import { LANGS, type Lang } from "./types";

// Guest names come in four shapes:
// - an adjective and a noun: "WonderfulCat", "GatoMaravilhoso", "すてきなネコ";
// - two nouns, a hybrid: "PotatoNinja", "BatataNinja", "ジャガイモ忍者";
// - a title and a noun, the title following the noun's Portuguese gender in every
//   language: "QueenFox", "RainhaRaposa", "キツネ女王";
// - now and then, a legendary meme name: "TGIF", "Sextou", "花金".
// Each row holds the same idea in every language, so the same guest number gives the
// same name, translated, to everyone in a room (whatever language each one plays in).
// Words are friendly or playfully silly, never insults; nouns avoid ones that are slurs
// or double meanings in Portuguese (vaca, anta, galinha, macaco...).

/** [English, Portuguese masculine, Portuguese feminine, Japanese (attributive form)]. */
type Adjective = readonly [en: string, ptM: string, ptF: string, ja: string];
/** [English, Portuguese, its grammatical gender, Japanese]. */
type Noun = readonly [en: string, pt: string, gender: "m" | "f", ja: string];
/** Masculine and feminine: [English, English, Portuguese, Portuguese, Japanese suffix, Japanese suffix]. */
type Title = readonly [
  enM: string,
  enF: string,
  ptM: string,
  ptF: string,
  jaM: string,
  jaF: string,
];
/** [English, Portuguese, Japanese]: the meme, or its local twin where one exists. */
type Legendary = readonly [en: string, pt: string, ja: string];

export const ADJECTIVES: readonly Adjective[] = [
  ["Brave", "Corajoso", "Corajosa", "勇敢な"],
  ["Sleepy", "Sonolento", "Sonolenta", "眠たい"],
  ["Hungry", "Faminto", "Faminta", "はらぺこ"],
  ["Happy", "Feliz", "Feliz", "ごきげんな"],
  ["Sneaky", "Sorrateiro", "Sorrateira", "忍び足の"],
  ["Clever", "Esperto", "Esperta", "賢い"],
  ["Curious", "Curioso", "Curiosa", "知りたがりの"],
  ["Fluffy", "Felpudo", "Felpuda", "ふわふわ"],
  ["Fuzzy", "Peludo", "Peluda", "もふもふ"],
  ["Cute", "Fofo", "Fofa", "かわいい"],
  ["Tiny", "Pequenino", "Pequenina", "ちいさな"],
  ["Giant", "Gigante", "Gigante", "でっかい"],
  ["Golden", "Dourado", "Dourada", "金色の"],
  ["Silver", "Prateado", "Prateada", "銀色の"],
  ["Purple", "Roxo", "Roxa", "むらさきの"],
  ["Blue", "Azul", "Azul", "青い"],
  ["Red", "Vermelho", "Vermelha", "赤い"],
  ["Green", "Verde", "Verde", "緑の"],
  ["Yellow", "Amarelo", "Amarela", "黄色い"],
  ["Pink", "Rosa", "Rosa", "ピンクの"],
  ["Orange", "Laranja", "Laranja", "オレンジの"],
  ["Turquoise", "Turquesa", "Turquesa", "ターコイズの"],
  ["Rainbow", "ArcoÍris", "ArcoÍris", "にじいろの"],
  ["Cosmic", "Cósmico", "Cósmica", "宇宙の"],
  ["Galactic", "Galáctico", "Galáctica", "銀河の"],
  ["Stellar", "Estelar", "Estelar", "星の"],
  ["Lunar", "Lunar", "Lunar", "月の"],
  ["Solar", "Solar", "Solar", "太陽の"],
  ["Quantum", "Quântico", "Quântica", "量子の"],
  ["Electric", "Elétrico", "Elétrica", "ビリビリ"],
  ["Digital", "Digital", "Digital", "デジタルな"],
  ["Pixel", "Pixelado", "Pixelada", "ドット絵の"],
  ["Neon", "Neon", "Neon", "ネオンの"],
  ["Turbo", "Turbo", "Turbo", "ターボ"],
  ["Mysterious", "Misterioso", "Misteriosa", "なぞの"],
  ["Secret", "Secreto", "Secreta", "ひみつの"],
  ["Hidden", "Escondido", "Escondida", "隠れた"],
  ["Invisible", "Invisível", "Invisível", "透明な"],
  ["Undercover", "Disfarçado", "Disfarçada", "変装した"],
  ["Lazy", "Preguiçoso", "Preguiçosa", "ぐうたら"],
  ["Grumpy", "Rabugento", "Rabugenta", "不機嫌な"],
  ["Shy", "Tímido", "Tímida", "照れ屋の"],
  ["Bold", "Ousado", "Ousada", "大胆な"],
  ["Quiet", "Quieto", "Quieta", "静かな"],
  ["Noisy", "Barulhento", "Barulhenta", "にぎやかな"],
  ["Lucky", "Sortudo", "Sortuda", "ラッキーな"],
  ["Speedy", "Veloz", "Veloz", "俊足の"],
  ["Quick", "Rápido", "Rápida", "すばやい"],
  ["Wild", "Selvagem", "Selvagem", "ワイルドな"],
  ["Gentle", "Gentil", "Gentil", "おだやかな"],
  ["Jolly", "Alegre", "Alegre", "陽気な"],
  ["Calm", "Tranquilo", "Tranquila", "のんびり"],
  ["Dizzy", "Zonzo", "Zonza", "ふらふら"],
  ["Fancy", "Chique", "Chique", "おしゃれな"],
  ["Cool", "Descolado", "Descolada", "クールな"],
  ["Fierce", "Feroz", "Feroz", "どう猛な"],
  ["Friendly", "Amigável", "Amigável", "人なつっこい"],
  ["Funny", "Engraçado", "Engraçada", "おもしろい"],
  ["Charming", "Charmoso", "Charmosa", "魅力的な"],
  ["Glowing", "Brilhante", "Brilhante", "光る"],
  ["Graceful", "Elegante", "Elegante", "優雅な"],
  ["Humble", "Humilde", "Humilde", "謙虚な"],
  ["Jumpy", "Saltitante", "Saltitante", "ぴょんぴょん"],
  ["Kind", "Bondoso", "Bondosa", "優しい"],
  ["Generous", "Generoso", "Generosa", "気前のいい"],
  ["Legendary", "Lendário", "Lendária", "伝説の"],
  ["Lively", "Animado", "Animada", "元気な"],
  ["Loyal", "Leal", "Leal", "忠実な"],
  ["Magic", "Mágico", "Mágica", "魔法の"],
  ["Majestic", "Majestoso", "Majestosa", "堂々とした"],
  ["Mighty", "Poderoso", "Poderosa", "最強の"],
  ["Nimble", "Ágil", "Ágil", "身軽な"],
  ["Noble", "Nobre", "Nobre", "高貴な"],
  ["Peculiar", "Peculiar", "Peculiar", "風変わりな"],
  ["Playful", "Brincalhão", "Brincalhona", "遊び好きの"],
  ["Polite", "Educado", "Educada", "礼儀正しい"],
  ["Proud", "Orgulhoso", "Orgulhosa", "誇り高い"],
  ["Radiant", "Radiante", "Radiante", "まぶしい"],
  ["Serious", "Sério", "Séria", "まじめな"],
  ["Shiny", "Reluzente", "Reluzente", "ピカピカの"],
  ["Silent", "Silencioso", "Silenciosa", "無口な"],
  ["Silly", "Bobo", "Boba", "とぼけた"],
  ["Smart", "Inteligente", "Inteligente", "頭のいい"],
  ["Smooth", "Suave", "Suave", "なめらかな"],
  ["Sparkly", "Cintilante", "Cintilante", "キラキラ"],
  ["Spotted", "Pintado", "Pintada", "水玉の"],
  ["Striped", "Listrado", "Listrada", "しましまの"],
  ["Stormy", "Tempestuoso", "Tempestuosa", "嵐の"],
  ["Tidy", "Arrumado", "Arrumada", "きれい好きの"],
  ["Tough", "Durão", "Durona", "タフな"],
  ["Cheeky", "Travesso", "Travessa", "いたずらな"],
  ["Wandering", "Errante", "Errante", "さすらいの"],
  ["Wise", "Sábio", "Sábia", "物知りの"],
  ["Ancient", "Antigo", "Antiga", "古代の"],
  ["Awesome", "Incrível", "Incrível", "すごい"],
  ["Busy", "Ocupado", "Ocupada", "いそがしい"],
  ["Hardworking", "Trabalhador", "Trabalhadora", "働き者の"],
  ["Chilly", "Friorento", "Friorenta", "寒がりの"],
  ["Clumsy", "Desastrado", "Desastrada", "ドジな"],
  ["Cozy", "Aconchegante", "Aconchegante", "ぬくぬく"],
  ["Crispy", "Crocante", "Crocante", "サクサクの"],
  ["Dreamy", "Sonhador", "Sonhadora", "夢見る"],
  ["Epic", "Épico", "Épica", "壮大な"],
  ["Icy", "Gelado", "Gelada", "こおりの"],
  ["Glorious", "Glorioso", "Gloriosa", "栄光の"],
  ["Heroic", "Heroico", "Heroica", "英雄の"],
  ["Honest", "Honesto", "Honesta", "正直な"],
  ["Wonderful", "Maravilhoso", "Maravilhosa", "すてきな"],
  ["Minty", "Mentolado", "Mentolada", "ミントの"],
  ["Misty", "Nebuloso", "Nebulosa", "霧の"],
  ["Nervous", "Nervoso", "Nervosa", "そわそわ"],
  ["Nocturnal", "Noturno", "Noturna", "夜ふかしの"],
  ["Optimistic", "Otimista", "Otimista", "前向きな"],
  ["Patient", "Paciente", "Paciente", "辛抱強い"],
  ["Rebel", "Rebelde", "Rebelde", "反抗期の"],
  ["Spooky", "Sombrio", "Sombria", "不気味な"],
  ["Sticky", "Grudento", "Grudenta", "ねばねば"],
  ["Stubborn", "Teimoso", "Teimosa", "がんこな"],
  ["Sturdy", "Robusto", "Robusta", "頑丈な"],
  ["Thoughtful", "Pensativo", "Pensativa", "考え中の"],
  ["Tropical", "Tropical", "Tropical", "南国の"],
  ["Vibrant", "Vibrante", "Vibrante", "鮮やかな"],
  ["Warm", "Quentinho", "Quentinha", "ほかほか"],
  ["Dancing", "Dançarino", "Dançarina", "踊る"],
  ["Singing", "Cantor", "Cantora", "歌う"],
  ["Flying", "Voador", "Voadora", "空飛ぶ"],
  ["Sporty", "Esportista", "Esportista", "スポーティな"],
  ["Artistic", "Artista", "Artista", "芸術家の"],
  ["Musical", "Musical", "Musical", "音楽好きの"],
  ["Retro", "Retrô", "Retrô", "レトロな"],
  ["Classic", "Clássico", "Clássica", "クラシックな"],
  ["Modern", "Moderno", "Moderna", "モダンな"],
  ["Famous", "Famoso", "Famosa", "有名な"],
  ["Lost", "Perdido", "Perdida", "迷子の"],
  ["Smiley", "Risonho", "Risonha", "にこにこ"],
  ["Chatty", "Tagarela", "Tagarela", "おしゃべりな"],
  ["Hasty", "Apressado", "Apressada", "せっかちな"],
  ["Gourmet", "Gourmet", "Gourmet", "グルメな"],
  ["Dramatic", "Dramático", "Dramática", "おおげさな"],
  ["Fabulous", "Fabuloso", "Fabulosa", "ゴージャスな"],
  ["Free", "Livre", "Livre", "自由な"],
  ["Sour", "Azedo", "Azeda", "すっぱい"],
  ["Salty", "Salgado", "Salgada", "しょっぱい"],
  ["Sweet", "Doce", "Doce", "あまい"],
  ["Fiery", "Flamejante", "Flamejante", "炎の"],
  ["Arctic", "Ártico", "Ártica", "北極の"],
  ["Urban", "Urbano", "Urbana", "都会の"],
  ["Confident", "Confiante", "Confiante", "自信満々の"],
  ["Relaxed", "Relaxado", "Relaxada", "リラックスした"],
  ["Tired", "Cansado", "Cansada", "お疲れの"],
  ["Bored", "Entediado", "Entediada", "退屈な"],
  ["Excited", "Empolgado", "Empolgada", "わくわく"],
  ["Surprised", "Surpreso", "Surpresa", "びっくり"],
  ["Confused", "Confuso", "Confusa", "混乱した"],
  ["Snoring", "Roncador", "Roncadora", "いびきの"],
  ["Sleepwalking", "Sonâmbulo", "Sonâmbula", "寝ぼけた"],
  ["Barefoot", "Descalço", "Descalça", "はだしの"],
  ["Infinite", "Infinito", "Infinita", "無限の"],
  ["Lone", "Solitário", "Solitária", "一匹狼の"],
  ["Sunny", "Ensolarado", "Ensolarada", "晴れやかな"],
  ["Snowy", "Nevado", "Nevada", "雪の"],
  ["Rainy", "Chuvoso", "Chuvosa", "雨の"],
  ["Daring", "Destemido", "Destemida", "恐れ知らずの"],
  ["Valiant", "Valente", "Valente", "勇ましい"],
  ["Witty", "Espirituoso", "Espirituosa", "機転の利く"],
  ["Cheerful", "Contente", "Contente", "朗らかな"],
  ["Bubbly", "Borbulhante", "Borbulhante", "あわあわ"],
  ["Juicy", "Suculento", "Suculenta", "ジューシーな"],
  ["Tasty", "Saboroso", "Saborosa", "おいしい"],
  ["Toasty", "Tostado", "Tostada", "こんがり"],
  ["Frosty", "Congelado", "Congelada", "凍った"],
  ["Muddy", "Enlameado", "Enlameada", "どろんこ"],
  ["Sassy", "Atrevido", "Atrevida", "生意気な"],
  ["Royal", "Real", "Real", "王家の"],
  ["Cyber", "Cibernético", "Cibernética", "サイバーな"],
  ["Supersonic", "Supersônico", "Supersônica", "超音速の"],
  ["Masked", "Mascarado", "Mascarada", "覆面の"],
  ["Squishy", "Molinho", "Molinha", "もちもち"],
  ["Round", "Redondo", "Redonda", "まんまるの"],
  ["Glittery", "Purpurinado", "Purpurinada", "ラメ入りの"],
  ["Pastel", "Pastel", "Pastel", "パステルの"],
  ["Silky", "Sedoso", "Sedosa", "サラサラ"],
  ["Brilliant", "Genial", "Genial", "天才的な"],
  ["Celestial", "Celestial", "Celestial", "天空の"],
  ["Mythic", "Mítico", "Mítica", "神話の"],
  ["Enchanted", "Encantado", "Encantada", "魅惑の"],
  ["Sneezy", "Espirrento", "Espirrenta", "くしゃみ中の"],
  ["Hopeful", "Esperançoso", "Esperançosa", "希望の"],
  ["Nerdy", "Nerd", "Nerd", "オタクな"],
  ["Punk", "Punk", "Punk", "パンクな"],
  ["Groovy", "Gingado", "Gingada", "グルーヴィーな"],
  ["Funky", "Funkeiro", "Funkeira", "ファンキーな"],
  ["Victorious", "Vitorioso", "Vitoriosa", "勝利の"],
  ["Undefeated", "Invicto", "Invicta", "無敗の"],
  ["Homemade", "Caseiro", "Caseira", "手作りの"],
  ["Creamy", "Cremoso", "Cremosa", "クリーミーな"],
  ["Fizzy", "Efervescente", "Efervescente", "シュワシュワ"],
  ["Caramel", "Caramelado", "Caramelada", "キャラメルの"],
  ["Chocolate", "Achocolatado", "Achocolatada", "チョコの"],
  ["Buttery", "Amanteigado", "Amanteigada", "バターの"],
  ["Plaid", "Xadrez", "Xadrez", "チェックの"],
  ["Origami", "Origami", "Origami", "折り紙の"],
  ["Martian", "Marciano", "Marciana", "火星の"],
  ["Volcanic", "Vulcânico", "Vulcânica", "火山の"],
  ["Oceanic", "Oceânico", "Oceânica", "大海の"],
  ["Festive", "Festivo", "Festiva", "お祭りの"],
  ["Supreme", "Supremo", "Suprema", "至高の"],
  ["Ultimate", "Definitivo", "Definitiva", "究極の"],
  ["Whistling", "Assobiador", "Assobiadora", "口笛好きの"],
  ["Adventurous", "Aventureiro", "Aventureira", "冒険好きの"],
  ["Creative", "Criativo", "Criativa", "創造的な"],
  ["Stylish", "Estiloso", "Estilosa", "イケてる"],
  ["Wacky", "Maluco", "Maluca", "ハチャメチャな"],
  ["Metallic", "Metálico", "Metálica", "メタリックな"],
  ["Bronze", "Bronzeado", "Bronzeada", "銅色の"],
  ["Crimson", "Carmesim", "Carmesim", "深紅の"],
  ["Emerald", "Esmeralda", "Esmeralda", "エメラルドの"],
  ["Gray", "Cinza", "Cinza", "灰色の"],
  ["Platinum", "Platinado", "Platinada", "プラチナの"],
  ["Zippy", "Ligeiro", "Ligeira", "すばしこい"],
  ["Bouncy", "Elástico", "Elástica", "ぷるぷる"],
  ["Chill", "Sossegado", "Sossegada", "まったり"],
  ["Starry", "Estrelado", "Estrelada", "星空の"],
  ["Moonlit", "Enluarado", "Enluarada", "月夜の"],
  ["Dusty", "Empoeirado", "Empoeirada", "ほこりまみれの"],
  ["Soggy", "Encharcado", "Encharcada", "びしょぬれの"],
  ["Leafy", "Frondoso", "Frondosa", "葉っぱの"],
  ["Spicy", "Picante", "Picante", "ピリ辛の"],
  ["Fruity", "Frutado", "Frutada", "フルーティーな"],
  ["Cheesy", "Queijudo", "Queijuda", "チーズ味の"],
  ["Dandy", "Janota", "Janota", "ダンディな"],
  ["Frisky", "Serelepe", "Serelepe", "やんちゃな"],
  ["Merry", "Festeiro", "Festeira", "浮かれた"],
  ["Velvety", "Aveludado", "Aveludada", "ビロードの"],
  ["Atomic", "Atômico", "Atômica", "原子の"],
  ["Hyper", "Hiperativo", "Hiperativa", "ハイパーな"],
  ["Imperial", "Imperial", "Imperial", "帝国の"],
  ["Alpine", "Alpino", "Alpina", "高山の"],
  ["Peaceful", "Pacífico", "Pacífica", "平和な"],
  ["Feathery", "Emplumado", "Emplumada", "羽毛の"],
  ["Robotic", "Robótico", "Robótica", "ロボの"],
  ["Mini", "Mini", "Mini", "ミニ"],
  ["Jumbo", "Jumbo", "Jumbo", "ジャンボ"],
  ["Yawning", "Bocejante", "Bocejante", "あくび中の"],
  ["Thrifty", "Econômico", "Econômica", "節約家の"],
  ["Punctual", "Pontual", "Pontual", "時間厳守の"],
  ["Sincere", "Sincero", "Sincera", "素直な"],
  ["Woolly", "Lanudo", "Lanuda", "もこもこ"],
  ["Glossy", "Lustroso", "Lustrosa", "つやつや"],
];

export const NOUNS: readonly Noun[] = [
  ["Cat", "Gato", "m", "ネコ"],
  ["Dog", "Cachorro", "m", "イヌ"],
  ["Fox", "Raposa", "f", "キツネ"],
  ["Panda", "Panda", "m", "パンダ"],
  ["Penguin", "Pinguim", "m", "ペンギン"],
  ["Owl", "Coruja", "f", "フクロウ"],
  ["Rabbit", "Coelho", "m", "ウサギ"],
  ["Bear", "Urso", "m", "クマ"],
  ["Tiger", "Tigre", "m", "トラ"],
  ["Lion", "Leão", "m", "ライオン"],
  ["Wolf", "Lobo", "m", "オオカミ"],
  ["Frog", "Sapo", "m", "カエル"],
  ["Turtle", "Tartaruga", "f", "カメ"],
  ["Duck", "Pato", "m", "アヒル"],
  ["Goose", "Ganso", "m", "ガチョウ"],
  ["Chick", "Pintinho", "m", "ヒヨコ"],
  ["Piglet", "Porquinho", "m", "コブタ"],
  ["Pony", "Pônei", "m", "ポニー"],
  ["Goat", "Cabra", "f", "ヤギ"],
  ["Sheep", "Ovelha", "f", "ヒツジ"],
  ["Llama", "Lhama", "f", "ラマ"],
  ["Alpaca", "Alpaca", "f", "アルパカ"],
  ["Camel", "Camelo", "m", "ラクダ"],
  ["Giraffe", "Girafa", "f", "キリン"],
  ["Elephant", "Elefante", "m", "ゾウ"],
  ["Hippo", "Hipopótamo", "m", "カバ"],
  ["Rhino", "Rinoceronte", "m", "サイ"],
  ["Zebra", "Zebra", "f", "シマウマ"],
  ["Kangaroo", "Canguru", "m", "カンガルー"],
  ["Koala", "Coala", "m", "コアラ"],
  ["Sloth", "Preguiça", "f", "ナマケモノ"],
  ["Capybara", "Capivara", "f", "カピバラ"],
  ["Armadillo", "Tatu", "m", "アルマジロ"],
  ["Anteater", "Tamanduá", "m", "アリクイ"],
  ["Toucan", "Tucano", "m", "オオハシ"],
  ["Parrot", "Papagaio", "m", "オウム"],
  ["Flamingo", "Flamingo", "m", "フラミンゴ"],
  ["Peacock", "Pavão", "m", "クジャク"],
  ["Swan", "Cisne", "m", "ハクチョウ"],
  ["Eagle", "Águia", "f", "ワシ"],
  ["Falcon", "Falcão", "m", "ハヤブサ"],
  ["Crow", "Corvo", "m", "カラス"],
  ["Pigeon", "Pombo", "m", "ハト"],
  ["Sparrow", "Pardal", "m", "スズメ"],
  ["Seagull", "Gaivota", "f", "カモメ"],
  ["Pelican", "Pelicano", "m", "ペリカン"],
  ["Ostrich", "Avestruz", "m", "ダチョウ"],
  ["Bat", "Morcego", "m", "コウモリ"],
  ["Hedgehog", "Ouriço", "m", "ハリネズミ"],
  ["Hamster", "Hamster", "m", "ハムスター"],
  ["Mouse", "Ratinho", "m", "ネズミ"],
  ["Squirrel", "Esquilo", "m", "リス"],
  ["Beaver", "Castor", "m", "ビーバー"],
  ["Otter", "Lontra", "f", "カワウソ"],
  ["Raccoon", "Guaxinim", "m", "アライグマ"],
  ["Badger", "Texugo", "m", "アナグマ"],
  ["Skunk", "Gambá", "m", "スカンク"],
  ["Deer", "Cervo", "m", "シカ"],
  ["Moose", "Alce", "m", "ヘラジカ"],
  ["Reindeer", "Rena", "f", "トナカイ"],
  ["Seal", "Foca", "f", "アザラシ"],
  ["Walrus", "Morsa", "f", "セイウチ"],
  ["Dolphin", "Golfinho", "m", "イルカ"],
  ["Shark", "Tubarão", "m", "サメ"],
  ["Octopus", "Polvo", "m", "タコ"],
  ["Crab", "Caranguejo", "m", "カニ"],
  ["Lobster", "Lagosta", "f", "ロブスター"],
  ["Shrimp", "Camarão", "m", "エビ"],
  ["Pufferfish", "Baiacu", "m", "フグ"],
  ["Snail", "Caracol", "m", "カタツムリ"],
  ["Bee", "Abelha", "f", "ミツバチ"],
  ["Ant", "Formiga", "f", "アリ"],
  ["Ladybug", "Joaninha", "f", "テントウムシ"],
  ["Butterfly", "Borboleta", "f", "チョウチョ"],
  ["Dragonfly", "Libélula", "f", "トンボ"],
  ["Cricket", "Grilo", "m", "コオロギ"],
  ["Beetle", "Besouro", "m", "カブトムシ"],
  ["Spider", "Aranha", "f", "クモ"],
  ["Lizard", "Lagarto", "m", "トカゲ"],
  ["Gecko", "Lagartixa", "f", "ヤモリ"],
  ["Chameleon", "Camaleão", "m", "カメレオン"],
  ["Crocodile", "Crocodilo", "m", "ワニ"],
  ["Alligator", "Jacaré", "m", "アリゲーター"],
  ["Dinosaur", "Dinossauro", "m", "恐竜"],
  ["Mammoth", "Mamute", "m", "マンモス"],
  ["Dodo", "Dodô", "m", "ドードー"],
  ["Platypus", "Ornitorrinco", "m", "カモノハシ"],
  ["Axolotl", "Axolote", "m", "ウーパールーパー"],
  ["Narwhal", "Narval", "m", "イッカク"],
  ["Leopard", "Leopardo", "m", "ヒョウ"],
  ["Jaguar", "Onça", "f", "ジャガー"],
  ["Cheetah", "Guepardo", "m", "チーター"],
  ["Lynx", "Lince", "m", "オオヤマネコ"],
  ["Puma", "Puma", "m", "ピューマ"],
  ["Hyena", "Hiena", "f", "ハイエナ"],
  ["Meerkat", "Suricato", "m", "ミーアキャット"],
  ["Lemur", "Lêmure", "m", "キツネザル"],
  ["Chinchilla", "Chinchila", "f", "チンチラ"],
  ["Ferret", "Furão", "m", "フェレット"],
  ["Yak", "Iaque", "m", "ヤク"],
  ["Bison", "Bisão", "m", "バイソン"],
  ["Quail", "Codorna", "f", "ウズラ"],
  ["Kiwi", "Kiwi", "m", "キーウィ"],
  ["Pangolin", "Pangolim", "m", "センザンコウ"],
  ["Wombat", "Vombate", "m", "ウォンバット"],
  ["Dragon", "Dragão", "m", "ドラゴン"],
  ["Unicorn", "Unicórnio", "m", "ユニコーン"],
  ["Phoenix", "Fênix", "f", "フェニックス"],
  ["Griffin", "Grifo", "m", "グリフォン"],
  ["Yeti", "Iéti", "m", "イエティ"],
  ["Ghost", "Fantasma", "m", "おばけ"],
  ["Robot", "Robô", "m", "ロボット"],
  ["Alien", "Alienígena", "m", "宇宙人"],
  ["Wizard", "Mago", "m", "魔法使い"],
  ["Ninja", "Ninja", "m", "忍者"],
  ["Pirate", "Pirata", "m", "海賊"],
  ["Knight", "Cavaleiro", "m", "騎士"],
  ["Viking", "Viking", "m", "バイキング"],
  ["Astronaut", "Astronauta", "m", "宇宙飛行士"],
  ["Detective", "Detetive", "m", "探偵"],
  ["Chef", "Chef", "m", "シェフ"],
  ["Mermaid", "Sereia", "f", "人魚"],
  ["Elf", "Elfo", "m", "エルフ"],
  ["Gnome", "Gnomo", "m", "小人"],
  ["Vampire", "Vampiro", "m", "吸血鬼"],
  ["Zombie", "Zumbi", "m", "ゾンビ"],
  ["Mummy", "Múmia", "f", "ミイラ"],
  ["Kraken", "Kraken", "m", "クラーケン"],
  ["Sphinx", "Esfinge", "f", "スフィンクス"],
  ["Pegasus", "Pégaso", "m", "ペガサス"],
  ["Fairy", "Fada", "f", "妖精"],
  ["Goblin", "Duende", "m", "ゴブリン"],
  ["Potato", "Batata", "f", "ジャガイモ"],
  ["Pancake", "Panqueca", "f", "パンケーキ"],
  ["Cookie", "Biscoito", "m", "クッキー"],
  ["Donut", "Rosquinha", "f", "ドーナツ"],
  ["Waffle", "Waffle", "m", "ワッフル"],
  ["Muffin", "Bolinho", "m", "マフィン"],
  ["Pudding", "Pudim", "m", "プリン"],
  ["Taco", "Taco", "m", "タコス"],
  ["Ramen", "Lámen", "m", "ラーメン"],
  ["Pickle", "Picles", "m", "ピクルス"],
  ["Avocado", "Abacate", "m", "アボカド"],
  ["Pineapple", "Abacaxi", "m", "パイナップル"],
  ["Mango", "Manga", "f", "マンゴー"],
  ["Lemon", "Limão", "m", "レモン"],
  ["Peach", "Pêssego", "m", "モモ"],
  ["Tomato", "Tomate", "m", "トマト"],
  ["Carrot", "Cenoura", "f", "ニンジン"],
  ["Broccoli", "Brócolis", "m", "ブロッコリー"],
  ["Mushroom", "Cogumelo", "m", "キノコ"],
  ["Pumpkin", "Abóbora", "f", "カボチャ"],
  ["Popcorn", "Pipoca", "f", "ポップコーン"],
  ["Cupcake", "Cupcake", "m", "カップケーキ"],
  ["Croissant", "Croissant", "m", "クロワッサン"],
  ["Sushi", "Sushi", "m", "寿司"],
  ["Tofu", "Tofu", "m", "豆腐"],
  ["Mochi", "Mochi", "m", "おもち"],
  ["Nugget", "Nugget", "m", "ナゲット"],
  ["Cactus", "Cacto", "m", "サボテン"],
  ["Acorn", "Bolota", "f", "ドングリ"],
  ["Cloud", "Nuvem", "f", "雲"],
  ["Comet", "Cometa", "m", "すい星"],
  ["Meteor", "Meteoro", "m", "流れ星"],
  ["Rocket", "Foguete", "m", "ロケット"],
  ["Volcano", "Vulcão", "m", "火山"],
  ["Tornado", "Tornado", "m", "竜巻"],
  ["Teapot", "Bule", "m", "ティーポット"],
  ["Toaster", "Torradeira", "f", "トースター"],
  ["Sock", "Meia", "f", "くつした"],
  ["Pillow", "Travesseiro", "m", "まくら"],
  ["Balloon", "Balão", "m", "風船"],
  ["Kite", "Pipa", "f", "カイト"],
  ["Orca", "Orca", "f", "シャチ"],
  ["Manatee", "PeixeBoi", "m", "マナティー"],
  ["Stingray", "Arraia", "f", "エイ"],
  ["Jellyfish", "ÁguaViva", "f", "クラゲ"],
  ["Seahorse", "CavaloMarinho", "m", "タツノオトシゴ"],
  ["Clownfish", "PeixePalhaço", "m", "クマノミ"],
  ["Hummingbird", "BeijaFlor", "m", "ハチドリ"],
  ["Macaw", "Arara", "f", "コンゴウインコ"],
  ["Puffin", "PapagaioDoMar", "m", "ツノメドリ"],
  ["Stork", "Cegonha", "f", "コウノトリ"],
  ["Rooster", "Galo", "m", "オンドリ"],
  ["Fennec", "Feneco", "m", "フェネック"],
  ["Coati", "Quati", "m", "ハナグマ"],
  ["Ocelot", "Jaguatirica", "f", "オセロット"],
  ["PolarBear", "UrsoPolar", "m", "シロクマ"],
  ["Koi", "Carpa", "f", "コイ"],
  ["Mongoose", "Mangusto", "m", "マングース"],
  ["Iguana", "Iguana", "f", "イグアナ"],
  ["Tortoise", "Jabuti", "m", "リクガメ"],
  ["Tadpole", "Girino", "m", "オタマジャクシ"],
  ["Firefly", "VagaLume", "m", "ホタル"],
  ["Tanuki", "Tanuki", "m", "タヌキ"],
  ["Centaur", "Centauro", "m", "ケンタウロス"],
  ["Cyclops", "Ciclope", "m", "サイクロプス"],
  ["Golem", "Golem", "m", "ゴーレム"],
  ["Chupacabra", "Chupacabra", "m", "チュパカブラ"],
  ["Bigfoot", "PéGrande", "m", "ビッグフット"],
  ["Werewolf", "Lobisomem", "m", "狼男"],
  ["Cowboy", "Caubói", "m", "カウボーイ"],
  ["Samurai", "Samurai", "m", "侍"],
  ["Spy", "Espião", "m", "スパイ"],
  ["Explorer", "Explorador", "m", "探検家"],
  ["Scientist", "Cientista", "m", "科学者"],
  ["Firefighter", "Bombeiro", "m", "消防士"],
  ["Sailor", "Marinheiro", "m", "船乗り"],
  ["Surfer", "Surfista", "m", "サーファー"],
  ["Poet", "Poeta", "m", "詩人"],
  ["Gamer", "Gamer", "m", "ゲーマー"],
  ["Strawberry", "Morango", "m", "イチゴ"],
  ["Watermelon", "Melancia", "f", "スイカ"],
  ["Cheese", "Queijo", "m", "チーズ"],
  ["Pizza", "Pizza", "f", "ピザ"],
  ["Burger", "Hambúrguer", "m", "ハンバーガー"],
  ["Dumpling", "Guioza", "m", "ギョーザ"],
  ["RiceBall", "Oniguiri", "m", "おにぎり"],
  ["CheeseBread", "PãoDeQueijo", "m", "チーズパン"],
  ["Tapioca", "Tapioca", "f", "タピオカ"],
  ["Churro", "Churro", "m", "チュロス"],
  ["Marshmallow", "Marshmallow", "m", "マシュマロ"],
  ["Takoyaki", "Takoyaki", "m", "たこ焼き"],
  ["Sunflower", "Girassol", "m", "ヒマワリ"],
  ["Bonsai", "Bonsai", "m", "盆栽"],
  ["Crystal", "Cristal", "m", "水晶"],
  ["Snowman", "BonecoDeNeve", "m", "雪だるま"],
  ["Planet", "Planeta", "m", "惑星"],
  ["UFO", "Óvni", "m", "ユーフォー"],
  ["Umbrella", "GuardaChuva", "m", "カサ"],
  ["Ukulele", "Ukulele", "m", "ウクレレ"],
  ["Slipper", "Chinelo", "m", "スリッパ"],
  ["Submarine", "Submarino", "m", "潜水艦"],
  ["Gnu", "Gnu", "m", "ヌー"],
  ["Emu", "Emu", "m", "エミュー"],
  ["Newt", "Tritão", "m", "イモリ"],
  ["Hare", "Lebre", "f", "ノウサギ"],
  ["Lamb", "Cordeiro", "m", "コヒツジ"],
  ["Kitten", "Gatinho", "m", "子ネコ"],
  ["Eel", "Enguia", "f", "ウナギ"],
  ["Tuna", "Atum", "m", "マグロ"],
  ["Salmon", "Salmão", "m", "サケ"],
  ["Oni", "Oni", "m", "鬼"],
  ["Tengu", "Tengu", "m", "天狗"],
  ["Minotaur", "Minotauro", "m", "ミノタウロス"],
  ["Baker", "Padeiro", "m", "パン屋"],
  ["Painter", "Pintor", "m", "画家"],
  ["Pilot", "Piloto", "m", "パイロット"],
  ["Miner", "Mineiro", "m", "炭鉱夫"],
  ["Bagel", "Bagel", "m", "ベーグル"],
  ["Brownie", "Brownie", "m", "ブラウニー"],
  ["Noodle", "Macarrão", "m", "麺"],
  ["Melon", "Melão", "m", "メロン"],
  ["Pear", "Pera", "f", "洋ナシ"],
  ["Jelly", "Gelatina", "f", "ゼリー"],
  ["Yoyo", "Ioiô", "m", "ヨーヨー"],
  ["Pebble", "Pedrinha", "f", "小石"],
  ["Moon", "Lua", "f", "月"],
  ["Drum", "Tambor", "m", "タイコ"],
];

/** Japanese puts the title after the noun, as a suffix ("ネコ船長", "キツネ女王"). */
export const TITLES: readonly Title[] = [
  ["Captain", "Captain", "Capitão", "Capitã", "船長", "船長"],
  ["Doctor", "Doctor", "Doutor", "Doutora", "博士", "博士"],
  ["Professor", "Professor", "Professor", "Professora", "教授", "教授"],
  ["Agent", "Agent", "Agente", "Agente", "捜査官", "捜査官"],
  ["General", "General", "General", "General", "将軍", "将軍"],
  ["Admiral", "Admiral", "Almirante", "Almirante", "提督", "提督"],
  ["Sergeant", "Sergeant", "Sargento", "Sargento", "軍曹", "軍曹"],
  ["Colonel", "Colonel", "Coronel", "Coronel", "大佐", "大佐"],
  ["Major", "Major", "Major", "Major", "少佐", "少佐"],
  ["Lieutenant", "Lieutenant", "Tenente", "Tenente", "中尉", "中尉"],
  ["Commander", "Commander", "Comandante", "Comandante", "司令官", "司令官"],
  ["Mayor", "Mayor", "Prefeito", "Prefeita", "市長", "市長"],
  ["Governor", "Governor", "Governador", "Governadora", "知事", "知事"],
  ["President", "President", "Presidente", "Presidente", "大統領", "大統領"],
  ["Senator", "Senator", "Senador", "Senadora", "議員", "議員"],
  ["Minister", "Minister", "Ministro", "Ministra", "大臣", "大臣"],
  ["Ambassador", "Ambassador", "Embaixador", "Embaixadora", "大使", "大使"],
  ["Judge", "Judge", "Juiz", "Juíza", "裁判長", "裁判長"],
  ["Sheriff", "Sheriff", "Xerife", "Xerife", "保安官", "保安官"],
  ["Officer", "Officer", "Guarda", "Guarda", "巡査", "巡査"],
  ["Inspector", "Inspector", "Inspetor", "Inspetora", "警部", "警部"],
  ["King", "Queen", "Rei", "Rainha", "大王", "女王"],
  ["Prince", "Princess", "Príncipe", "Princesa", "王子", "姫"],
  ["Emperor", "Empress", "Imperador", "Imperatriz", "皇帝", "女帝"],
  ["Duke", "Duchess", "Duque", "Duquesa", "公爵", "公爵夫人"],
  ["Marquis", "Marchioness", "Marquês", "Marquesa", "侯爵", "侯爵夫人"],
  ["Count", "Countess", "Conde", "Condessa", "伯爵", "伯爵夫人"],
  ["Viscount", "Viscountess", "Visconde", "Viscondessa", "子爵", "子爵夫人"],
  ["Baron", "Baroness", "Barão", "Baronesa", "男爵", "男爵夫人"],
  ["Lord", "Lady", "Lorde", "Lady", "卿", "夫人"],
  ["Pharaoh", "Pharaoh", "Faraó", "Faraó", "ファラオ", "ファラオ"],
  ["Overlord", "Overlord", "Soberano", "Soberana", "魔王", "魔王"],
  ["Master", "Master", "Mestre", "Mestra", "師匠", "師匠"],
  ["Sensei", "Sensei", "Sensei", "Sensei", "先生", "先生"],
  ["Elder", "Elder", "Ancião", "Anciã", "長老", "長老"],
  ["Chief", "Chief", "Chefe", "Chefe", "隊長", "隊長"],
  ["Boss", "Boss", "Chefão", "Chefona", "親分", "親分"],
  ["CEO", "CEO", "CEO", "CEO", "社長", "社長"],
  ["Manager", "Manager", "Gerente", "Gerente", "店長", "店長"],
  ["Principal", "Principal", "Diretor", "Diretora", "校長", "校長"],
  ["Coach", "Coach", "Técnico", "Técnica", "監督", "監督"],
  ["Champion", "Champion", "Campeão", "Campeã", "王者", "王者"],
  ["Hero", "Heroine", "Herói", "Heroína", "勇者", "勇者"],
  ["Guardian", "Guardian", "Guardião", "Guardiã", "守護神", "守護神"],
  ["Tycoon", "Tycoon", "Magnata", "Magnata", "大富豪", "大富豪"],
  ["Mister", "Madam", "Senhor", "Senhora", "さん", "さん"],
  ["Uncle", "Aunt", "Tio", "Tia", "おじさん", "おばさん"],
  ["Grandpa", "Grandma", "Vovô", "Vovó", "じいじ", "ばあば"],
  ["Papa", "Mama", "Papai", "Mamãe", "パパ", "ママ"],
  ["Bro", "Sis", "Mano", "Mana", "兄貴", "姉貴"],
  ["Baby", "Baby", "Bebê", "Bebê", "ちゃん", "ちゃん"],
  ["Sir", "Dame", "Sir", "Dama", "殿", "御前"],
  ["Shogun", "Shogun", "Xogum", "Xogum", "大将", "大将"],
  ["Dean", "Dean", "Reitor", "Reitora", "学長", "学長"],
  ["Chancellor", "Chancellor", "Chanceler", "Chanceler", "宰相", "宰相"],
  ["Cadet", "Cadet", "Cadete", "Cadete", "候補生", "候補生"],
  ["Private", "Private", "Soldado", "Soldada", "二等兵", "二等兵"],
  ["Marshal", "Marshal", "Marechal", "Marechal", "元帥", "元帥"],
  ["Archduke", "Archduchess", "Arquiduque", "Arquiduquesa", "大公", "大公妃"],
  ["Squire", "Squire", "Escudeiro", "Escudeira", "従者", "従者"],
  ["Paladin", "Paladin", "Paladino", "Paladina", "聖騎士", "聖騎士"],
  ["Maestro", "Maestro", "Maestro", "Maestrina", "マエストロ", "マエストロ"],
  ["Ace", "Ace", "Ás", "Ás", "エース", "エース"],
  ["Idol", "Idol", "Ídolo", "Ídolo", "アイドル", "アイドル"],
  ["Streamer", "Streamer", "Streamer", "Streamer", "配信者", "配信者"],
  ["Senpai", "Senpai", "Senpai", "Senpai", "先輩", "先輩"],
  ["Rookie", "Rookie", "Novato", "Novata", "新人", "新人"],
  ["Buddy", "Buddy", "Parça", "Parça", "くん", "くん"],
];

/** Rare names, hand-picked: one new guest in a hundred gets one (see LEGENDARY_CHANCE). */
export const LEGENDARY: readonly Legendary[] = [
  ["Doge", "Doge", "ドージ"],
  ["Stonks", "Stonks", "ストンクス"],
  ["NyanCat", "NyanCat", "ニャンキャット"],
  ["PopCat", "PopCat", "ポップキャット"],
  ["HappyHappyCat", "GatoHappyHappy", "ハッピーハッピー猫"],
  ["HuhCat", "GatoHuh", "ハァ猫"],
  ["BananaCat", "GatoBanana", "バナナ猫"],
  ["ChipiChipiChapa", "ChipiChipiChapa", "チピチピチャパ"],
  ["OiiaOiiaCat", "GatoOiiaOiia", "オイアオイア猫"],
  ["VibingCat", "GatoVibando", "ノリノリ猫"],
  ["KeyboardCat", "GatoTecladista", "キーボード猫"],
  ["CeilingCat", "GatoDoTeto", "天井猫"],
  ["Longcat", "Longcat", "ロングキャット"],
  ["BongoCat", "BongoCat", "ボンゴキャット"],
  ["Bingus", "Bingus", "ビンガス"],
  ["BigFloppa", "BigFloppa", "ビッグフロッパ"],
  ["Cheems", "Cheems", "チームズ"],
  ["Doggo", "Doguinho", "わんこ"],
  ["CaramelMutt", "ViraLataCaramelo", "キャラメル犬"],
  ["MooDeng", "MooDeng", "ムーデン"],
  ["PedroRaccoon", "GuaxinimPedro", "ペドロアライグマ"],
  ["SadHamster", "HamsterTriste", "悲しいハムスター"],
  ["TrashPanda", "PandaDoLixo", "ゴミパンダ"],
  ["DangerNoodle", "MacarrãoPerigoso", "危険なヌードル"],
  ["SeaPancake", "PanquecaDoMar", "海のパンケーキ"],
  ["AbsoluteUnit", "UnidadeAbsoluta", "規格外"],
  ["DatBoi", "DatBoi", "ダットボーイ"],
  ["Trollface", "Trollface", "トロールフェイス"],
  ["Rickroll", "Rickroll", "リックロール"],
  ["ThisIsFine", "TáTudoBem", "大丈夫だ問題ない"],
  ["GalaxyBrain", "CérebroGaláctico", "銀河脳"],
  ["GigaChad", "GigaChad", "ギガチャド"],
  ["Bonk", "Bonk", "ボンク"],
  ["Moai", "Moai", "モアイ"],
  ["Skibidi", "Skibidi", "スキビディ"],
  ["Amogus", "Amogus", "アモングス"],
  ["Kappa", "Kappa", "カッパ"],
  ["Hackerman", "Hackerman", "ハッカーマン"],
  ["CakeIsALie", "OBoloÉMentira", "ケーキは嘘"],
  ["OverNineThousand", "MaisDeOitoMil", "戦闘力53万"],
  ["FinalAnswer", "RespostaFinal", "ファイナルアンサー"],
  ["MainCharacter", "Protagonista", "主人公"],
  ["RageQuit", "RageQuit", "台パン"],
  ["PressF", "PressF", "Fで敬意を"],
  ["NullPointer", "NullPointer", "ぬるぽ"],
  ["Orz", "Orz", "orz"],
  ["PleadingFace", "CarinhaPidona", "ぴえん"],
  ["SmugFace", "CaraDeConvencido", "ドヤ顔"],
  ["Rofl", "Kkkkkkk", "大草原"],
  ["TGIF", "Sextou", "花金"],
  ["DadJoker", "TioDoPavê", "ダジャレおじさん"],
  ["GifOrJif", "BiscoitoOuBolacha", "きのこたけのこ"],
  ["BrrBrrPatapim", "BrrBrrPatapim", "ブルブルパタピン"],
  ["TungTungSahur", "TungTungSahur", "トゥントゥンサフール"],
  ["Chimpanzini", "Chimpanzini", "チンパンジーニ"],
  ["Birb", "Birb", "トリさん"],
  ["Snek", "Snek", "ヘビちゃん"],
  ["Blep", "Blep", "ペロッ"],
  ["Boop", "Boop", "ぷにっ"],
  ["Rawr", "Rawr", "がおー"],
  ["LongBoi", "LongBoi", "ロングボーイ"],
  ["Hampter", "Hampter", "ハムプター"],
  ["HamsterDance", "HamsterDance", "ハムスターダンス"],
  ["CrabRave", "CrabRave", "カニレイブ"],
  ["DancingBaby", "BebêDançante", "ダンシングベイビー"],
  ["NumaNuma", "NumaNuma", "恋のマイアヒ"],
  ["PPAP", "PPAP", "ペンパイナッポー"],
  ["BluePen", "CanetaAzul", "青いペン"],
  ["ToTheMoon", "RumoÀLua", "月まで"],
  ["Thonk", "Thonk", "考え中"],
  ["AllYourBase", "TodaSuaBase", "君達の基地"],
  ["DoABarrelRoll", "FazUmBarrelRoll", "バレルロール"],
  ["ItsATrap", "ÉUmaArmadilha", "罠だ"],
  ["Wololo", "Wololo", "ウォロロ"],
  ["Hadouken", "Hadouken", "波動拳"],
  ["Kamehameha", "Kamehameha", "かめはめ波"],
  ["ZaWarudo", "ZaWarudo", "ザ・ワールド"],
  ["YareYare", "YareYare", "やれやれ"],
  ["Nani", "Nani", "なにぃ"],
  ["Yatta", "Yatta", "やった"],
];

/** Titles that also stand alone in Japanese, after an adjective: not さん, ちゃん, くん or 殿. */
const STANDALONE_TITLES = TITLES.filter(
  ([, , , , ja]) => !["さん", "ちゃん", "くん", "殿"].includes(ja),
);

// Guest numbers run through the shapes in order: adjective and noun, hybrids, title and
// noun, the legendary names, then title and adjective (added last, so older numbers keep
// their names).
const ADJECTIVE_NOUNS = ADJECTIVES.length * NOUNS.length;
const HYBRIDS = NOUNS.length * NOUNS.length;
const TITLED = TITLES.length * NOUNS.length;
const LEGENDARY_START = ADJECTIVE_NOUNS + HYBRIDS + TITLED;
const TITLED_ADJECTIVES = STANDALONE_TITLES.length * ADJECTIVES.length;
export const GUEST_NAME_COUNT =
  LEGENDARY_START + LEGENDARY.length + TITLED_ADJECTIVES;

/**
 * A guest's name from their guest number, written as one word.
 * Adjective and noun: English and Japanese put the adjective first ("WonderfulCat",
 * "すてきなネコ"); Portuguese puts the noun first and agrees in gender ("GatoMaravilhoso",
 * "RaposaMaravilhosa").
 * Hybrid: two nouns in the same order everywhere ("PotatoNinja", "BatataNinja").
 * Title and noun: the title first, last in Japanese ("QueenFox", "RainhaRaposa", "キツネ女王").
 * Title and adjective: the same order, the adjective first in Japanese ("CaptainBrave",
 * "CapitãoCorajoso", "勇敢な船長"). With no noun to give a gender, half the pairs are
 * masculine and half feminine; both would read the same in English.
 */
export function guestName(guestNumber: number, lang: Lang): string {
  let i = Math.abs(Math.trunc(guestNumber) || 0) % GUEST_NAME_COUNT;
  if (i < ADJECTIVE_NOUNS) {
    const [en, ptM, ptF, ja] = ADJECTIVES[i % ADJECTIVES.length];
    const [nounEn, nounPt, gender, nounJa] =
      NOUNS[Math.floor(i / ADJECTIVES.length)];
    if (lang === "pt") return nounPt + (gender === "f" ? ptF : ptM);
    if (lang === "ja") return ja + nounJa;
    return en + nounEn;
  }
  i -= ADJECTIVE_NOUNS;
  if (i < HYBRIDS) {
    const word = (noun: Noun) =>
      lang === "pt" ? noun[1] : lang === "ja" ? noun[3] : noun[0];
    return (
      word(NOUNS[Math.floor(i / NOUNS.length)]) + word(NOUNS[i % NOUNS.length])
    );
  }
  i -= HYBRIDS;
  if (i < TITLED) {
    const [enM, enF, ptM, ptF, jaM, jaF] = TITLES[i % TITLES.length];
    const [en, pt, gender, ja] = NOUNS[Math.floor(i / TITLES.length)];
    const f = gender === "f";
    if (lang === "pt") return (f ? ptF : ptM) + pt;
    if (lang === "ja") return ja + (f ? jaF : jaM);
    return (f ? enF : enM) + en;
  }
  i -= TITLED;
  if (i < LEGENDARY.length) {
    const [en, pt, ja] = LEGENDARY[i];
    return lang === "pt" ? pt : lang === "ja" ? ja : en;
  }
  i -= LEGENDARY.length;
  const t = i % STANDALONE_TITLES.length;
  const a = Math.floor(i / STANDALONE_TITLES.length);
  const [enM, enF, ptM, ptF, jaM, jaF] = STANDALONE_TITLES[t];
  const [en, adjPtM, adjPtF, ja] = ADJECTIVES[a];
  const f = (t + a) % 2 === 1;
  if (lang === "pt") return f ? ptF + adjPtF : ptM + adjPtM;
  if (lang === "ja") return ja + (f ? jaF : jaM);
  return (f ? enF : enM) + en;
}

/** Longest name allowed per language (in characters), so names fit the player strip. */
export const GUEST_NAME_MAX: Record<Lang, number> = { en: 18, pt: 18, ja: 10 };

const fits = (n: number) =>
  LANGS.every((l) => [...guestName(n, l)].length <= GUEST_NAME_MAX[l]);

/** How often a new guest gets a legendary name. */
export const LEGENDARY_CHANCE = 1 / 100;

/** A random guest number whose name is short enough in every language; now and then a legendary one. */
export function randomGuestNumber(random: () => number = Math.random): number {
  if (random() < LEGENDARY_CHANCE)
    return LEGENDARY_START + Math.floor(random() * LEGENDARY.length);
  let n = 0;
  for (let tries = 0; tries < 100; tries++) {
    // every number but the legendary ones
    n = Math.floor(random() * (GUEST_NAME_COUNT - LEGENDARY.length));
    if (n >= LEGENDARY_START) n += LEGENDARY.length;
    if (fits(n)) return n;
  }
  return n;
}
