import { LANGS, type Lang } from "./types";

// Guest names come in four shapes:
// - an adjective and a noun: "WonderfulCat", "GatoMaravilhoso", "GatoMaravilloso",
//   "すてきなネコ";
// - two nouns, a hybrid: "PotatoNinja", "BatataNinja", "PapaNinja", "ジャガイモ忍者";
// - a title and a noun, the title following the noun's Portuguese gender in every
//   language: "QueenFox", "RainhaRaposa", "ReinaZorro", "キツネ女王"; a title with a
//   different word for each gender in every language also comes in the other one:
//   "QueenCat", "RainhaGato";
// - now and then, a legendary meme name: "TGIF", "Sextou", "YaEsViernes", "花金".
// Each row holds the same idea in every language, so the same guest number gives the
// same name, translated, to everyone in a room (whatever language each one plays in).
// Words are friendly or playfully silly, never insults; nouns avoid ones that are slurs
// or double meanings in Portuguese (vaca, anta, galinha, macaco...) or Spanish (zorra,
// mariquita...). Spanish is neutral Latin American.

/** [English, Portuguese masculine, Portuguese feminine, Japanese (attributive form), Spanish masculine, Spanish feminine]. */
type Adjective = readonly [
  en: string,
  ptM: string,
  ptF: string,
  ja: string,
  esM: string,
  esF: string,
];
/** [English, Portuguese, its grammatical gender, Japanese, Spanish, its grammatical gender]. */
type Noun = readonly [
  en: string,
  pt: string,
  gender: "m" | "f",
  ja: string,
  es: string,
  esGender: "m" | "f",
];
/** Masculine and feminine: [English, English, Portuguese, Portuguese, Japanese suffix, Japanese suffix, Spanish, Spanish]. */
type Title = readonly [
  enM: string,
  enF: string,
  ptM: string,
  ptF: string,
  jaM: string,
  jaF: string,
  esM: string,
  esF: string,
];
/** [English, Portuguese, Japanese, Spanish]: the meme, or its local twin where one exists. */
type Legendary = readonly [en: string, pt: string, ja: string, es: string];

// One row per line, a table to read across: kept out of the formatter.
// biome-ignore format: word table
export const ADJECTIVES: readonly Adjective[] = [
  ["Brave", "Corajoso", "Corajosa", "勇敢な", "Valiente", "Valiente"],
  ["Sleepy", "Sonolento", "Sonolenta", "眠たい", "Dormilón", "Dormilona"],
  ["Hungry", "Faminto", "Faminta", "はらぺこ", "Hambriento", "Hambrienta"],
  ["Happy", "Feliz", "Feliz", "ごきげんな", "Feliz", "Feliz"],
  ["Sneaky", "Sorrateiro", "Sorrateira", "忍び足の", "Sigiloso", "Sigilosa"],
  ["Clever", "Esperto", "Esperta", "賢い", "Astuto", "Astuta"],
  ["Curious", "Curioso", "Curiosa", "知りたがりの", "Curioso", "Curiosa"],
  ["Fluffy", "Felpudo", "Felpuda", "ふわふわ", "Esponjoso", "Esponjosa"],
  ["Fuzzy", "Peludo", "Peluda", "もふもふ", "Peludo", "Peluda"],
  ["Cute", "Fofo", "Fofa", "かわいい", "Tierno", "Tierna"],
  ["Tiny", "Pequenino", "Pequenina", "ちいさな", "Chiquito", "Chiquita"],
  ["Giant", "Gigante", "Gigante", "でっかい", "Gigante", "Gigante"],
  ["Golden", "Dourado", "Dourada", "金色の", "Dorado", "Dorada"],
  ["Silver", "Prateado", "Prateada", "銀色の", "Plateado", "Plateada"],
  ["Purple", "Roxo", "Roxa", "むらさきの", "Morado", "Morada"],
  ["Blue", "Azul", "Azul", "青い", "Azul", "Azul"],
  ["Red", "Vermelho", "Vermelha", "赤い", "Rojo", "Roja"],
  ["Green", "Verde", "Verde", "緑の", "Verde", "Verde"],
  ["Yellow", "Amarelo", "Amarela", "黄色い", "Amarillo", "Amarilla"],
  ["Pink", "Rosa", "Rosa", "ピンクの", "Rosa", "Rosa"],
  ["Orange", "Laranja", "Laranja", "オレンジの", "Naranja", "Naranja"],
  ["Turquoise", "Turquesa", "Turquesa", "ターコイズの", "Turquesa", "Turquesa"],
  ["Rainbow", "ArcoÍris", "ArcoÍris", "にじいろの", "Arcoíris", "Arcoíris"],
  ["Cosmic", "Cósmico", "Cósmica", "宇宙の", "Cósmico", "Cósmica"],
  ["Galactic", "Galáctico", "Galáctica", "銀河の", "Galáctico", "Galáctica"],
  ["Stellar", "Estelar", "Estelar", "星の", "Estelar", "Estelar"],
  ["Lunar", "Lunar", "Lunar", "月の", "Lunar", "Lunar"],
  ["Solar", "Solar", "Solar", "太陽の", "Solar", "Solar"],
  ["Quantum", "Quântico", "Quântica", "量子の", "Cuántico", "Cuántica"],
  ["Electric", "Elétrico", "Elétrica", "ビリビリ", "Eléctrico", "Eléctrica"],
  ["Digital", "Digital", "Digital", "デジタルな", "Digital", "Digital"],
  ["Pixel", "Pixelado", "Pixelada", "ドット絵の", "Pixelado", "Pixelada"],
  ["Neon", "Neon", "Neon", "ネオンの", "Neón", "Neón"],
  ["Turbo", "Turbo", "Turbo", "ターボ", "Turbo", "Turbo"],
  ["Mysterious", "Misterioso", "Misteriosa", "なぞの", "Misterioso", "Misteriosa"],
  ["Secret", "Secreto", "Secreta", "ひみつの", "Secreto", "Secreta"],
  ["Hidden", "Escondido", "Escondida", "隠れた", "Escondido", "Escondida"],
  ["Invisible", "Invisível", "Invisível", "透明な", "Invisible", "Invisible"],
  ["Undercover", "Disfarçado", "Disfarçada", "変装した", "Disfrazado", "Disfrazada"],
  ["Lazy", "Preguiçoso", "Preguiçosa", "ぐうたら", "Flojo", "Floja"],
  ["Grumpy", "Rabugento", "Rabugenta", "不機嫌な", "Gruñón", "Gruñona"],
  ["Shy", "Tímido", "Tímida", "照れ屋の", "Tímido", "Tímida"],
  ["Bold", "Ousado", "Ousada", "大胆な", "Audaz", "Audaz"],
  ["Quiet", "Quieto", "Quieta", "静かな", "Callado", "Callada"],
  ["Noisy", "Barulhento", "Barulhenta", "にぎやかな", "Ruidoso", "Ruidosa"],
  ["Lucky", "Sortudo", "Sortuda", "ラッキーな", "Suertudo", "Suertuda"],
  ["Speedy", "Veloz", "Veloz", "俊足の", "Veloz", "Veloz"],
  ["Quick", "Rápido", "Rápida", "すばやい", "Rápido", "Rápida"],
  ["Wild", "Selvagem", "Selvagem", "ワイルドな", "Salvaje", "Salvaje"],
  ["Gentle", "Gentil", "Gentil", "おだやかな", "Gentil", "Gentil"],
  ["Jolly", "Alegre", "Alegre", "陽気な", "Alegre", "Alegre"],
  ["Calm", "Tranquilo", "Tranquila", "のんびり", "Tranquilo", "Tranquila"],
  ["Dizzy", "Zonzo", "Zonza", "ふらふら", "Mareado", "Mareada"],
  ["Fancy", "Chique", "Chique", "おしゃれな", "Elegante", "Elegante"],
  ["Cool", "Descolado", "Descolada", "クールな", "Genial", "Genial"],
  ["Fierce", "Feroz", "Feroz", "どう猛な", "Feroz", "Feroz"],
  ["Friendly", "Amigável", "Amigável", "人なつっこい", "Amigable", "Amigable"],
  ["Funny", "Engraçado", "Engraçada", "おもしろい", "Chistoso", "Chistosa"],
  ["Charming", "Charmoso", "Charmosa", "魅力的な", "Encantador", "Encantadora"],
  ["Glowing", "Brilhante", "Brilhante", "光る", "Luminoso", "Luminosa"],
  ["Graceful", "Elegante", "Elegante", "優雅な", "Garboso", "Garbosa"],
  ["Humble", "Humilde", "Humilde", "謙虚な", "Humilde", "Humilde"],
  ["Jumpy", "Saltitante", "Saltitante", "ぴょんぴょん", "Saltarín", "Saltarina"],
  ["Kind", "Bondoso", "Bondosa", "優しい", "Bondadoso", "Bondadosa"],
  ["Generous", "Generoso", "Generosa", "気前のいい", "Generoso", "Generosa"],
  ["Legendary", "Lendário", "Lendária", "伝説の", "Legendario", "Legendaria"],
  ["Lively", "Animado", "Animada", "元気な", "Animado", "Animada"],
  ["Loyal", "Leal", "Leal", "忠実な", "Leal", "Leal"],
  ["Magic", "Mágico", "Mágica", "魔法の", "Mágico", "Mágica"],
  ["Majestic", "Majestoso", "Majestosa", "堂々とした", "Majestuoso", "Majestuosa"],
  ["Mighty", "Poderoso", "Poderosa", "最強の", "Poderoso", "Poderosa"],
  ["Nimble", "Ágil", "Ágil", "身軽な", "Ágil", "Ágil"],
  ["Noble", "Nobre", "Nobre", "高貴な", "Noble", "Noble"],
  ["Peculiar", "Peculiar", "Peculiar", "風変わりな", "Peculiar", "Peculiar"],
  ["Playful", "Brincalhão", "Brincalhona", "遊び好きの", "Juguetón", "Juguetona"],
  ["Polite", "Educado", "Educada", "礼儀正しい", "Educado", "Educada"],
  ["Proud", "Orgulhoso", "Orgulhosa", "誇り高い", "Orgulloso", "Orgullosa"],
  ["Radiant", "Radiante", "Radiante", "まぶしい", "Radiante", "Radiante"],
  ["Serious", "Sério", "Séria", "まじめな", "Serio", "Seria"],
  ["Shiny", "Reluzente", "Reluzente", "ピカピカの", "Brilloso", "Brillosa"],
  ["Silent", "Silencioso", "Silenciosa", "無口な", "Silencioso", "Silenciosa"],
  ["Silly", "Bobo", "Boba", "とぼけた", "Bobo", "Boba"],
  ["Smart", "Inteligente", "Inteligente", "頭のいい", "Inteligente", "Inteligente"],
  ["Smooth", "Suave", "Suave", "なめらかな", "Suave", "Suave"],
  ["Sparkly", "Cintilante", "Cintilante", "キラキラ", "Reluciente", "Reluciente"],
  ["Spotted", "Pintado", "Pintada", "水玉の", "Moteado", "Moteada"],
  ["Striped", "Listrado", "Listrada", "しましまの", "Rayado", "Rayada"],
  ["Stormy", "Tempestuoso", "Tempestuosa", "嵐の", "Tormentoso", "Tormentosa"],
  ["Tidy", "Arrumado", "Arrumada", "きれい好きの", "Ordenado", "Ordenada"],
  ["Tough", "Durão", "Durona", "タフな", "Rudo", "Ruda"],
  ["Cheeky", "Travesso", "Travessa", "いたずらな", "Travieso", "Traviesa"],
  ["Wandering", "Errante", "Errante", "さすらいの", "Errante", "Errante"],
  ["Wise", "Sábio", "Sábia", "物知りの", "Sabio", "Sabia"],
  ["Ancient", "Antigo", "Antiga", "古代の", "Antiguo", "Antigua"],
  ["Awesome", "Incrível", "Incrível", "すごい", "Increíble", "Increíble"],
  ["Busy", "Ocupado", "Ocupada", "いそがしい", "Ocupado", "Ocupada"],
  ["Hardworking", "Trabalhador", "Trabalhadora", "働き者の", "Trabajador", "Trabajadora"],
  ["Chilly", "Friorento", "Friorenta", "寒がりの", "Friolento", "Friolenta"],
  ["Clumsy", "Desastrado", "Desastrada", "ドジな", "Torpe", "Torpe"],
  ["Cozy", "Aconchegante", "Aconchegante", "ぬくぬく", "Acogedor", "Acogedora"],
  ["Crispy", "Crocante", "Crocante", "サクサクの", "Crujiente", "Crujiente"],
  ["Dreamy", "Sonhador", "Sonhadora", "夢見る", "Soñador", "Soñadora"],
  ["Epic", "Épico", "Épica", "壮大な", "Épico", "Épica"],
  ["Icy", "Gelado", "Gelada", "こおりの", "Helado", "Helada"],
  ["Glorious", "Glorioso", "Gloriosa", "栄光の", "Glorioso", "Gloriosa"],
  ["Heroic", "Heroico", "Heroica", "英雄の", "Heroico", "Heroica"],
  ["Honest", "Honesto", "Honesta", "正直な", "Honesto", "Honesta"],
  ["Wonderful", "Maravilhoso", "Maravilhosa", "すてきな", "Maravilloso", "Maravillosa"],
  ["Minty", "Mentolado", "Mentolada", "ミントの", "Mentolado", "Mentolada"],
  ["Misty", "Nebuloso", "Nebulosa", "霧の", "Brumoso", "Brumosa"],
  ["Nervous", "Nervoso", "Nervosa", "そわそわ", "Nervioso", "Nerviosa"],
  ["Nocturnal", "Noturno", "Noturna", "夜ふかしの", "Nocturno", "Nocturna"],
  ["Optimistic", "Otimista", "Otimista", "前向きな", "Optimista", "Optimista"],
  ["Patient", "Paciente", "Paciente", "辛抱強い", "Paciente", "Paciente"],
  ["Rebel", "Rebelde", "Rebelde", "反抗期の", "Rebelde", "Rebelde"],
  ["Spooky", "Sombrio", "Sombria", "不気味な", "Tenebroso", "Tenebrosa"],
  ["Sticky", "Grudento", "Grudenta", "ねばねば", "Pegajoso", "Pegajosa"],
  ["Stubborn", "Teimoso", "Teimosa", "がんこな", "Terco", "Terca"],
  ["Sturdy", "Robusto", "Robusta", "頑丈な", "Robusto", "Robusta"],
  ["Thoughtful", "Pensativo", "Pensativa", "考え中の", "Pensativo", "Pensativa"],
  ["Tropical", "Tropical", "Tropical", "南国の", "Tropical", "Tropical"],
  ["Vibrant", "Vibrante", "Vibrante", "鮮やかな", "Vibrante", "Vibrante"],
  ["Warm", "Quentinho", "Quentinha", "ほかほか", "Tibio", "Tibia"],
  ["Dancing", "Dançarino", "Dançarina", "踊る", "Bailarín", "Bailarina"],
  ["Singing", "Cantor", "Cantora", "歌う", "Cantarín", "Cantarina"],
  ["Flying", "Voador", "Voadora", "空飛ぶ", "Volador", "Voladora"],
  ["Sporty", "Esportista", "Esportista", "スポーティな", "Deportista", "Deportista"],
  ["Artistic", "Artista", "Artista", "芸術家の", "Artista", "Artista"],
  ["Musical", "Musical", "Musical", "音楽好きの", "Musical", "Musical"],
  ["Retro", "Retrô", "Retrô", "レトロな", "Retro", "Retro"],
  ["Classic", "Clássico", "Clássica", "クラシックな", "Clásico", "Clásica"],
  ["Modern", "Moderno", "Moderna", "モダンな", "Moderno", "Moderna"],
  ["Famous", "Famoso", "Famosa", "有名な", "Famoso", "Famosa"],
  ["Lost", "Perdido", "Perdida", "迷子の", "Perdido", "Perdida"],
  ["Smiley", "Risonho", "Risonha", "にこにこ", "Sonriente", "Sonriente"],
  ["Chatty", "Tagarela", "Tagarela", "おしゃべりな", "Parlanchín", "Parlanchina"],
  ["Hasty", "Apressado", "Apressada", "せっかちな", "Apurado", "Apurada"],
  ["Gourmet", "Gourmet", "Gourmet", "グルメな", "Gourmet", "Gourmet"],
  ["Dramatic", "Dramático", "Dramática", "おおげさな", "Dramático", "Dramática"],
  ["Fabulous", "Fabuloso", "Fabulosa", "ゴージャスな", "Fabuloso", "Fabulosa"],
  ["Free", "Livre", "Livre", "自由な", "Libre", "Libre"],
  ["Sour", "Azedo", "Azeda", "すっぱい", "Agrio", "Agria"],
  ["Salty", "Salgado", "Salgada", "しょっぱい", "Salado", "Salada"],
  ["Sweet", "Doce", "Doce", "あまい", "Dulce", "Dulce"],
  ["Fiery", "Flamejante", "Flamejante", "炎の", "Llameante", "Llameante"],
  ["Arctic", "Ártico", "Ártica", "北極の", "Ártico", "Ártica"],
  ["Urban", "Urbano", "Urbana", "都会の", "Urbano", "Urbana"],
  ["Confident", "Confiante", "Confiante", "自信満々の", "Seguro", "Segura"],
  ["Relaxed", "Relaxado", "Relaxada", "リラックスした", "Relajado", "Relajada"],
  ["Tired", "Cansado", "Cansada", "お疲れの", "Cansado", "Cansada"],
  ["Bored", "Entediado", "Entediada", "退屈な", "Aburrido", "Aburrida"],
  ["Excited", "Empolgado", "Empolgada", "わくわく", "Emocionado", "Emocionada"],
  ["Surprised", "Surpreso", "Surpresa", "びっくり", "Asombrado", "Asombrada"],
  ["Confused", "Confuso", "Confusa", "混乱した", "Confuso", "Confusa"],
  ["Snoring", "Roncador", "Roncadora", "いびきの", "Roncador", "Roncadora"],
  ["Sleepwalking", "Sonâmbulo", "Sonâmbula", "寝ぼけた", "Sonámbulo", "Sonámbula"],
  ["Barefoot", "Descalço", "Descalça", "はだしの", "Descalzo", "Descalza"],
  ["Infinite", "Infinito", "Infinita", "無限の", "Infinito", "Infinita"],
  ["Lone", "Solitário", "Solitária", "一匹狼の", "Solitario", "Solitaria"],
  ["Sunny", "Ensolarado", "Ensolarada", "晴れやかな", "Soleado", "Soleada"],
  ["Snowy", "Nevado", "Nevada", "雪の", "Nevado", "Nevada"],
  ["Rainy", "Chuvoso", "Chuvosa", "雨の", "Lluvioso", "Lluviosa"],
  ["Daring", "Destemido", "Destemida", "恐れ知らずの", "Intrépido", "Intrépida"],
  ["Valiant", "Valente", "Valente", "勇ましい", "Valeroso", "Valerosa"],
  ["Witty", "Espirituoso", "Espirituosa", "機転の利く", "Ingenioso", "Ingeniosa"],
  ["Cheerful", "Contente", "Contente", "朗らかな", "Contento", "Contenta"],
  ["Bubbly", "Borbulhante", "Borbulhante", "あわあわ", "Burbujeante", "Burbujeante"],
  ["Juicy", "Suculento", "Suculenta", "ジューシーな", "Jugoso", "Jugosa"],
  ["Tasty", "Saboroso", "Saborosa", "おいしい", "Sabroso", "Sabrosa"],
  ["Toasty", "Tostado", "Tostada", "こんがり", "Tostado", "Tostada"],
  ["Frosty", "Congelado", "Congelada", "凍った", "Congelado", "Congelada"],
  ["Muddy", "Enlameado", "Enlameada", "どろんこ", "Enlodado", "Enlodada"],
  ["Sassy", "Atrevido", "Atrevida", "生意気な", "Atrevido", "Atrevida"],
  ["Royal", "Real", "Real", "王家の", "Real", "Real"],
  ["Cyber", "Cibernético", "Cibernética", "サイバーな", "Cibernético", "Cibernética"],
  ["Supersonic", "Supersônico", "Supersônica", "超音速の", "Supersónico", "Supersónica"],
  ["Masked", "Mascarado", "Mascarada", "覆面の", "Enmascarado", "Enmascarada"],
  ["Squishy", "Molinho", "Molinha", "もちもち", "Blandito", "Blandita"],
  ["Round", "Redondo", "Redonda", "まんまるの", "Redondo", "Redonda"],
  ["Glittery", "Purpurinado", "Purpurinada", "ラメ入りの", "Escarchado", "Escarchada"],
  ["Pastel", "Pastel", "Pastel", "パステルの", "Pastel", "Pastel"],
  ["Silky", "Sedoso", "Sedosa", "サラサラ", "Sedoso", "Sedosa"],
  ["Brilliant", "Genial", "Genial", "天才的な", "Brillante", "Brillante"],
  ["Celestial", "Celestial", "Celestial", "天空の", "Celestial", "Celestial"],
  ["Mythic", "Mítico", "Mítica", "神話の", "Mítico", "Mítica"],
  ["Enchanted", "Encantado", "Encantada", "魅惑の", "Encantado", "Encantada"],
  ["Sneezy", "Espirrento", "Espirrenta", "くしゃみ中の", "Resfriado", "Resfriada"],
  ["Hopeful", "Esperançoso", "Esperançosa", "希望の", "Esperanzado", "Esperanzada"],
  ["Nerdy", "Nerd", "Nerd", "オタクな", "Nerd", "Nerd"],
  ["Punk", "Punk", "Punk", "パンクな", "Punk", "Punk"],
  ["Groovy", "Gingado", "Gingada", "グルーヴィーな", "Rumbero", "Rumbera"],
  ["Funky", "Funkeiro", "Funkeira", "ファンキーな", "Funky", "Funky"],
  ["Victorious", "Vitorioso", "Vitoriosa", "勝利の", "Victorioso", "Victoriosa"],
  ["Undefeated", "Invicto", "Invicta", "無敗の", "Invicto", "Invicta"],
  ["Homemade", "Caseiro", "Caseira", "手作りの", "Casero", "Casera"],
  ["Creamy", "Cremoso", "Cremosa", "クリーミーな", "Cremoso", "Cremosa"],
  ["Fizzy", "Efervescente", "Efervescente", "シュワシュワ", "Efervescente", "Efervescente"],
  ["Caramel", "Caramelado", "Caramelada", "キャラメルの", "Acaramelado", "Acaramelada"],
  ["Chocolate", "Achocolatado", "Achocolatada", "チョコの", "Achocolatado", "Achocolatada"],
  ["Buttery", "Amanteigado", "Amanteigada", "バターの", "Mantecoso", "Mantecosa"],
  ["Plaid", "Xadrez", "Xadrez", "チェックの", "Escocés", "Escocesa"],
  ["Origami", "Origami", "Origami", "折り紙の", "Origami", "Origami"],
  ["Martian", "Marciano", "Marciana", "火星の", "Marciano", "Marciana"],
  ["Volcanic", "Vulcânico", "Vulcânica", "火山の", "Volcánico", "Volcánica"],
  ["Oceanic", "Oceânico", "Oceânica", "大海の", "Oceánico", "Oceánica"],
  ["Festive", "Festivo", "Festiva", "お祭りの", "Festivo", "Festiva"],
  ["Supreme", "Supremo", "Suprema", "至高の", "Supremo", "Suprema"],
  ["Ultimate", "Definitivo", "Definitiva", "究極の", "Definitivo", "Definitiva"],
  ["Whistling", "Assobiador", "Assobiadora", "口笛好きの", "Silbador", "Silbadora"],
  ["Adventurous", "Aventureiro", "Aventureira", "冒険好きの", "Aventurero", "Aventurera"],
  ["Creative", "Criativo", "Criativa", "創造的な", "Creativo", "Creativa"],
  ["Stylish", "Estiloso", "Estilosa", "イケてる", "Estiloso", "Estilosa"],
  ["Wacky", "Maluco", "Maluca", "ハチャメチャな", "Chiflado", "Chiflada"],
  ["Metallic", "Metálico", "Metálica", "メタリックな", "Metálico", "Metálica"],
  ["Bronze", "Bronzeado", "Bronzeada", "銅色の", "Bronceado", "Bronceada"],
  ["Crimson", "Carmesim", "Carmesim", "深紅の", "Carmesí", "Carmesí"],
  ["Emerald", "Esmeralda", "Esmeralda", "エメラルドの", "Esmeralda", "Esmeralda"],
  ["Gray", "Cinza", "Cinza", "灰色の", "Gris", "Gris"],
  ["Platinum", "Platinado", "Platinada", "プラチナの", "Platinado", "Platinada"],
  ["Zippy", "Ligeiro", "Ligeira", "すばしこい", "Raudo", "Rauda"],
  ["Bouncy", "Elástico", "Elástica", "ぷるぷる", "Elástico", "Elástica"],
  ["Chill", "Sossegado", "Sossegada", "まったり", "Sereno", "Serena"],
  ["Starry", "Estrelado", "Estrelada", "星空の", "Estrellado", "Estrellada"],
  ["Moonlit", "Enluarado", "Enluarada", "月夜の", "Lunático", "Lunática"],
  ["Dusty", "Empoeirado", "Empoeirada", "ほこりまみれの", "Polvoriento", "Polvorienta"],
  ["Soggy", "Encharcado", "Encharcada", "びしょぬれの", "Empapado", "Empapada"],
  ["Leafy", "Frondoso", "Frondosa", "葉っぱの", "Frondoso", "Frondosa"],
  ["Spicy", "Picante", "Picante", "ピリ辛の", "Picante", "Picante"],
  ["Fruity", "Frutado", "Frutada", "フルーティーな", "Afrutado", "Afrutada"],
  ["Cheesy", "Queijudo", "Queijuda", "チーズ味の", "Quesudo", "Quesuda"],
  ["Dandy", "Janota", "Janota", "ダンディな", "Presumido", "Presumida"],
  ["Frisky", "Serelepe", "Serelepe", "やんちゃな", "Inquieto", "Inquieta"],
  ["Merry", "Festeiro", "Festeira", "浮かれた", "Fiestero", "Fiestera"],
  ["Velvety", "Aveludado", "Aveludada", "ビロードの", "Afelpado", "Afelpada"],
  ["Atomic", "Atômico", "Atômica", "原子の", "Atómico", "Atómica"],
  ["Hyper", "Hiperativo", "Hiperativa", "ハイパーな", "Hiperactivo", "Hiperactiva"],
  ["Imperial", "Imperial", "Imperial", "帝国の", "Imperial", "Imperial"],
  ["Alpine", "Alpino", "Alpina", "高山の", "Alpino", "Alpina"],
  ["Peaceful", "Pacífico", "Pacífica", "平和な", "Pacífico", "Pacífica"],
  ["Feathery", "Emplumado", "Emplumada", "羽毛の", "Emplumado", "Emplumada"],
  ["Robotic", "Robótico", "Robótica", "ロボの", "Robótico", "Robótica"],
  ["Mini", "Mini", "Mini", "ミニ", "Mini", "Mini"],
  ["Jumbo", "Jumbo", "Jumbo", "ジャンボ", "Jumbo", "Jumbo"],
  ["Yawning", "Bocejante", "Bocejante", "あくび中の", "Bostezón", "Bostezona"],
  ["Thrifty", "Econômico", "Econômica", "節約家の", "Ahorrador", "Ahorradora"],
  ["Punctual", "Pontual", "Pontual", "時間厳守の", "Puntual", "Puntual"],
  ["Sincere", "Sincero", "Sincera", "素直な", "Sincero", "Sincera"],
  ["Woolly", "Lanudo", "Lanuda", "もこもこ", "Lanudo", "Lanuda"],
  ["Glossy", "Lustroso", "Lustrosa", "つやつや", "Lustroso", "Lustrosa"],
];

// biome-ignore format: word table
export const NOUNS: readonly Noun[] = [
  ["Cat", "Gato", "m", "ネコ", "Gato", "m"],
  ["Dog", "Cachorro", "m", "イヌ", "Perro", "m"],
  ["Fox", "Raposa", "f", "キツネ", "Zorro", "m"],
  ["Panda", "Panda", "m", "パンダ", "Panda", "m"],
  ["Penguin", "Pinguim", "m", "ペンギン", "Pingüino", "m"],
  ["Owl", "Coruja", "f", "フクロウ", "Búho", "m"],
  ["Rabbit", "Coelho", "m", "ウサギ", "Conejo", "m"],
  ["Bear", "Urso", "m", "クマ", "Oso", "m"],
  ["Tiger", "Tigre", "m", "トラ", "Tigre", "m"],
  ["Lion", "Leão", "m", "ライオン", "León", "m"],
  ["Wolf", "Lobo", "m", "オオカミ", "Lobo", "m"],
  ["Frog", "Sapo", "m", "カエル", "Rana", "f"],
  ["Turtle", "Tartaruga", "f", "カメ", "Tortuga", "f"],
  ["Duck", "Pato", "m", "アヒル", "Pato", "m"],
  ["Goose", "Ganso", "m", "ガチョウ", "Ganso", "m"],
  ["Chick", "Pintinho", "m", "ヒヨコ", "Pollito", "m"],
  ["Piglet", "Porquinho", "m", "コブタ", "Cerdito", "m"],
  ["Pony", "Pônei", "m", "ポニー", "Poni", "m"],
  ["Goat", "Cabra", "f", "ヤギ", "Cabra", "f"],
  ["Sheep", "Ovelha", "f", "ヒツジ", "Oveja", "f"],
  ["Llama", "Lhama", "f", "ラマ", "Llama", "f"],
  ["Alpaca", "Alpaca", "f", "アルパカ", "Alpaca", "f"],
  ["Camel", "Camelo", "m", "ラクダ", "Camello", "m"],
  ["Giraffe", "Girafa", "f", "キリン", "Jirafa", "f"],
  ["Elephant", "Elefante", "m", "ゾウ", "Elefante", "m"],
  ["Hippo", "Hipopótamo", "m", "カバ", "Hipopótamo", "m"],
  ["Rhino", "Rinoceronte", "m", "サイ", "Rinoceronte", "m"],
  ["Zebra", "Zebra", "f", "シマウマ", "Cebra", "f"],
  ["Kangaroo", "Canguru", "m", "カンガルー", "Canguro", "m"],
  ["Koala", "Coala", "m", "コアラ", "Koala", "m"],
  ["Sloth", "Preguiça", "f", "ナマケモノ", "Perezoso", "m"],
  ["Capybara", "Capivara", "f", "カピバラ", "Capibara", "m"],
  ["Armadillo", "Tatu", "m", "アルマジロ", "Armadillo", "m"],
  ["Anteater", "Tamanduá", "m", "アリクイ", "OsoHormiguero", "m"],
  ["Toucan", "Tucano", "m", "オオハシ", "Tucán", "m"],
  ["Parrot", "Papagaio", "m", "オウム", "Loro", "m"],
  ["Flamingo", "Flamingo", "m", "フラミンゴ", "Flamenco", "m"],
  ["Peacock", "Pavão", "m", "クジャク", "Pavorreal", "m"],
  ["Swan", "Cisne", "m", "ハクチョウ", "Cisne", "m"],
  ["Eagle", "Águia", "f", "ワシ", "Águila", "f"],
  ["Falcon", "Falcão", "m", "ハヤブサ", "Halcón", "m"],
  ["Crow", "Corvo", "m", "カラス", "Cuervo", "m"],
  ["Pigeon", "Pombo", "m", "ハト", "Paloma", "f"],
  ["Sparrow", "Pardal", "m", "スズメ", "Gorrión", "m"],
  ["Seagull", "Gaivota", "f", "カモメ", "Gaviota", "f"],
  ["Pelican", "Pelicano", "m", "ペリカン", "Pelícano", "m"],
  ["Ostrich", "Avestruz", "m", "ダチョウ", "Avestruz", "m"],
  ["Bat", "Morcego", "m", "コウモリ", "Murciélago", "m"],
  ["Hedgehog", "Ouriço", "m", "ハリネズミ", "Erizo", "m"],
  ["Hamster", "Hamster", "m", "ハムスター", "Hámster", "m"],
  ["Mouse", "Ratinho", "m", "ネズミ", "Ratón", "m"],
  ["Squirrel", "Esquilo", "m", "リス", "Ardilla", "f"],
  ["Beaver", "Castor", "m", "ビーバー", "Castor", "m"],
  ["Otter", "Lontra", "f", "カワウソ", "Nutria", "f"],
  ["Raccoon", "Guaxinim", "m", "アライグマ", "Mapache", "m"],
  ["Badger", "Texugo", "m", "アナグマ", "Tejón", "m"],
  ["Skunk", "Gambá", "m", "スカンク", "Zorrillo", "m"],
  ["Deer", "Cervo", "m", "シカ", "Ciervo", "m"],
  ["Moose", "Alce", "m", "ヘラジカ", "Alce", "m"],
  ["Reindeer", "Rena", "f", "トナカイ", "Reno", "m"],
  ["Seal", "Foca", "f", "アザラシ", "Foca", "f"],
  ["Walrus", "Morsa", "f", "セイウチ", "Morsa", "f"],
  ["Dolphin", "Golfinho", "m", "イルカ", "Delfín", "m"],
  ["Shark", "Tubarão", "m", "サメ", "Tiburón", "m"],
  ["Octopus", "Polvo", "m", "タコ", "Pulpo", "m"],
  ["Crab", "Caranguejo", "m", "カニ", "Cangrejo", "m"],
  ["Lobster", "Lagosta", "f", "ロブスター", "Langosta", "f"],
  ["Shrimp", "Camarão", "m", "エビ", "Camarón", "m"],
  ["Pufferfish", "Baiacu", "m", "フグ", "PezGlobo", "m"],
  ["Snail", "Caracol", "m", "カタツムリ", "Caracol", "m"],
  ["Bee", "Abelha", "f", "ミツバチ", "Abeja", "f"],
  ["Ant", "Formiga", "f", "アリ", "Hormiga", "f"],
  ["Ladybug", "Joaninha", "f", "テントウムシ", "Catarina", "f"],
  ["Butterfly", "Borboleta", "f", "チョウチョ", "Mariposa", "f"],
  ["Dragonfly", "Libélula", "f", "トンボ", "Libélula", "f"],
  ["Cricket", "Grilo", "m", "コオロギ", "Grillo", "m"],
  ["Beetle", "Besouro", "m", "カブトムシ", "Escarabajo", "m"],
  ["Spider", "Aranha", "f", "クモ", "Araña", "f"],
  ["Lizard", "Lagarto", "m", "トカゲ", "Lagarto", "m"],
  ["Gecko", "Lagartixa", "f", "ヤモリ", "Lagartija", "f"],
  ["Chameleon", "Camaleão", "m", "カメレオン", "Camaleón", "m"],
  ["Crocodile", "Crocodilo", "m", "ワニ", "Cocodrilo", "m"],
  ["Alligator", "Jacaré", "m", "アリゲーター", "Caimán", "m"],
  ["Dinosaur", "Dinossauro", "m", "恐竜", "Dinosaurio", "m"],
  ["Mammoth", "Mamute", "m", "マンモス", "Mamut", "m"],
  ["Dodo", "Dodô", "m", "ドードー", "Dodo", "m"],
  ["Platypus", "Ornitorrinco", "m", "カモノハシ", "Ornitorrinco", "m"],
  ["Axolotl", "Axolote", "m", "ウーパールーパー", "Ajolote", "m"],
  ["Narwhal", "Narval", "m", "イッカク", "Narval", "m"],
  ["Leopard", "Leopardo", "m", "ヒョウ", "Leopardo", "m"],
  ["Jaguar", "Onça", "f", "ジャガー", "Jaguar", "m"],
  ["Cheetah", "Guepardo", "m", "チーター", "Guepardo", "m"],
  ["Lynx", "Lince", "m", "オオヤマネコ", "Lince", "m"],
  ["Puma", "Puma", "m", "ピューマ", "Puma", "m"],
  ["Hyena", "Hiena", "f", "ハイエナ", "Hiena", "f"],
  ["Meerkat", "Suricato", "m", "ミーアキャット", "Suricata", "f"],
  ["Lemur", "Lêmure", "m", "キツネザル", "Lémur", "m"],
  ["Chinchilla", "Chinchila", "f", "チンチラ", "Chinchilla", "f"],
  ["Ferret", "Furão", "m", "フェレット", "Hurón", "m"],
  ["Yak", "Iaque", "m", "ヤク", "Yak", "m"],
  ["Bison", "Bisão", "m", "バイソン", "Bisonte", "m"],
  ["Quail", "Codorna", "f", "ウズラ", "Codorniz", "f"],
  ["Kiwi", "Kiwi", "m", "キーウィ", "Kiwi", "m"],
  ["Pangolin", "Pangolim", "m", "センザンコウ", "Pangolín", "m"],
  ["Wombat", "Vombate", "m", "ウォンバット", "Wómbat", "m"],
  ["Dragon", "Dragão", "m", "ドラゴン", "Dragón", "m"],
  ["Unicorn", "Unicórnio", "m", "ユニコーン", "Unicornio", "m"],
  ["Phoenix", "Fênix", "f", "フェニックス", "Fénix", "m"],
  ["Griffin", "Grifo", "m", "グリフォン", "Grifo", "m"],
  ["Yeti", "Iéti", "m", "イエティ", "Yeti", "m"],
  ["Ghost", "Fantasma", "m", "おばけ", "Fantasma", "m"],
  ["Robot", "Robô", "m", "ロボット", "Robot", "m"],
  ["Alien", "Alienígena", "m", "宇宙人", "Alienígena", "m"],
  ["Wizard", "Mago", "m", "魔法使い", "Mago", "m"],
  ["Ninja", "Ninja", "m", "忍者", "Ninja", "m"],
  ["Pirate", "Pirata", "m", "海賊", "Pirata", "m"],
  ["Knight", "Cavaleiro", "m", "騎士", "Caballero", "m"],
  ["Viking", "Viking", "m", "バイキング", "Vikingo", "m"],
  ["Astronaut", "Astronauta", "m", "宇宙飛行士", "Astronauta", "m"],
  ["Detective", "Detetive", "m", "探偵", "Detective", "m"],
  ["Chef", "Chef", "m", "シェフ", "Chef", "m"],
  ["Mermaid", "Sereia", "f", "人魚", "Sirena", "f"],
  ["Elf", "Elfo", "m", "エルフ", "Elfo", "m"],
  ["Gnome", "Gnomo", "m", "小人", "Gnomo", "m"],
  ["Vampire", "Vampiro", "m", "吸血鬼", "Vampiro", "m"],
  ["Zombie", "Zumbi", "m", "ゾンビ", "Zombi", "m"],
  ["Mummy", "Múmia", "f", "ミイラ", "Momia", "f"],
  ["Kraken", "Kraken", "m", "クラーケン", "Kraken", "m"],
  ["Sphinx", "Esfinge", "f", "スフィンクス", "Esfinge", "f"],
  ["Pegasus", "Pégaso", "m", "ペガサス", "Pegaso", "m"],
  ["Fairy", "Fada", "f", "妖精", "Hada", "f"],
  ["Goblin", "Duende", "m", "ゴブリン", "Duende", "m"],
  ["Potato", "Batata", "f", "ジャガイモ", "Papa", "f"],
  ["Pancake", "Panqueca", "f", "パンケーキ", "Panqueque", "m"],
  ["Cookie", "Biscoito", "m", "クッキー", "Galleta", "f"],
  ["Donut", "Rosquinha", "f", "ドーナツ", "Dona", "f"],
  ["Waffle", "Waffle", "m", "ワッフル", "Wafle", "m"],
  ["Muffin", "Bolinho", "m", "マフィン", "Muffin", "m"],
  ["Pudding", "Pudim", "m", "プリン", "Flan", "m"],
  ["Taco", "Taco", "m", "タコス", "Taco", "m"],
  ["Ramen", "Lámen", "m", "ラーメン", "Ramen", "m"],
  ["Pickle", "Picles", "m", "ピクルス", "Pepinillo", "m"],
  ["Avocado", "Abacate", "m", "アボカド", "Aguacate", "m"],
  ["Pineapple", "Abacaxi", "m", "パイナップル", "Piña", "f"],
  ["Mango", "Manga", "f", "マンゴー", "Mango", "m"],
  ["Lemon", "Limão", "m", "レモン", "Limón", "m"],
  ["Peach", "Pêssego", "m", "モモ", "Durazno", "m"],
  ["Tomato", "Tomate", "m", "トマト", "Tomate", "m"],
  ["Carrot", "Cenoura", "f", "ニンジン", "Zanahoria", "f"],
  ["Broccoli", "Brócolis", "m", "ブロッコリー", "Brócoli", "m"],
  ["Mushroom", "Cogumelo", "m", "キノコ", "Hongo", "m"],
  ["Pumpkin", "Abóbora", "f", "カボチャ", "Calabaza", "f"],
  ["Popcorn", "Pipoca", "f", "ポップコーン", "Palomita", "f"],
  ["Cupcake", "Cupcake", "m", "カップケーキ", "Cupcake", "m"],
  ["Croissant", "Croissant", "m", "クロワッサン", "Croissant", "m"],
  ["Sushi", "Sushi", "m", "寿司", "Sushi", "m"],
  ["Tofu", "Tofu", "m", "豆腐", "Tofu", "m"],
  ["Mochi", "Mochi", "m", "おもち", "Mochi", "m"],
  ["Nugget", "Nugget", "m", "ナゲット", "Nugget", "m"],
  ["Cactus", "Cacto", "m", "サボテン", "Cactus", "m"],
  ["Acorn", "Bolota", "f", "ドングリ", "Bellota", "f"],
  ["Cloud", "Nuvem", "f", "雲", "Nube", "f"],
  ["Comet", "Cometa", "m", "すい星", "Cometa", "m"],
  ["Meteor", "Meteoro", "m", "流れ星", "Meteoro", "m"],
  ["Rocket", "Foguete", "m", "ロケット", "Cohete", "m"],
  ["Volcano", "Vulcão", "m", "火山", "Volcán", "m"],
  ["Tornado", "Tornado", "m", "竜巻", "Tornado", "m"],
  ["Teapot", "Bule", "m", "ティーポット", "Tetera", "f"],
  ["Toaster", "Torradeira", "f", "トースター", "Tostadora", "f"],
  ["Sock", "Meia", "f", "くつした", "Calcetín", "m"],
  ["Pillow", "Travesseiro", "m", "まくら", "Almohada", "f"],
  ["Balloon", "Balão", "m", "風船", "Globo", "m"],
  ["Kite", "Pipa", "f", "カイト", "Papalote", "m"],
  ["Orca", "Orca", "f", "シャチ", "Orca", "f"],
  ["Manatee", "PeixeBoi", "m", "マナティー", "Manatí", "m"],
  ["Stingray", "Arraia", "f", "エイ", "Mantarraya", "f"],
  ["Jellyfish", "ÁguaViva", "f", "クラゲ", "Medusa", "f"],
  ["Seahorse", "CavaloMarinho", "m", "タツノオトシゴ", "Hipocampo", "m"],
  ["Clownfish", "PeixePalhaço", "m", "クマノミ", "PezPayaso", "m"],
  ["Hummingbird", "BeijaFlor", "m", "ハチドリ", "Colibrí", "m"],
  ["Macaw", "Arara", "f", "コンゴウインコ", "Guacamaya", "f"],
  ["Puffin", "PapagaioDoMar", "m", "ツノメドリ", "Frailecillo", "m"],
  ["Stork", "Cegonha", "f", "コウノトリ", "Cigüeña", "f"],
  ["Rooster", "Galo", "m", "オンドリ", "Gallo", "m"],
  ["Fennec", "Feneco", "m", "フェネック", "Fénec", "m"],
  ["Coati", "Quati", "m", "ハナグマ", "Coatí", "m"],
  ["Ocelot", "Jaguatirica", "f", "オセロット", "Ocelote", "m"],
  ["PolarBear", "UrsoPolar", "m", "シロクマ", "OsoPolar", "m"],
  ["Koi", "Carpa", "f", "コイ", "Carpa", "f"],
  ["Mongoose", "Mangusto", "m", "マングース", "Mangosta", "f"],
  ["Iguana", "Iguana", "f", "イグアナ", "Iguana", "f"],
  ["Tortoise", "Jabuti", "m", "リクガメ", "Galápago", "m"],
  ["Tadpole", "Girino", "m", "オタマジャクシ", "Renacuajo", "m"],
  ["Firefly", "VagaLume", "m", "ホタル", "Luciérnaga", "f"],
  ["Tanuki", "Tanuki", "m", "タヌキ", "Tanuki", "m"],
  ["Centaur", "Centauro", "m", "ケンタウロス", "Centauro", "m"],
  ["Cyclops", "Ciclope", "m", "サイクロプス", "Cíclope", "m"],
  ["Golem", "Golem", "m", "ゴーレム", "Gólem", "m"],
  ["Chupacabra", "Chupacabra", "m", "チュパカブラ", "Chupacabra", "m"],
  ["Bigfoot", "PéGrande", "m", "ビッグフット", "PieGrande", "m"],
  ["Werewolf", "Lobisomem", "m", "狼男", "HombreLobo", "m"],
  ["Cowboy", "Caubói", "m", "カウボーイ", "Vaquero", "m"],
  ["Samurai", "Samurai", "m", "侍", "Samurái", "m"],
  ["Spy", "Espião", "m", "スパイ", "Espía", "m"],
  ["Explorer", "Explorador", "m", "探検家", "Explorador", "m"],
  ["Scientist", "Cientista", "m", "科学者", "Científico", "m"],
  ["Firefighter", "Bombeiro", "m", "消防士", "Bombero", "m"],
  ["Sailor", "Marinheiro", "m", "船乗り", "Marinero", "m"],
  ["Surfer", "Surfista", "m", "サーファー", "Surfista", "m"],
  ["Poet", "Poeta", "m", "詩人", "Poeta", "m"],
  ["Gamer", "Gamer", "m", "ゲーマー", "Gamer", "m"],
  ["Strawberry", "Morango", "m", "イチゴ", "Fresa", "f"],
  ["Watermelon", "Melancia", "f", "スイカ", "Sandía", "f"],
  ["Cheese", "Queijo", "m", "チーズ", "Queso", "m"],
  ["Pizza", "Pizza", "f", "ピザ", "Pizza", "f"],
  ["Burger", "Hambúrguer", "m", "ハンバーガー", "Hamburguesa", "f"],
  ["Dumpling", "Guioza", "m", "ギョーザ", "Gyoza", "f"],
  ["RiceBall", "Oniguiri", "m", "おにぎり", "Onigiri", "m"],
  ["CheeseBread", "PãoDeQueijo", "m", "チーズパン", "PanDeQueso", "m"],
  ["Tapioca", "Tapioca", "f", "タピオカ", "Tapioca", "f"],
  ["Churro", "Churro", "m", "チュロス", "Churro", "m"],
  ["Marshmallow", "Marshmallow", "m", "マシュマロ", "Malvavisco", "m"],
  ["Takoyaki", "Takoyaki", "m", "たこ焼き", "Takoyaki", "m"],
  ["Sunflower", "Girassol", "m", "ヒマワリ", "Girasol", "m"],
  ["Bonsai", "Bonsai", "m", "盆栽", "Bonsái", "m"],
  ["Crystal", "Cristal", "m", "水晶", "Cristal", "m"],
  ["Snowman", "BonecoDeNeve", "m", "雪だるま", "MuñecoDeNieve", "m"],
  ["Planet", "Planeta", "m", "惑星", "Planeta", "m"],
  ["UFO", "Óvni", "m", "ユーフォー", "Ovni", "m"],
  ["Umbrella", "GuardaChuva", "m", "カサ", "Paraguas", "m"],
  ["Ukulele", "Ukulele", "m", "ウクレレ", "Ukelele", "m"],
  ["Slipper", "Chinelo", "m", "スリッパ", "Chancla", "f"],
  ["Submarine", "Submarino", "m", "潜水艦", "Submarino", "m"],
  ["Gnu", "Gnu", "m", "ヌー", "Ñu", "m"],
  ["Emu", "Emu", "m", "エミュー", "Emú", "m"],
  ["Newt", "Tritão", "m", "イモリ", "Tritón", "m"],
  ["Hare", "Lebre", "f", "ノウサギ", "Liebre", "f"],
  ["Lamb", "Cordeiro", "m", "コヒツジ", "Cordero", "m"],
  ["Kitten", "Gatinho", "m", "子ネコ", "Gatito", "m"],
  ["Eel", "Enguia", "f", "ウナギ", "Anguila", "f"],
  ["Tuna", "Atum", "m", "マグロ", "Atún", "m"],
  ["Salmon", "Salmão", "m", "サケ", "Salmón", "m"],
  ["Oni", "Oni", "m", "鬼", "Oni", "m"],
  ["Tengu", "Tengu", "m", "天狗", "Tengu", "m"],
  ["Minotaur", "Minotauro", "m", "ミノタウロス", "Minotauro", "m"],
  ["Baker", "Padeiro", "m", "パン屋", "Panadero", "m"],
  ["Painter", "Pintor", "m", "画家", "Pintor", "m"],
  ["Pilot", "Piloto", "m", "パイロット", "Piloto", "m"],
  ["Miner", "Mineiro", "m", "炭鉱夫", "Minero", "m"],
  ["Bagel", "Bagel", "m", "ベーグル", "Bagel", "m"],
  ["Brownie", "Brownie", "m", "ブラウニー", "Brownie", "m"],
  ["Noodle", "Macarrão", "m", "麺", "Fideo", "m"],
  ["Melon", "Melão", "m", "メロン", "Melón", "m"],
  ["Pear", "Pera", "f", "洋ナシ", "Pera", "f"],
  ["Jelly", "Gelatina", "f", "ゼリー", "Gelatina", "f"],
  ["Yoyo", "Ioiô", "m", "ヨーヨー", "Yoyó", "m"],
  ["Pebble", "Pedrinha", "f", "小石", "Piedrita", "f"],
  ["Moon", "Lua", "f", "月", "Luna", "f"],
  ["Drum", "Tambor", "m", "タイコ", "Tambor", "m"],
];

/** Japanese puts the title after the noun, as a suffix ("ネコ船長", "キツネ女王"). */
// biome-ignore format: word table
export const TITLES: readonly Title[] = [
  ["Captain", "Captain", "Capitão", "Capitã", "船長", "船長", "Capitán", "Capitana"],
  ["Doctor", "Doctor", "Doutor", "Doutora", "博士", "博士", "Doctor", "Doctora"],
  ["Professor", "Professor", "Professor", "Professora", "教授", "教授", "Profesor", "Profesora"],
  ["Agent", "Agent", "Agente", "Agente", "捜査官", "捜査官", "Agente", "Agente"],
  ["General", "General", "General", "General", "将軍", "将軍", "General", "General"],
  ["Admiral", "Admiral", "Almirante", "Almirante", "提督", "提督", "Almirante", "Almirante"],
  ["Sergeant", "Sergeant", "Sargento", "Sargento", "軍曹", "軍曹", "Sargento", "Sargento"],
  ["Colonel", "Colonel", "Coronel", "Coronel", "大佐", "大佐", "Coronel", "Coronel"],
  ["Major", "Major", "Major", "Major", "少佐", "少佐", "Mayor", "Mayor"],
  ["Lieutenant", "Lieutenant", "Tenente", "Tenente", "中尉", "中尉", "Teniente", "Teniente"],
  ["Commander", "Commander", "Comandante", "Comandante", "司令官", "司令官", "Comandante", "Comandante"],
  ["Mayor", "Mayor", "Prefeito", "Prefeita", "市長", "市長", "Alcalde", "Alcaldesa"],
  ["Governor", "Governor", "Governador", "Governadora", "知事", "知事", "Gobernador", "Gobernadora"],
  ["President", "President", "Presidente", "Presidente", "大統領", "大統領", "Presidente", "Presidenta"],
  ["Senator", "Senator", "Senador", "Senadora", "議員", "議員", "Senador", "Senadora"],
  ["Minister", "Minister", "Ministro", "Ministra", "大臣", "大臣", "Ministro", "Ministra"],
  ["Ambassador", "Ambassador", "Embaixador", "Embaixadora", "大使", "大使", "Embajador", "Embajadora"],
  ["Judge", "Judge", "Juiz", "Juíza", "裁判長", "裁判長", "Juez", "Jueza"],
  ["Sheriff", "Sheriff", "Xerife", "Xerife", "保安官", "保安官", "Sheriff", "Sheriff"],
  ["Officer", "Officer", "Guarda", "Guarda", "巡査", "巡査", "Oficial", "Oficial"],
  ["Inspector", "Inspector", "Inspetor", "Inspetora", "警部", "警部", "Inspector", "Inspectora"],
  ["King", "Queen", "Rei", "Rainha", "大王", "女王", "Rey", "Reina"],
  ["Prince", "Princess", "Príncipe", "Princesa", "王子", "姫", "Príncipe", "Princesa"],
  ["Emperor", "Empress", "Imperador", "Imperatriz", "皇帝", "女帝", "Emperador", "Emperatriz"],
  ["Duke", "Duchess", "Duque", "Duquesa", "公爵", "公爵夫人", "Duque", "Duquesa"],
  ["Marquis", "Marchioness", "Marquês", "Marquesa", "侯爵", "侯爵夫人", "Marqués", "Marquesa"],
  ["Count", "Countess", "Conde", "Condessa", "伯爵", "伯爵夫人", "Conde", "Condesa"],
  ["Viscount", "Viscountess", "Visconde", "Viscondessa", "子爵", "子爵夫人", "Vizconde", "Vizcondesa"],
  ["Baron", "Baroness", "Barão", "Baronesa", "男爵", "男爵夫人", "Barón", "Baronesa"],
  ["Lord", "Lady", "Lorde", "Lady", "卿", "夫人", "Lord", "Lady"],
  ["Pharaoh", "Pharaoh", "Faraó", "Faraó", "ファラオ", "ファラオ", "Faraón", "Faraona"],
  ["Overlord", "Overlord", "Soberano", "Soberana", "魔王", "魔王", "Soberano", "Soberana"],
  ["Master", "Master", "Mestre", "Mestra", "師匠", "師匠", "Maestro", "Maestra"],
  ["Sensei", "Sensei", "Sensei", "Sensei", "先生", "先生", "Sensei", "Sensei"],
  ["Elder", "Elder", "Ancião", "Anciã", "長老", "長老", "Anciano", "Anciana"],
  ["Chief", "Chief", "Chefe", "Chefe", "隊長", "隊長", "Jefe", "Jefa"],
  ["Boss", "Boss", "Chefão", "Chefona", "親分", "親分", "Jefazo", "Jefaza"],
  ["CEO", "CEO", "CEO", "CEO", "社長", "社長", "CEO", "CEO"],
  ["Manager", "Manager", "Gerente", "Gerente", "店長", "店長", "Gerente", "Gerente"],
  ["Principal", "Principal", "Diretor", "Diretora", "校長", "校長", "Rector", "Rectora"],
  ["Coach", "Coach", "Técnico", "Técnica", "監督", "監督", "Técnico", "Técnica"],
  ["Champion", "Champion", "Campeão", "Campeã", "王者", "王者", "Campeón", "Campeona"],
  ["Hero", "Heroine", "Herói", "Heroína", "勇者", "勇者", "Héroe", "Heroína"],
  ["Guardian", "Guardian", "Guardião", "Guardiã", "守護神", "守護神", "Guardián", "Guardiana"],
  ["Tycoon", "Tycoon", "Magnata", "Magnata", "大富豪", "大富豪", "Magnate", "Magnate"],
  ["Mister", "Madam", "Senhor", "Senhora", "さん", "さん", "Don", "Doña"],
  ["Uncle", "Aunt", "Tio", "Tia", "おじさん", "おばさん", "Tío", "Tía"],
  ["Grandpa", "Grandma", "Vovô", "Vovó", "じいじ", "ばあば", "Abuelo", "Abuela"],
  ["Papa", "Mama", "Papai", "Mamãe", "パパ", "ママ", "Papá", "Mamá"],
  ["Bro", "Sis", "Mano", "Mana", "兄貴", "姉貴", "Hermano", "Hermana"],
  ["Baby", "Baby", "Bebê", "Bebê", "ちゃん", "ちゃん", "Bebé", "Bebé"],
  ["Sir", "Dame", "Sir", "Dama", "殿", "御前", "Sir", "Dama"],
  ["Shogun", "Shogun", "Xogum", "Xogum", "大将", "大将", "Shogun", "Shogun"],
  ["Dean", "Dean", "Reitor", "Reitora", "学長", "学長", "Decano", "Decana"],
  ["Chancellor", "Chancellor", "Chanceler", "Chanceler", "宰相", "宰相", "Canciller", "Canciller"],
  ["Cadet", "Cadet", "Cadete", "Cadete", "候補生", "候補生", "Cadete", "Cadete"],
  ["Private", "Private", "Soldado", "Soldada", "二等兵", "二等兵", "Soldado", "Soldada"],
  ["Marshal", "Marshal", "Marechal", "Marechal", "元帥", "元帥", "Mariscal", "Mariscal"],
  ["Archduke", "Archduchess", "Arquiduque", "Arquiduquesa", "大公", "大公妃", "Archiduque", "Archiduquesa"],
  ["Squire", "Squire", "Escudeiro", "Escudeira", "従者", "従者", "Escudero", "Escudera"],
  ["Paladin", "Paladin", "Paladino", "Paladina", "聖騎士", "聖騎士", "Paladín", "Paladina"],
  ["Maestro", "Maestro", "Maestro", "Maestrina", "マエストロ", "マエストロ", "Director", "Directora"],
  ["Ace", "Ace", "Ás", "Ás", "エース", "エース", "As", "As"],
  ["Idol", "Idol", "Ídolo", "Ídolo", "アイドル", "アイドル", "Ídolo", "Ídolo"],
  ["Streamer", "Streamer", "Streamer", "Streamer", "配信者", "配信者", "Streamer", "Streamer"],
  ["Senpai", "Senpai", "Senpai", "Senpai", "先輩", "先輩", "Senpai", "Senpai"],
  ["Rookie", "Rookie", "Novato", "Novata", "新人", "新人", "Novato", "Novata"],
  ["Buddy", "Buddy", "Parça", "Parça", "くん", "くん", "Compa", "Compa"],
];

/** Rare names, hand-picked: one new guest in a hundred gets one (see LEGENDARY_CHANCE). */
// biome-ignore format: word table
export const LEGENDARY: readonly Legendary[] = [
  ["Doge", "Doge", "ドージ", "Doge"],
  ["Stonks", "Stonks", "ストンクス", "Stonks"],
  ["NyanCat", "NyanCat", "ニャンキャット", "NyanCat"],
  ["PopCat", "PopCat", "ポップキャット", "PopCat"],
  ["HappyHappyCat", "GatoHappyHappy", "ハッピーハッピー猫", "GatoHappyHappy"],
  ["HuhCat", "GatoHuh", "ハァ猫", "GatoHuh"],
  ["BananaCat", "GatoBanana", "バナナ猫", "GatoBanana"],
  ["ChipiChipiChapa", "ChipiChipiChapa", "チピチピチャパ", "ChipiChipiChapa"],
  ["OiiaOiiaCat", "GatoOiiaOiia", "オイアオイア猫", "GatoOiiaOiia"],
  ["VibingCat", "GatoVibando", "ノリノリ猫", "GatoVibrando"],
  ["KeyboardCat", "GatoTecladista", "キーボード猫", "GatoTecladista"],
  ["CeilingCat", "GatoDoTeto", "天井猫", "GatoDelTecho"],
  ["Longcat", "Longcat", "ロングキャット", "Longcat"],
  ["BongoCat", "BongoCat", "ボンゴキャット", "BongoCat"],
  ["Bingus", "Bingus", "ビンガス", "Bingus"],
  ["BigFloppa", "BigFloppa", "ビッグフロッパ", "BigFloppa"],
  ["Cheems", "Cheems", "チームズ", "Cheems"],
  ["Doggo", "Doguinho", "わんこ", "Firulais"],
  ["CaramelMutt", "ViraLataCaramelo", "キャラメル犬", "PerroCaramelo"],
  ["MooDeng", "MooDeng", "ムーデン", "MooDeng"],
  ["PedroRaccoon", "GuaxinimPedro", "ペドロアライグマ", "MapachePedro"],
  ["SadHamster", "HamsterTriste", "悲しいハムスター", "HámsterTriste"],
  ["TrashPanda", "PandaDoLixo", "ゴミパンダ", "PandaBasurero"],
  ["DangerNoodle", "MacarrãoPerigoso", "危険なヌードル", "FideoPeligroso"],
  ["SeaPancake", "PanquecaDoMar", "海のパンケーキ", "PanquequeDeMar"],
  ["AbsoluteUnit", "UnidadeAbsoluta", "規格外", "UnidadAbsoluta"],
  ["DatBoi", "DatBoi", "ダットボーイ", "DatBoi"],
  ["Trollface", "Trollface", "トロールフェイス", "Trollface"],
  ["Rickroll", "Rickroll", "リックロール", "Rickroll"],
  ["ThisIsFine", "TáTudoBem", "大丈夫だ問題ない", "TodoBien"],
  ["GalaxyBrain", "CérebroGaláctico", "銀河脳", "CerebroGaláctico"],
  ["GigaChad", "GigaChad", "ギガチャド", "GigaChad"],
  ["Bonk", "Bonk", "ボンク", "Bonk"],
  ["Moai", "Moai", "モアイ", "Moai"],
  ["Skibidi", "Skibidi", "スキビディ", "Skibidi"],
  ["Amogus", "Amogus", "アモングス", "Amogus"],
  ["Kappa", "Kappa", "カッパ", "Kappa"],
  ["Hackerman", "Hackerman", "ハッカーマン", "Hackerman"],
  ["CakeIsALie", "OBoloÉMentira", "ケーキは嘘", "ElPastelEsMentira"],
  ["OverNineThousand", "MaisDeOitoMil", "戦闘力53万", "MásDeOchoMil"],
  ["FinalAnswer", "RespostaFinal", "ファイナルアンサー", "RespuestaFinal"],
  ["MainCharacter", "Protagonista", "主人公", "Protagonista"],
  ["RageQuit", "RageQuit", "台パン", "RageQuit"],
  ["PressF", "PressF", "Fで敬意を", "PressF"],
  ["NullPointer", "NullPointer", "ぬるぽ", "NullPointer"],
  ["Orz", "Orz", "orz", "Orz"],
  ["PleadingFace", "CarinhaPidona", "ぴえん", "OjitosDeCachorro"],
  ["SmugFace", "CaraDeConvencido", "ドヤ顔", "CaraDeCreído"],
  ["Rofl", "Kkkkkkk", "大草原", "Jajajaja"],
  ["TGIF", "Sextou", "花金", "YaEsViernes"],
  ["DadJoker", "TioDoPavê", "ダジャレおじさん", "ReyDelChisteMalo"],
  ["GifOrJif", "BiscoitoOuBolacha", "きのこたけのこ", "PaltaOAguacate"],
  ["BrrBrrPatapim", "BrrBrrPatapim", "ブルブルパタピン", "BrrBrrPatapim"],
  ["TungTungSahur", "TungTungSahur", "トゥントゥンサフール", "TungTungSahur"],
  ["Chimpanzini", "Chimpanzini", "チンパンジーニ", "Chimpanzini"],
  ["Birb", "Birb", "トリさん", "Birb"],
  ["Snek", "Snek", "ヘビちゃん", "Snek"],
  ["Blep", "Blep", "ペロッ", "Blep"],
  ["Boop", "Boop", "ぷにっ", "Boop"],
  ["Rawr", "Rawr", "がおー", "Rawr"],
  ["LongBoi", "LongBoi", "ロングボーイ", "LongBoi"],
  ["Hampter", "Hampter", "ハムプター", "Hampter"],
  ["HamsterDance", "HamsterDance", "ハムスターダンス", "HamsterDance"],
  ["CrabRave", "CrabRave", "カニレイブ", "CrabRave"],
  ["DancingBaby", "BebêDançante", "ダンシングベイビー", "BebéBailarín"],
  ["NumaNuma", "NumaNuma", "恋のマイアヒ", "NumaNuma"],
  ["PPAP", "PPAP", "ペンパイナッポー", "PPAP"],
  ["BluePen", "CanetaAzul", "青いペン", "BolígrafoAzul"],
  ["ToTheMoon", "RumoÀLua", "月まで", "HastaLaLuna"],
  ["Thonk", "Thonk", "考え中", "Thonk"],
  ["AllYourBase", "TodaSuaBase", "君達の基地", "TodaTuBase"],
  ["DoABarrelRoll", "FazUmBarrelRoll", "バレルロール", "HazUnBarrelRoll"],
  ["ItsATrap", "ÉUmaArmadilha", "罠だ", "EsUnaTrampa"],
  ["Wololo", "Wololo", "ウォロロ", "Wololo"],
  ["Hadouken", "Hadouken", "波動拳", "Hadouken"],
  ["Kamehameha", "Kamehameha", "かめはめ波", "Kamehameha"],
  ["ZaWarudo", "ZaWarudo", "ザ・ワールド", "ZaWarudo"],
  ["YareYare", "YareYare", "やれやれ", "YareYare"],
  ["Nani", "Nani", "なにぃ", "Nani"],
  ["Yatta", "Yatta", "やった", "Yatta"],
];

/** Titles that also stand alone in Japanese, after an adjective: not さん, ちゃん, くん or 殿. */
const STANDALONE_TITLES = TITLES.filter(
  ([, , , , ja]) => !["さん", "ちゃん", "くん", "殿"].includes(ja),
);

/** Titles with a different word for each gender in every language ("King", "Queen"). */
const GENDERED_TITLES = TITLES.filter(
  ([enM, enF, ptM, ptF, jaM, jaF, esM, esF]) =>
    enM !== enF && ptM !== ptF && jaM !== jaF && esM !== esF,
);

// Guest numbers run through the shapes in order: adjective and noun, hybrids, title and
// noun, the legendary names, title and adjective, then gendered titles and nouns in the
// other gender (each added last, so older numbers keep their names).
const ADJECTIVE_NOUNS = ADJECTIVES.length * NOUNS.length;
const HYBRIDS = NOUNS.length * NOUNS.length;
const TITLED = TITLES.length * NOUNS.length;
const LEGENDARY_START = ADJECTIVE_NOUNS + HYBRIDS + TITLED;
const TITLED_ADJECTIVES = STANDALONE_TITLES.length * ADJECTIVES.length;
const CROSS_TITLED = GENDERED_TITLES.length * NOUNS.length;
export const GUEST_NAME_COUNT =
  LEGENDARY_START + LEGENDARY.length + TITLED_ADJECTIVES + CROSS_TITLED;

/** A noun in a language. */
const nounIn = ([en, pt, , ja, es]: Noun, lang: Lang) =>
  lang === "pt" ? pt : lang === "es" ? es : lang === "ja" ? ja : en;

/** A title and a noun, the title in the given gender. */
function titled(title: Title, noun: Noun, f: boolean, lang: Lang): string {
  const [enM, enF, ptM, ptF, jaM, jaF, esM, esF] = title;
  const word = nounIn(noun, lang);
  if (lang === "pt") return (f ? ptF : ptM) + word;
  if (lang === "es") return (f ? esF : esM) + word;
  if (lang === "ja") return word + (f ? jaF : jaM);
  return (f ? enF : enM) + word;
}

/**
 * A guest's name from their guest number, written as one word.
 * Adjective and noun: English and Japanese put the adjective first ("WonderfulCat",
 * "すてきなネコ"); Portuguese and Spanish put the noun first and agree in gender
 * ("GatoMaravilhoso", "RaposaMaravilhosa", "RanaMaravillosa"), each with its own
 * noun's gender ("ZorroMaravilloso").
 * Hybrid: two nouns in the same order everywhere ("PotatoNinja", "BatataNinja").
 * Title and noun: the title first, last in Japanese ("QueenFox", "RainhaRaposa",
 * "ReinaZorro", "キツネ女王"). Its gender follows the noun's Portuguese one in every
 * language; gendered titles also come in the other one ("QueenCat", "RainhaGato",
 * "ネコ女王").
 * Title and adjective: the same order, the adjective first in Japanese ("CaptainBrave",
 * "CapitãoCorajoso", "勇敢な船長"). With no noun to give a gender, half the pairs are
 * masculine and half feminine; both would read the same in English.
 */
export function guestName(guestNumber: number, lang: Lang): string {
  let i = Math.abs(Math.trunc(guestNumber) || 0) % GUEST_NAME_COUNT;
  if (i < ADJECTIVE_NOUNS) {
    const [en, ptM, ptF, ja, esM, esF] = ADJECTIVES[i % ADJECTIVES.length];
    const noun = NOUNS[Math.floor(i / ADJECTIVES.length)];
    const [, , gender, , , esGender] = noun;
    const word = nounIn(noun, lang);
    if (lang === "pt") return word + (gender === "f" ? ptF : ptM);
    if (lang === "es") return word + (esGender === "f" ? esF : esM);
    if (lang === "ja") return ja + word;
    return en + word;
  }
  i -= ADJECTIVE_NOUNS;
  if (i < HYBRIDS) {
    return (
      nounIn(NOUNS[Math.floor(i / NOUNS.length)], lang) +
      nounIn(NOUNS[i % NOUNS.length], lang)
    );
  }
  i -= HYBRIDS;
  if (i < TITLED) {
    const noun = NOUNS[Math.floor(i / TITLES.length)];
    return titled(TITLES[i % TITLES.length], noun, noun[2] === "f", lang);
  }
  i -= TITLED;
  if (i < LEGENDARY.length) {
    const [en, pt, ja, es] = LEGENDARY[i];
    return lang === "pt" ? pt : lang === "es" ? es : lang === "ja" ? ja : en;
  }
  i -= LEGENDARY.length;
  if (i >= TITLED_ADJECTIVES) {
    i -= TITLED_ADJECTIVES;
    const noun = NOUNS[Math.floor(i / GENDERED_TITLES.length)];
    // the other gender than the noun's
    const title = GENDERED_TITLES[i % GENDERED_TITLES.length];
    return titled(title, noun, noun[2] === "m", lang);
  }
  const t = i % STANDALONE_TITLES.length;
  const a = Math.floor(i / STANDALONE_TITLES.length);
  const [enM, enF, ptM, ptF, jaM, jaF, esM, esF] = STANDALONE_TITLES[t];
  const [en, adjPtM, adjPtF, ja, adjEsM, adjEsF] = ADJECTIVES[a];
  const f = (t + a) % 2 === 1;
  if (lang === "pt") return f ? ptF + adjPtF : ptM + adjPtM;
  if (lang === "es") return f ? esF + adjEsF : esM + adjEsM;
  if (lang === "ja") return ja + (f ? jaF : jaM);
  return (f ? enF : enM) + en;
}

/**
 * The name a reader sees: an account's own, else the guest name in the
 * reader's language. Only the server calls it: the browser gets names ready.
 */
export const displayName = (
  p: { isGuest: boolean; name: string | null; guestNumber: number },
  lang: Lang,
) => (!p.isGuest && p.name ? p.name : guestName(p.guestNumber, lang));

/** Longest name allowed per language (in characters), so names fit the player strip. */
export const GUEST_NAME_MAX: Record<Lang, number> = {
  en: 18,
  pt: 18,
  es: 18,
  ja: 10,
};

const fits = (n: number) =>
  LANGS.every((l) => [...guestName(n, l)].length <= GUEST_NAME_MAX[l]);

/** How often a new guest gets a legendary name. */
export const LEGENDARY_CHANCE = 1 / 100;

/** A random guest number whose name is short enough in every language; now and then a legendary one. */
export function randomGuestNumber(random: () => number = Math.random): number {
  if (random() < LEGENDARY_CHANCE)
    return LEGENDARY_START + Math.floor(random() * LEGENDARY.length);
  let n = 0;
  for (let tries = 0; tries < 100; tries++) {
    // every number but the legendary ones
    n = Math.floor(random() * (GUEST_NAME_COUNT - LEGENDARY.length));
    if (n >= LEGENDARY_START) n += LEGENDARY.length;
    if (fits(n)) return n;
  }
  return n;
}
