// Every word of the guest names mapped to a piece of the drawing, in a small
// grammar (see parse in index.ts). Keyed by the English word.
// Nouns: what the body is (first noun) and what it lends to another (second noun of a hybrid).
export const NOUN: Record<string, string> = {
  Cat: "gum e:cat f:cat c:orange/gray/cream/charcoal/ginger",
  Dog: "gum e:floppy f:muzzle o:tongue c:tan/brown/cream/white",
  Fox: "gum e:fox m:cheeks f:cat c:orange",
  Panda: "gum e:bear ec:black m:patches f:muzzle c:white eyeBase",
  Penguin: "round m:bib f:beak c:navy",
  Owl: "round e:tuft m:discs x:ring f:hook c:brown/tan/gray",
  Rabbit: "gum e:bunny f:bunny c:white/cream/gray/tan",
  Bear: "gum e:bear f:muzzle c:brown/choc/tan",
  Tiger: "gum e:cat m:stripes m:cheeks f:cat c:orange",
  Lion: "gum e:bear t:mane f:cat c:gold",
  Wolf: "gum e:fox m:cheeks f:muzzle c:gray/slate",
  Frog: "wide bulge x:big blush c:green/lime",
  Turtle: "gum t:shell c:lime/green",
  Duck: "round t:tuft f:bill c:yellow/white",
  Goose: "gum f:beak c:white",
  Chick: "round t:tuft f:beak blush c:yellow",
  Piglet: "gum e:pig f:snout c:pink",
  Pony: "gum e:cat t:forelock f:muzzle c:tan/brown/white",
  Goat: "gum h:goat e:small f:muzzle wear:goatee c:white/cream/tan",
  Sheep: "fluffy e:small m:faceplate c:cream/white",
  Llama: "bean e:bunny t:fluff f:muzzle c:cream/white/tan",
  Alpaca: "fluffy e:bunny f:muzzle c:cream/white/peach",
  Camel: "bean e:small x:lashes f:muzzle c:tan/sand",
  Giraffe: "bean h:ossicone e:small m:spots f:muzzle c:gold/yellow",
  Elephant: "gum e:elephant f:trunk c:gray/slate",
  Hippo: "wide e:small f:hippo c:lilac/gray",
  Rhino: "gum e:small f:rhino c:gray/slate",
  Zebra: "bean e:cat t:mohawk m:zstripes f:muzzle c:white",
  Kangaroo: "gum e:bunny f:cat c:tan/ginger",
  Koala: "gum e:koala f:koalanose c:gray",
  Sloth: "gum m:slothmask x:sleepy o:smile c:tan/brown",
  Capybara: "square e:small f:capy x:sleepy c:brown/tan",
  Armadillo: "gum e:small m:rings f:cat c:tan/gray",
  Anteater: "gum e:small f:anteater c:gray/tan",
  Toucan: "round m:bib f:bigbeak c:black",
  Parrot: "gum t:crest f:hook c:green/red/blue",
  Flamingo: "bean f:flamingo c:pink/rose",
  Peacock: "gum t:peacock f:beak c:blue/teal",
  Swan: "gum f:beak c:white",
  Eagle: "gum f:hook x:dot c:white/brown",
  Falcon: "gum f:hook m:cheekmarks c:slate/tan",
  Crow: "gum f:beak c:charcoal/black",
  Pigeon: "round f:beak c:gray/slate",
  Sparrow: "round f:beak m:belly c:brown/tan",
  Seagull: "gum f:beak c:white/silver",
  Pelican: "gum f:bigbeak c:white",
  Ostrich: "bean t:tuft f:beak c:charcoal/gray",
  Bat: "gum e:bat w:bat o:fang c:lilac/purple/charcoal",
  Hedgehog: "gum t:spikes m:faceplate f:cat c:tan/sand p:plate=#F6E7CC",
  Hamster: "gum e:small cheekpuffs f:cat c:ginger/cream/tan",
  Mouse: "gum e:mouse f:mouse c:gray/white/tan",
  Squirrel: "gum e:tuft f:beaver w:bushytail c:ginger/brown",
  Beaver: "gum e:small f:beaver c:brown",
  Otter: "gum e:small m:cheeks f:seal c:brown/choc",
  Raccoon: "gum e:cat m:band m:cheeks f:cat c:gray eyeBase",
  Badger: "gum e:small m:stripe f:cat c:gray/charcoal",
  Skunk: "gum e:small m:stripe f:cat c:charcoal/black",
  Deer: "gum h:antlers e:cat m:whitespots f:muzzle c:tan/brown",
  Moose: "gum h:antlers e:small f:muzzle c:brown/choc",
  Reindeer: "gum h:antlers e:cat f:rednose c:brown/tan",
  Seal: "round f:seal c:gray/silver",
  Walrus: "round f:walrus c:brown/tan",
  Dolphin: "gum t:fin m:belly c:sky/blue/gray",
  Shark: "gum t:fin m:belly f:sharp c:slate/gray/blue",
  Octopus: "tent m:suckers c:pink/coral/purple/red",
  Crab: "wide a:stalks e:claws noEyes c:red/coral/orange",
  Lobster: "gum a:feelers e:claws c:red",
  Shrimp: "bean a:feelers m:segments c:coral/pink",
  Pufferfish: "round t:puffspikes m:belly c:yellow/gold",
  Snail: "round t:snailshell a:stalks noEyes c:mint/lime/lilac",
  Bee: "round a:bug m:bands w:insect c:yellow",
  Ant: "gum a:bug c:red/charcoal/brown",
  Ladybug: "round a:bug m:ladyspots c:red",
  Butterfly: "gum a:bug w:butterfly c:lilac/sky/pink/orange",
  Dragonfly: "bean a:bug w:insect x:big c:teal/blue/green",
  Cricket: "gum a:long c:green/lime",
  Beetle: "gum h:beetle a:bug c:teal/blue/purple",
  Spider: "round x:spider c:charcoal/purple/black",
  Lizard: "bean bulge o:forked m:spots c:green/lime/teal",
  Gecko: "gum bulge x:big m:spots blush c:lime/orange/yellow",
  Chameleon: "gum t:chamcrest x:wide c:green/teal/lime/orange",
  Crocodile:
    "wide bulge t:ridge f:croc m:scutes c:forest/green p:ridgeCol=#2C7550",
  Alligator:
    "wide bulge t:ridge f:gator m:scutes c:olive/forest p:ridgeCol=#6B6E3A",
  Dinosaur: "gum t:ridge c:green/teal/lilac",
  Mammoth: "gum e:elephant t:fluff f:mammoth c:brown/choc",
  Dodo: "round t:tuft f:dodobeak c:gray/slate",
  Platypus: "gum f:bill c:brown/choc",
  Axolotl: "gum e:gills blush c:pink/lilac/white",
  Narwhal: "round t:tusk m:spots c:slate/gray/sky",
  Leopard: "gum e:cat m:rosettes f:cat c:gold/yellow",
  Jaguar: "gum e:bear m:rosettes f:cat c:gold",
  Cheetah: "gum e:bear m:spots m:tearlines f:cat c:gold/yellow",
  Lynx: "gum e:lynx m:cheeks f:cat c:tan/gray",
  Puma: "gum e:cat m:cheeks f:cat c:tan",
  Hyena: "gum e:bear m:spots f:muzzle o:grin c:tan/sand",
  Meerkat: "bean e:small m:band f:cat c:sand/tan eyeBase",
  Lemur: "gum e:cat m:darkdiscs x:ring f:cat c:gray",
  Chinchilla: "gum e:mouse f:mouse c:gray/silver",
  Ferret: "bean e:small m:band f:cat c:cream/tan eyeBase",
  Yak: "gum h:bull t:fluff f:muzzle c:choc/charcoal",
  Bison: "wide h:bull t:fluff f:muzzle c:choc/brown",
  Quail: "round t:plume f:beak m:specks c:tan/brown",
  Kiwi: "round f:longbeak c:brown/tan",
  Pangolin: "gum m:scales f:cat c:tan/brown",
  Wombat: "wide e:small f:wombatnose c:brown/tan",
  Dragon: "gum h:dragon t:ridge w:bat o:fang c:green/red/purple/teal",
  Unicorn:
    "gum e:cat t:unihorn t:forelock f:muzzle c:white/pink/lilac p:mane=#F38FAA",
  Phoenix: "gum t:flame w:feather f:hook c:red/orange",
  Griffin: "gum e:tuft w:feather f:hook c:gold/tan",
  Yeti: "fluffy m:faceplate c:white p:plate=#BFE3EA",
  Ghost: "ghost o:o c:white",
  Robot: "square a:robot x:pixel f:none o:grill c:silver/sky/gray",
  Alien: "bean a:alien x:big c:lime/green/teal/lilac",
  Wizard: "blob out:robe p:shirt=purple wear:wizard wear:beard p:lend=wizard",
  Ninja:
    "blob c:charcoal m:ninjaband wear:headband=#E8574D p:dtop=none p:lend=headband=#2D3240",
  Pirate:
    "blob out:stripes p:shirt=red wear:pirate wear:eyepatch p:lend=pirate,eyepatch",
  Knight: "blob out:armor p:shirt=silver wear:knight p:lend=knight",
  Viking:
    "blob out:fur p:shirt=brown wear:viking wear:beard=#E5803E p:lend=viking",
  Astronaut: "blob out:space p:shirt=white wear:astronaut p:lend=astronaut",
  Detective: "blob out:coat p:shirt=tan wear:deerstalker p:lend=deerstalker",
  Chef: "blob out:tee p:shirt=white wear:toque wear:scarf=#E8574D wear:mustache p:lend=toque",
  Mermaid: "gum t:hairlong m:scales c:teal/mint/aqua p:lend=flower",
  Elf: "blob e:elf out:tee p:shirt=green",
  Gnome: "blob out:tee p:shirt=blue wear:gnomehat wear:beard p:lend=gnomehat",
  Vampire:
    "blob c:lilac/platinum t:widow o:fangs wear:collar out:suit p:shirt=black p:lend=collar",
  Zombie: "blob c:lime/mint m:stitches x:half o:flat out:torn p:shirt=slate",
  Mummy: "gum m:bandages c:bone",
  Kraken: "tent m:suckers c:purple/teal",
  Sphinx: "gum wear:nemes f:cat c:gold/tan",
  Centaur: "blob out:toga p:shirt=white wear:laurel p:lend=laurel",
  Pegasus: "gum e:cat t:forelock w:feather f:muzzle c:white/sky p:wing=#BFE3EA",
  Fairy: "gum w:fairy fx:sparkles c:pink/lilac/mint",
  Goblin: "gum e:elf o:grin c:green/lime",
  Potato: "lumpy m:specks c:tan/sand",
  Pancake: "wide t:butter m:pancake c:gold/tan",
  Cookie: "round m:chips c:tan/sand",
  Donut: "ring t:ringfrost c:tan/caramel",
  Waffle: "square m:grid c:gold",
  Muffin: "cupcake t:muffintop m:pleats c:sky/pink/white",
  Pudding: "jello t:caramel c:yellow",
  Taco: "taco t:tacofill m:specks c:gold",
  Ramen: "bowl t:ramen m:bowlband c:red/navy",
  Pickle: "bean m:bumps c:green/olive",
  Avocado: "pear m:pit c:lime",
  Pineapple: "gum t:leafcrown m:crosshatch c:gold/yellow",
  Mango: "round t:leaf m:blushside c:orange/gold",
  Lemon: "round t:leaf c:yellow",
  Peach: "round t:leaf m:crease c:coral/peach",
  Tomato: "round t:calyx c:red",
  Carrot: "bean t:fronds m:lines c:orange",
  Broccoli: "brocco t:florets c:lime",
  Mushroom: "gum t:mushcap c:cream p:capCol=#E8574D",
  Pumpkin: "wide t:stem m:ribs c:orange",
  Popcorn: "fluffy m:boxstripes c:cream",
  Cupcake: "cupcake t:cupfrost m:pleats blush c:pink/sky/mint/yellow/lilac",
  Croissant: "crescent m:croissegs c:gold",
  Sushi: "wide t:salmon m:noriband c:white",
  Tofu: "square c:white/cream",
  Mochi: "round blush c:white/pink/mint",
  Nugget: "lumpy m:specks c:gold",
  Cactus: "bean t:cactusarms t:flower m:bumps c:green/forest",
  Acorn: "round t:acorncap c:tan/brown",
  Cloud: "fluffy blush c:white",
  Comet: "ball fx:comettail c:yellow/gold blush",
  Meteor: "lumpy fx:meteortail m:craters c:slate/brown",
  Rocket: "bean t:nosecone w:fins m:window c:white/silver",
  Volcano: "tri t:lava c:brown/choc",
  Tornado: "funnel m:swirl c:gray/slate",
  Teapot: "round t:lid t:spout c:sky/mint/pink/white",
  Toaster: "square t:toast m:slots c:silver/red/mint",
  Sock: "bean m:sockstripes c:red/sky/lime",
  Pillow: "square m:seams c:white/lilac/pink",
  Balloon: "round fx:string m:shine c:red/sky/pink/yellow",
  Kite: "tri m:kitecross fx:string c:red/yellow/sky",
  Orca: "gum t:fin m:orca c:black",
  Manatee: "round f:seal c:gray/slate",
  Stingray: "wide w:fins m:belly c:slate/gray/sky",
  Jellyfish: "jelly blush c:pink/lilac/aqua",
  Seahorse: "bean t:crest f:longsnout c:orange/yellow/coral",
  Clownfish: "gum e:fishfins t:fin m:clownbands c:orange",
  Hummingbird: "round f:longbeak c:teal/green",
  Macaw: "gum t:crest f:hook c:red/blue/gold",
  Puffin: "round m:bib f:puffinbeak c:black",
  Stork: "gum f:longbeak p:beak=#E8574D c:white",
  Rooster: "gum t:comb f:beak m:wattle c:white/gold/red",
  Fennec: "gum e:big f:cat c:sand/cream",
  Coati: "bean e:small m:band f:cat c:brown/tan eyeBase",
  Ocelot: "gum e:cat m:rosettes f:cat c:gold/tan",
  PolarBear: "gum e:bear f:muzzle c:white",
  Koi: "gum m:koi f:koiwhiskers c:white",
  Mongoose: "bean e:small f:cat c:tan/gray",
  Iguana: "gum t:ridge m:spots c:green/lime p:ridgeCol=#3D8F62",
  Tortoise: "gum t:shell c:olive/tan p:shellCol=#A06F4C",
  Tadpole: "round fx:tadtail c:charcoal/slate",
  Firefly: "gum a:bug w:insect m:glowbelly c:charcoal/navy",
  Tanuki: "gum e:bear m:band f:muzzle c:brown/tan eyeBase",
  Cyclops: "gum h:oni x:mono c:lilac/sky/lime",
  Golem: "square m:cracks c:gray/slate/sand",
  Chupacabra: "gum t:spikes o:fang c:green/olive",
  Bigfoot: "fluffy m:faceplate c:brown/choc p:plate=#D6A26B",
  Werewolf: "gum e:fox m:cheeks f:muzzle o:fang c:gray/slate/brown",
  Cowboy: "blob out:tee wear:cowboy wear:scarf=#E8574D p:lend=cowboy",
  Samurai: "blob out:kimono p:shirt=navy wear:kabuto p:lend=kabuto",
  Spy: "blob out:suit p:shirt=charcoal wear:fedora wear:shades p:lend=fedora,shades",
  Explorer: "blob out:tee p:shirt=sand wear:safari p:lend=safari",
  Scientist: "blob out:labcoat p:shirt=white wear:goggles p:lend=goggles",
  Firefighter:
    "blob out:vest p:shirt=red wear:hardhat=#E8574D wear+badge p:lend=hardhat=#E8574D",
  Sailor: "blob out:sailor p:shirt=white wear:sailorcap p:lend=sailorcap",
  Surfer:
    "blob out:hawaii p:shirt=sky wear:shades wear:flower p:lend=shades,flower",
  Poet: "blob out:turtleneck p:shirt=charcoal wear:beret wear:scarf p:lend=beret",
  Gamer: "blob out:hoodie p:shirt=purple wear:headphones p:lend=headphones",
  Strawberry: "round t:calyx m:seeds c:red",
  Watermelon: "round m:melonstripes c:green",
  Cheese: "tri m:holes c:yellow/gold",
  Pizza: "tri m:pepperoni c:yellow",
  Burger: "wide t:sesame m:burger c:tan",
  Dumpling: "round t:pleats c:white/cream",
  RiceBall: "tri m:nori c:white",
  CheeseBread: "round m:specks c:gold/sand",
  Tapioca: "halfmoon t:tapfill m:specks c:white",
  Churro: "bean m:ridges m:sugar c:tan/gold",
  Marshmallow: "square blush c:white/pink",
  Takoyaki: "round m:sauce t:bonito c:tan/brown",
  Sunflower: "round t:petals c:brown",
  Bonsai: "bonsai t:bonsaitree c:caramel/sky",
  Crystal: "gem m:gemfacets c:lilac/sky/mint/pink",
  Snowman: "round f:carrotnose wear:scarf c:white",
  Planet: "round t:ring c:lilac/sky/coral",
  UFO: "wide t:ufodome m:lights c:silver",
  Umbrella: "blob t:umbrella",
  Ukulele: "pear t:ukeneck m:soundhole m:strings c:tan/gold",
  Slipper: "sole t:strap m:solein c:sky/pink/yellow/lime",
  Submarine: "bean t:periscope m:portholes c:yellow/gold",
  Gnu: "gum h:bull t:fluff f:muzzle c:slate/gray",
  Emu: "bean t:tuft f:beak c:brown/charcoal",
  Newt: "gum bulge x:big m:spots c:orange/coral",
  Hare: "gum e:bunny f:bunny c:tan/brown",
  Lamb: "fluffy e:small m:faceplate c:white",
  Kitten: "round e:cat f:cat x:big blush c:orange/gray/cream/white",
  Eel: "bean t:softfin m:belly x:big c:olive/teal/slate",
  Tuna: "gum e:fishfins t:fin m:belly c:slate/blue",
  Salmon: "gum e:fishfins t:fin m:belly c:coral/pink",
  Oni: "gum h:oni o:fangs c:red/sky/lime",
  Tengu: "gum f:tengunose c:red",
  Minotaur: "gum h:bull f:muzzle c:brown/choc",
  Baker: "blob out:apron p:shirt=peach wear:bakerhat p:lend=bakerhat",
  Painter: "blob out:tee p:shirt=white wear:beret m:paintspots p:lend=beret",
  Pilot:
    "blob out:coat p:shirt=brown wear:pilotcap wear:scarf=#FBF9F4 p:lend=pilotcap",
  Miner: "blob out:vest p:shirt=orange wear:hardhat wear+lamp p:lend=hardhat",
  Bagel: "ring m:specks c:tan/caramel",
  Brownie: "square m:cracks c:choc",
  Noodle: "cup t:cupnoodles m:cupband c:white",
  Melon: "round m:net c:lime/mint",
  Pear: "pear t:stem c:lime/gold",
  Jelly: "jello t:cream m:jellolines m:shine c:red/lime/purple",
  Yoyo: "round m:yoyo fx:string c:red/sky",
  Pebble: "lumpy x:sleepy c:gray/slate/sand",
  Moon: "round m:craters fx:stars c:butter/bone",
  Drum: "square m:drum c:red/sky",
};

// Adjectives: expression, colour, pattern, something to wear or an effect.
export const ADJ: Record<string, string> = {
  Brave: "ex:brave",
  Sleepy: "ex:sleepy fx:zzz",
  Hungry: "ex:hungry",
  Happy: "ex:happy",
  Sneaky: "ex:sneaky",
  Clever: "ex:smug",
  Curious: "ex:surprised fx:question",
  Fluffy: "shape:fluffy",
  Fuzzy: "shape:fluffy",
  Cute: "ex:cute",
  Tiny: "size:.8 ex:cute",
  Giant: "size:1.1",
  Golden: "c:gold m:shine fx:sparkles",
  Silver: "c:silver m:shine",
  Purple: "c:purple",
  Blue: "c:blue",
  Red: "c:red",
  Green: "c:green",
  Yellow: "c:yellow",
  Pink: "c:pink",
  Orange: "c:orange",
  Turquoise: "c:teal",
  Rainbow: "fx:rainbow",
  Cosmic: "c:navy m:galaxy fx:stars",
  Galactic: "c:purple m:galaxy fx:stars",
  Stellar: "ex:excited fx:stars",
  Lunar: "c:platinum fx:moon",
  Solar: "c:gold fx:sun",
  Quantum: "fx:atom",
  Electric: "fx:bolt",
  Digital: "x:pixel",
  Pixel: "x:pixel",
  Neon: "c:magenta fx:glow",
  Turbo: "fx:speed",
  Mysterious: "wear:fedora ex:sneaky",
  Secret: "wear:disguise",
  Hidden: "ex:shy",
  Invisible: "style:invisible",
  Undercover: "wear:disguise",
  Lazy: "ex:sleepy",
  Grumpy: "ex:grumpy",
  Shy: "ex:shy",
  Bold: "ex:brave",
  Quiet: "ex:quiet",
  Noisy: "ex:open fx:exclaim",
  Lucky: "fx:clover",
  Speedy: "fx:speed",
  Quick: "fx:speed",
  Wild: "ex:fierce",
  Gentle: "ex:calm",
  Jolly: "ex:happy",
  Calm: "ex:calm",
  Dizzy: "ex:dizzy",
  Fancy: "wear:bowtie wear:monocle",
  Cool: "wear:shades",
  Fierce: "ex:fierce",
  Friendly: "ex:happy",
  Funny: "ex:silly",
  Charming: "ex:wink",
  Glowing: "fx:glow",
  Graceful: "ex:calm",
  Humble: "ex:shy",
  Jumpy: "ex:surprised",
  Kind: "ex:calm fx:hearts",
  Generous: "ex:happy fx:hearts",
  Legendary: "wear:laurel fx:glow",
  Lively: "ex:happy",
  Loyal: "ex:cute",
  Magic: "wear:wizard fx:sparkles",
  Majestic: "wear:crown",
  Mighty: "ex:brave size:1.06",
  Nimble: "fx:speed",
  Noble: "wear:tiara",
  Peculiar: "ex:odd",
  Playful: "ex:tongue",
  Polite: "wear:bowtie ex:calm",
  Proud: "ex:smug",
  Radiant: "fx:glow fx:sparkles",
  Serious: "ex:serious",
  Shiny: "m:shine fx:sparkles",
  Silent: "ex:quiet",
  Silly: "ex:silly",
  Smart: "wear:glasses",
  Smooth: "ex:smug",
  Sparkly: "fx:sparkles",
  Spotted: "m:spots",
  Striped: "m:stripes",
  Stormy: "fx:storm",
  Tidy: "wear:bowtie",
  Tough: "ex:fierce wear:bandaid",
  Cheeky: "ex:tongue",
  Wandering: "wear:safari",
  Wise: "wear:glasses wear:beard",
  Ancient: "wear:beard wear:oldbrows",
  Awesome: "wear:shades ex:happy",
  Busy: "fx:sweat",
  Hardworking: "wear:headband fx:sweat",
  Chilly: "wear:scarf fx:snow",
  Clumsy: "wear:bandaid ex:dizzy",
  Cozy: "wear:scarf ex:calm",
  Crispy: "c:gold m:specks",
  Dreamy: "ex:dreamy fx:stars",
  Epic: "fx:rays",
  Icy: "c:aqua fx:snow",
  Glorious: "wear:laurel",
  Heroic: "wear:domino ex:brave",
  Honest: "ex:smile",
  Wonderful: "ex:happy fx:sparkles",
  Minty: "c:mint",
  Misty: "c:silver",
  Nervous: "ex:nervous fx:sweat",
  Nocturnal: "ex:surprised fx:moon",
  Optimistic: "ex:happy",
  Patient: "ex:calm",
  Rebel: "wear:headband",
  Spooky: "ex:spooky c:lilac",
  Sticky: "ex:tongue",
  Stubborn: "ex:grumpy",
  Sturdy: "size:1.06",
  Thoughtful: "ex:quiet wear:glasses",
  Tropical: "wear:flower",
  Vibrant: "c:magenta",
  Warm: "wear:scarf",
  Dancing: "fx:notes ex:happy",
  Singing: "ex:open fx:notes",
  Flying: "wear:pilotcap",
  Sporty: "wear:headband=#4F86E0",
  Artistic: "wear:beret",
  Musical: "wear:headphones",
  Retro: "wear:glasses",
  Classic: "wear:bowtie",
  Modern: "wear:cap",
  Famous: "wear:shades fx:sparkles",
  Lost: "fx:question",
  Smiley: "ex:happy",
  Chatty: "ex:open",
  Hasty: "fx:speed fx:sweat",
  Gourmet: "wear:toque",
  Dramatic: "ex:surprised fx:exclaim",
  Fabulous: "wear:bow fx:sparkles",
  Free: "fx:leaf",
  Sour: "ex:sour",
  Salty: "ex:grumpy",
  Sweet: "fx:hearts ex:cute",
  Fiery: "t:flame c:red",
  Arctic: "wear:beanie fx:snow",
  Urban: "wear:cap",
  Confident: "ex:smug",
  Relaxed: "ex:calm",
  Tired: "ex:sleepy",
  Bored: "ex:bored",
  Excited: "ex:excited",
  Surprised: "ex:surprised",
  Confused: "ex:confused fx:question",
  Snoring: "ex:sleepy fx:zzz",
  Sleepwalking: "ex:sleepy wear:sleepcap fx:zzz",
  Barefoot: "ex:happy",
  Infinite: "fx:stars",
  Lone: "ex:quiet",
  Sunny: "fx:sun",
  Snowy: "fx:snow",
  Rainy: "fx:rain",
  Daring: "ex:brave",
  Valiant: "ex:brave",
  Witty: "ex:wink",
  Cheerful: "ex:happy",
  Bubbly: "fx:bubbles",
  Juicy: "m:shine fx:drops",
  Tasty: "ex:tongue",
  Toasty: "fx:steam",
  Frosty: "c:aqua fx:snow",
  Muddy: "m:mud",
  Sassy: "ex:smug",
  Royal: "wear:crown",
  Cyber: "wear:visor",
  Supersonic: "fx:speed",
  Masked: "wear:domino",
  Squishy: "shape:round ex:cute",
  Round: "shape:round",
  Glittery: "m:glitter fx:sparkles",
  Pastel: "style:pastel",
  Silky: "m:shine wear:bow=#BCA4F2",
  Brilliant: "fx:sparkles",
  Celestial: "wear:halo fx:stars",
  Mythic: "fx:rays",
  Enchanted: "fx:sparkles",
  Sneezy: "ex:sneezy",
  Hopeful: "ex:dreamy",
  Nerdy: "wear:glasses",
  Punk: "t:mohawk p:punk=1",
  Groovy: "wear:shades fx:notes",
  Funky: "fx:notes",
  Victorious: "wear:medal",
  Undefeated: "wear:medal",
  Homemade: "m:stitchpatch",
  Creamy: "c:cream",
  Fizzy: "fx:bubbles",
  Caramel: "c:caramel",
  Chocolate: "c:choc",
  Buttery: "c:butter",
  Plaid: "m:plaid",
  Origami: "m:folds",
  Martian: "c:coral a:alien",
  Volcanic: "t:flame",
  Oceanic: "c:blue fx:bubbles",
  Festive: "wear:party",
  Supreme: "wear:crown",
  Ultimate: "fx:rays",
  Whistling: "ex:whistle fx:notes",
  Adventurous: "wear:safari",
  Creative: "wear:beret=#4F86E0",
  Stylish: "wear:shades",
  Wacky: "ex:odd",
  Metallic: "c:silver m:shine",
  Bronze: "c:bronze m:shine",
  Crimson: "c:crimson",
  Emerald: "c:emerald",
  Gray: "c:gray",
  Platinum: "c:platinum m:shine",
  Zippy: "fx:speed",
  Bouncy: "ex:happy",
  Chill: "wear:shades ex:calm",
  Starry: "m:galaxy c:navy",
  Moonlit: "fx:moon",
  Dusty: "m:mud",
  Soggy: "fx:rain",
  Leafy: "t:sprout",
  Spicy: "fx:steam c:red",
  Fruity: "t:leaf",
  Cheesy: "ex:happy",
  Dandy: "wear:tophat wear:mustache",
  Frisky: "ex:tongue",
  Merry: "wear:party ex:happy",
  Velvety: "c:plum",
  Atomic: "fx:atom",
  Hyper: "fx:bolt ex:excited",
  Imperial: "wear:crown",
  Alpine: "wear:beanie=#4F86E0",
  Peaceful: "ex:calm",
  Feathery: "t:crest",
  Robotic: "a:robot x:pixel",
  Mini: "size:.8",
  Jumbo: "size:1.1",
  Yawning: "ex:yawn",
  Thrifty: "ex:smug",
  Punctual: "wear:bowtie",
  Sincere: "ex:smile",
  Woolly: "shape:fluffy",
  Glossy: "m:shine",
};

// Titles: what goes on the head (feminine forms share the masculine's row).
export const TITLE: Record<string, string> = {
  Captain: "wear:captain tout:uniform p:tshirt=navy",
  Doctor: "wear:glasses tout:labcoat p:tshirt=white",
  Professor: "wear:mortarboard wear:glasses tout:suit p:tshirt=brown",
  Agent: "wear:shades tout:suit p:tshirt=black",
  General: "wear:military wear:medal tout:uniform p:tshirt=olive",
  Admiral: "wear:captain wear:medal tout:uniform p:tshirt=navy",
  Sergeant: "wear:military tout:uniform p:tshirt=olive",
  Colonel: "wear:military tout:uniform p:tshirt=olive",
  Major: "wear:military tout:uniform p:tshirt=olive",
  Lieutenant: "wear:military tout:uniform p:tshirt=olive",
  Commander: "wear:captain tout:uniform p:tshirt=navy",
  Mayor: "wear:tophat tout:suit p:tshirt=navy",
  Governor: "wear:tophat wear:tie tout:suit p:tshirt=charcoal",
  President: "wear:tie tout:suit p:tshirt=navy",
  Senator: "wear:tie tout:suit p:tshirt=charcoal",
  Minister: "wear:tie tout:suit p:tshirt=slate",
  Ambassador: "wear:bowtie tout:suit p:tshirt=black",
  Judge: "wear:judgewig tout:robe p:tshirt=black",
  Sheriff: "wear:cowboy wear:badge tout:coat p:tshirt=tan",
  Officer: "wear:military tout:uniform p:tshirt=navy",
  Inspector: "wear:deerstalker tout:coat p:tshirt=tan",
  King: "wear:crown tout:redrobe p:tshirt=crimson",
  Prince: "wear:crown tout:redrobe p:tshirt=blue",
  Emperor: "wear:crown wear:collar tout:redrobe p:tshirt=crimson",
  Duke: "wear:tophat wear:monocle tout:suit p:tshirt=plum",
  Marquis: "wear:tophat tout:suit p:tshirt=plum",
  Count: "wear:collar tout:suit p:tshirt=black",
  Viscount: "wear:tophat tout:suit p:tshirt=plum",
  Baron: "wear:tophat wear:mustache tout:suit p:tshirt=brown",
  Lord: "wear:tophat tout:suit p:tshirt=navy",
  Pharaoh: "wear:nemes tout:toga p:tshirt=white",
  Overlord: "wear:crown=#3E4556 tout:redrobe p:tshirt=black",
  Master: "wear:beard wear:oldbrows tout:kimono p:tshirt=white",
  Sensei: "wear:headband=#FBF9F4 wear:beard tout:kimono p:tshirt=white",
  Elder: "wear:beard wear:oldbrows wear:glasses tout:turtleneck p:tshirt=sand",
  Chief: "wear:hardhat tout:vest p:tshirt=orange",
  Boss: "wear:shades wear:tie tout:suit p:tshirt=black",
  CEO: "wear:tie tout:suit p:tshirt=navy",
  Manager: "wear:tie tout:suit p:tshirt=slate",
  Principal: "wear:mortarboard tout:suit p:tshirt=brown",
  Coach: "wear:cap tout:hoodie p:tshirt=red",
  Champion: "wear:medal wear:laurel tout:tee p:tshirt=gold",
  Hero: "wear:domino tout:tee p:tshirt=red",
  Guardian: "wear:knight tout:armor p:tshirt=silver",
  Tycoon: "wear:tophat wear:monocle tout:suit p:tshirt=black",
  Mister: "wear:mustache tout:suit p:tshirt=brown",
  Uncle: "wear:mustache tout:tee",
  Grandpa:
    "wear:glasses wear:oldbrows wear:mustache=#E9ECF1 tout:turtleneck p:tshirt=sand",
  Papa: "wear:mustache tout:tee",
  Bro: "wear:cap=#E8574D tout:hoodie",
  Baby: "wear:curl tout:onesie p:tshirt=aqua",
  Sir: "wear:knight tout:armor p:tshirt=silver",
  Shogun: "wear:kabuto tout:kimono p:tshirt=navy",
  Dean: "wear:mortarboard tout:suit p:tshirt=brown",
  Chancellor: "wear:mortarboard wear:tie tout:suit p:tshirt=charcoal",
  Cadet: "wear:military tout:uniform p:tshirt=navy",
  Private: "wear:military tout:uniform p:tshirt=olive",
  Marshal: "wear:military wear:medal tout:uniform p:tshirt=navy",
  Archduke: "wear:crown tout:redrobe p:tshirt=crimson",
  Squire: "wear:knight tout:armor p:tshirt=silver",
  Paladin: "wear:knight wear:halo tout:armor p:tshirt=silver",
  Maestro: "wear:beret wear:bowtie tout:suit p:tshirt=black",
  Ace: "wear:pilotcap tout:coat p:tshirt=brown",
  Idol: "wear:headset tout:tee p:tshirt=pink",
  Streamer: "wear:headphones tout:hoodie p:tshirt=purple",
  Senpai: "wear:shades tout:sailor p:tshirt=white",
  Rookie: "wear:bandaid wear:cap tout:tee",
  Buddy: "ex:happy tout:tee",
};
// feminine titles that differ in the drawing
export const TITLE_F: Record<string, string> = {
  King: "wear:crown wear:bow tout:redrobe p:tshirt=crimson",
  Prince: "wear:tiara tout:redrobe p:tshirt=rose",
  Emperor: "wear:crown tout:redrobe p:tshirt=crimson",
  Duke: "wear:tiara tout:redrobe p:tshirt=plum",
  Marquis: "wear:tiara tout:redrobe p:tshirt=lilac",
  Count: "wear:tiara tout:redrobe p:tshirt=purple",
  Viscount: "wear:tiara tout:redrobe p:tshirt=teal",
  Baron: "wear:tiara tout:redrobe p:tshirt=rose",
  Lord: "wear:tiara tout:redrobe p:tshirt=navy",
  Uncle: "wear:bow tout:tee",
  Grandpa: "wear:glasses wear:oldbrows tout:turtleneck p:tshirt=lilac",
  Master: "wear:oldbrows tout:kimono p:tshirt=white",
  Sensei: "wear:headband=#FBF9F4 wear:oldbrows tout:kimono p:tshirt=white",
  Elder: "wear:oldbrows wear:glasses tout:turtleneck p:tshirt=sand",
  Papa: "wear:bow tout:tee",
  Bro: "wear:bow tout:hoodie",
  Sir: "wear:tiara tout:armor p:tshirt=silver",
  Mister: "wear:bow tout:tee",
  Hero: "wear:domino wear:bow tout:tee p:tshirt=red",
  Archduke: "wear:tiara tout:redrobe p:tshirt=crimson",
};

// Legendary names: one exact look each, with a little rays-and-sparkles frame.
export const LEGEND: Record<string, string> = {
  Doge: "Dog",
  Stonks: "blob wear:tie fx:bolt",
  NyanCat: "Cat fx:rainbow",
  PopCat: "Cat ex:surprised",
  HappyHappyCat: "Cat ex:happy fx:notes",
  HuhCat: "Cat ex:confused",
  BananaCat: "Cat c:yellow",
  ChipiChipiChapa: "Cat fx:notes",
  OiiaOiiaCat: "Cat ex:dizzy",
  VibingCat: "Cat ex:calm fx:notes",
  KeyboardCat: "Cat wear:shades fx:notes",
  CeilingCat: "Cat ex:sneaky",
  Longcat: "Cat shape:bean",
  BongoCat: "Cat fx:notes",
  Bingus: "Cat c:pink",
  BigFloppa: "Lynx ex:smug",
  Cheems: "Dog ex:sad",
  Doggo: "Dog ex:happy",
  CaramelMutt: "Dog c:caramel",
  MooDeng: "Hippo ex:fierce",
  PedroRaccoon: "Raccoon fx:notes",
  SadHamster: "Hamster ex:sad",
  TrashPanda: "Raccoon ex:sneaky",
  DangerNoodle: "bean o:forked m:rosettes c:lime/green ex:fierce",
  SeaPancake: "Stingray",
  AbsoluteUnit: "Sheep size:1.12",
  DatBoi: "Frog",
  Trollface: "blob ex:smug",
  Rickroll: "blob fx:notes ex:wink",
  ThisIsFine: "Dog fx:steam ex:calm",
  GalaxyBrain: "blob m:galaxy c:navy fx:stars",
  GigaChad: "blob ex:smug size:1.08",
  Bonk: "Dog wear:bandaid",
  Moai: "Golem ex:serious",
  Skibidi: "blob ex:odd",
  Amogus: "blob wear:visor",
  Kappa: "blob ex:smug",
  Hackerman: "blob wear:visor",
  CakeIsALie: "Cupcake",
  OverNineThousand: "blob fx:bolt ex:fierce",
  FinalAnswer: "blob fx:question",
  MainCharacter: "blob fx:sparkles",
  RageQuit: "blob ex:grumpy fx:steam",
  PressF: "blob ex:sad",
  NullPointer: "Robot",
  Orz: "blob ex:sad",
  PleadingFace: "blob ex:cute",
  SmugFace: "blob ex:smug",
  Rofl: "blob ex:happy",
  TGIF: "blob wear:party",
  DadJoker: "blob wear:mustache ex:wink",
  GifOrJif: "blob ex:confused fx:question",
  BrrBrrPatapim: "Bigfoot",
  TungTungSahur: "Drum",
  Chimpanzini: "Mango",
  Birb: "Chick",
  Snek: "bean o:forked m:rosettes c:lime/green ex:wink",
  Blep: "Cat ex:tongue",
  Boop: "Dog ex:surprised",
  Rawr: "Dinosaur",
  LongBoi: "Goose shape:bean",
  Hampter: "Hamster",
  HamsterDance: "Hamster fx:notes",
  CrabRave: "Crab fx:notes",
  DancingBaby: "blob wear:curl fx:notes",
  NumaNuma: "blob ex:open fx:notes",
  PPAP: "Pineapple",
  BluePen: "blob c:blue",
  ToTheMoon: "Rocket fx:stars",
  Thonk: "blob ex:confused",
  AllYourBase: "UFO",
  DoABarrelRoll: "blob wear:pilotcap",
  ItsATrap: "blob ex:surprised",
  Wololo: "blob wear:wizard",
  Hadouken: "blob wear:headband fx:glow",
  Kamehameha: "blob fx:glow ex:brave",
  ZaWarudo: "blob ex:fierce fx:rays",
  YareYare: "blob ex:bored",
  Nani: "blob ex:surprised fx:exclaim",
  Yatta: "blob ex:excited",
};
