// The Impostor's question bank in local mode: the same first lot as
// supabase/seed/impostor_questions.sql, as the table hands it to the server.
import type { BankQuestion } from "@/game/impostor/questions";

export const LOCAL_QUESTIONS: BankQuestion[] = [
  {
    id: "g-scale-01",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How brave are they?",
      es: "¿Qué tan valiente es?",
      ja: "どれくらい勇敢？",
      pt: "Quão corajoso ele é?",
    },
    options: {
      low: {
        emoji: "😱",
        text: {
          en: "Scaredy-cat",
          es: "Cobarde",
          ja: "臆病",
          pt: "Medroso",
        },
      },
      high: {
        emoji: "🦁",
        text: {
          en: "Fearless",
          es: "Valiente",
          ja: "勇敢",
          pt: "Corajoso",
        },
      },
    },
  },
  {
    id: "g-scale-02",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How dangerous are they?",
      es: "¿Qué tan peligroso es?",
      ja: "どれくらい危険？",
      pt: "Quão perigoso ele é?",
    },
    options: {
      low: {
        emoji: "🐣",
        text: {
          en: "Harmless",
          es: "Inofensivo",
          ja: "無害",
          pt: "Inofensivo",
        },
      },
      high: {
        emoji: "☠️",
        text: {
          en: "Deadly",
          es: "Peligroso",
          ja: "危険",
          pt: "Perigoso",
        },
      },
    },
  },
  {
    id: "g-scale-03",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How smart are they?",
      es: "¿Qué tan inteligente es?",
      ja: "どれくらい頭がいい？",
      pt: "Quão inteligente ele é?",
    },
    options: {
      low: {
        emoji: "🫠",
        text: {
          en: "Airhead",
          es: "En la luna",
          ja: "ぼんやり",
          pt: "Desligado",
        },
      },
      high: {
        emoji: "🧠",
        text: {
          en: "Genius",
          es: "Genio",
          ja: "天才",
          pt: "Gênio",
        },
      },
    },
  },
  {
    id: "g-scale-04",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How funny are they?",
      es: "¿Qué tan gracioso es?",
      ja: "どれくらい面白い？",
      pt: "Quão engraçado ele é?",
    },
    options: {
      low: {
        emoji: "😐",
        text: {
          en: "Serious",
          es: "Serio",
          ja: "真面目",
          pt: "Sério",
        },
      },
      high: {
        emoji: "🤡",
        text: {
          en: "Total clown",
          es: "Payaso",
          ja: "お調子者",
          pt: "Palhaço",
        },
      },
    },
  },
  {
    id: "g-scale-05",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How much do they talk?",
      es: "¿Cuánto habla?",
      ja: "どれくらいおしゃべり？",
      pt: "Quanto ele fala?",
    },
    options: {
      low: {
        emoji: "🤐",
        text: {
          en: "Quiet",
          es: "Callado",
          ja: "無口",
          pt: "Calado",
        },
      },
      high: {
        emoji: "🗣️",
        text: {
          en: "Chatterbox",
          es: "Parlanchín",
          ja: "おしゃべり",
          pt: "Tagarela",
        },
      },
    },
  },
  {
    id: "g-scale-06",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How organized are they?",
      es: "¿Qué tan ordenado es?",
      ja: "どれくらい几帳面？",
      pt: "Quão organizado ele é?",
    },
    options: {
      low: {
        emoji: "🌪️",
        text: {
          en: "Messy",
          es: "Un desastre",
          ja: "散らかし屋",
          pt: "Bagunceiro",
        },
      },
      high: {
        emoji: "📐",
        text: {
          en: "Neat freak",
          es: "Impecable",
          ja: "きっちり",
          pt: "Certinho",
        },
      },
    },
  },
  {
    id: "g-scale-07",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How vain are they?",
      es: "¿Qué tan vanidoso es?",
      ja: "見た目をどれくらい気にする？",
      pt: "Quão vaidoso ele é?",
    },
    options: {
      low: {
        emoji: "🤷",
        text: {
          en: "Doesn't care",
          es: "Le da igual",
          ja: "無頓着",
          pt: "Nem liga",
        },
      },
      high: {
        emoji: "🪞",
        text: {
          en: "Mirror addict",
          es: "Vive en el espejo",
          ja: "鏡が手放せない",
          pt: "Vive no espelho",
        },
      },
    },
  },
  {
    id: "g-scale-08",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How lucky are they?",
      es: "¿Cuánta suerte tiene?",
      ja: "どれくらい運がいい？",
      pt: "Quão sortudo ele é?",
    },
    options: {
      low: {
        emoji: "🐈‍⬛",
        text: {
          en: "Unlucky",
          es: "Cero suerte",
          ja: "不運",
          pt: "Azarado",
        },
      },
      high: {
        emoji: "🍀",
        text: {
          en: "Lucky",
          es: "Mucha suerte",
          ja: "強運",
          pt: "Sortudo",
        },
      },
    },
  },
  {
    id: "g-scale-09",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How far would they get on a reality show?",
      es: "¿Hasta dónde llegaría en un reality?",
      ja: "リアリティ番組でどこまで残れる？",
      pt: "Quão longe ele chegaria num reality show?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "First one out",
          es: "Sale primero",
          ja: "初週で脱落",
          pt: "Sai na 1ª semana",
        },
      },
      high: {
        emoji: "🏆",
        text: {
          en: "Wins it all",
          es: "Gana",
          ja: "優勝",
          pt: "Ganha",
        },
      },
    },
  },
  {
    id: "g-scale-10",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How stressed out are they?",
      es: "¿Cuánto estrés tiene?",
      ja: "普段どれくらいストレスがある？",
      pt: "Quão estressado ele vive?",
    },
    options: {
      low: {
        emoji: "🧘",
        text: {
          en: "Zen",
          es: "Zen",
          ja: "悟りの境地",
          pt: "Zen",
        },
      },
      high: {
        emoji: "🌋",
        text: {
          en: "About to blow",
          es: "Explotando",
          ja: "爆発寸前",
          pt: "Explodindo",
        },
      },
    },
  },
  {
    id: "g-scale-11",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How well would they keep a secret?",
      es: "¿Qué tan bien guardaría un secreto?",
      ja: "秘密をどれくらい守れる？",
      pt: "Quão bem ele guardaria um segredo?",
    },
    options: {
      low: {
        emoji: "📢",
        text: {
          en: "Tells everyone",
          es: "Lo cuenta todo",
          ja: "すぐバラす",
          pt: "Conta pra todo mundo",
        },
      },
      high: {
        emoji: "🤫",
        text: {
          en: "To the grave",
          es: "Hasta la tumba",
          ja: "墓場まで",
          pt: "Leva pro túmulo",
        },
      },
    },
  },
  {
    id: "g-scale-12",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How rich are they?",
      es: "¿Qué tan rico es?",
      ja: "どれくらいお金持ち？",
      pt: "Quão rico ele é?",
    },
    options: {
      low: {
        emoji: "🪙",
        text: {
          en: "Broke",
          es: "Sin un peso",
          ja: "金欠",
          pt: "Duro",
        },
      },
      high: {
        emoji: "💰",
        text: {
          en: "Millionaire",
          es: "Millonario",
          ja: "大富豪",
          pt: "Milionário",
        },
      },
    },
  },
  {
    id: "g-scale-13",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How good are they in a fight?",
      es: "¿Qué tan bien pelea?",
      ja: "ケンカはどれくらい強い？",
      pt: "Quão bom de briga ele é?",
    },
    options: {
      low: {
        emoji: "🏃",
        text: {
          en: "Runs away",
          es: "Sale corriendo",
          ja: "逃げる",
          pt: "Foge",
        },
      },
      high: {
        emoji: "🥊",
        text: {
          en: "Unbeatable",
          es: "Invencible",
          ja: "無敵",
          pt: "Imbatível",
        },
      },
    },
  },
  {
    id: "g-scale-14",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How good a person are they?",
      es: "¿Qué tan buena persona es?",
      ja: "どれくらいいい人？",
      pt: "Quão boa pessoa ele é?",
    },
    options: {
      low: {
        emoji: "😈",
        text: {
          en: "Villain",
          es: "Villano",
          ja: "悪党",
          pt: "Vilão",
        },
      },
      high: {
        emoji: "😇",
        text: {
          en: "Saint",
          es: "Santo",
          ja: "聖人",
          pt: "Santo",
        },
      },
    },
  },
  {
    id: "g-scale-15",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How romantic are they?",
      es: "¿Qué tan romántico es?",
      ja: "どれくらいロマンチック？",
      pt: "Quão romântico ele é?",
    },
    options: {
      low: {
        emoji: "🧊",
        text: {
          en: "Ice cold",
          es: "Frío",
          ja: "冷たい",
          pt: "Frio",
        },
      },
      high: {
        emoji: "💘",
        text: {
          en: "Head over heels",
          es: "Apasionado",
          ja: "情熱的",
          pt: "Apaixonado",
        },
      },
    },
  },
  {
    id: "g-scale-16",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How old do they look?",
      es: "¿Qué edad aparenta?",
      ja: "何歳くらいに見える？",
      pt: "Quão velho ele parece?",
    },
    options: {
      low: {
        emoji: "👶",
        text: {
          en: "Kid",
          es: "Niño",
          ja: "子ども",
          pt: "Criança",
        },
      },
      high: {
        emoji: "🧓",
        text: {
          en: "Ancient",
          es: "Anciano",
          ja: "お年寄り",
          pt: "Ancião",
        },
      },
    },
  },
  {
    id: "g-scale-17",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How physically strong are they?",
      es: "¿Qué tan fuerte es físicamente?",
      ja: "力はどれくらい強い？",
      pt: "Quão forte ele é fisicamente?",
    },
    options: {
      low: {
        emoji: "🪶",
        text: {
          en: "Fragile",
          es: "Frágil",
          ja: "ひ弱",
          pt: "Frágil",
        },
      },
      high: {
        emoji: "⛰️",
        text: {
          en: "Mountain",
          es: "Una montaña",
          ja: "怪力",
          pt: "Montanha",
        },
      },
    },
  },
  {
    id: "g-scale-18",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "fiction",
    spice: 2,
    text: {
      en: "How famous are they in their world?",
      es: "¿Qué tan famoso es en su mundo?",
      ja: "自分の世界でどれくらい有名？",
      pt: "Quão famoso ele é no mundo dele?",
    },
    options: {
      low: {
        emoji: "👤",
        text: {
          en: "Unknown",
          es: "Anónimo",
          ja: "無名",
          pt: "Anônimo",
        },
      },
      high: {
        emoji: "🌟",
        text: {
          en: "Legend",
          es: "Leyenda",
          ja: "伝説",
          pt: "Lenda",
        },
      },
    },
  },
  {
    id: "g-scale-19",
    kind: "scale",
    scope: "general",
    set: null,
    themeId: null,
    audience: "real",
    spice: 1,
    text: {
      en: "How would they do in an action movie?",
      es: "¿Cómo le iría en una película de acción?",
      ja: "アクション映画でどれくらい活躍する？",
      pt: "Quão bem ele se sairia num filme de ação?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Dies first",
          es: "Muere al principio",
          ja: "最初にやられる",
          pt: "Morre no começo",
        },
      },
      high: {
        emoji: "💥",
        text: {
          en: "Saves the day",
          es: "Salva el día",
          ja: "世界を救う",
          pt: "Salva o dia",
        },
      },
    },
  },
  {
    id: "g-color-01",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What color would they be?",
      es: "Si fuera un color, ¿cuál sería?",
      ja: "色にたとえると何色？",
      pt: "Se ele fosse uma cor?",
    },
    options: null,
  },
  {
    id: "g-color-02",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What color would they paint their room?",
      es: "¿De qué color pintaría su cuarto?",
      ja: "部屋の壁を何色に塗る？",
      pt: "De que cor ele pintaria o quarto?",
    },
    options: null,
  },
  {
    id: "g-color-03",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What color matches their mood?",
      es: "¿Qué color combina con su humor?",
      ja: "気分にぴったりの色は？",
      pt: "Que cor combina com o humor dele?",
    },
    options: null,
  },
  {
    id: "g-color-04",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What color would their car be?",
      es: "Si tuviera un auto, ¿de qué color sería?",
      ja: "車を持つなら何色？",
      pt: "Se ele tivesse um carro, de que cor seria?",
    },
    options: null,
  },
  {
    id: "g-color-05",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What color do they hate?",
      es: "¿Qué color odia?",
      ja: "嫌いな色は？",
      pt: "Que cor ele odeia?",
    },
    options: null,
  },
  {
    id: "g-color-06",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What color would their backpack be?",
      es: "¿De qué color sería su mochila?",
      ja: "リュックは何色？",
      pt: "De que cor seria a mochila dele?",
    },
    options: null,
  },
  {
    id: "g-color-07",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What color is their team's flag?",
      es: "¿De qué color sería la bandera de su equipo?",
      ja: "チームの旗は何色？",
      pt: "De que cor seria a bandeira do time dele?",
    },
    options: null,
  },
  {
    id: "g-color-08",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What color is the place they live?",
      es: "¿De qué color es el lugar donde vive?",
      ja: "住んでいる場所は何色？",
      pt: "De que cor é o lugar onde ele vive?",
    },
    options: null,
  },
  {
    id: "g-color-09",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 3,
    text: {
      en: "What color do they wear the most?",
      es: "¿De qué color se viste más?",
      ja: "服でいちばんよく着る色は？",
      pt: "Que cor ele mais usa na roupa?",
    },
    options: null,
  },
  {
    id: "g-color-10",
    kind: "color",
    scope: "general",
    set: null,
    themeId: null,
    audience: "real",
    spice: 2,
    text: {
      en: "What color would they be as a cartoon?",
      es: "Como dibujo animado, ¿de qué color sería?",
      ja: "アニメになったら何色？",
      pt: "Se ele virasse desenho, de que cor seria?",
    },
    options: null,
  },
  {
    id: "g-emoji-01",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Which emoji would they send the most?",
      es: "¿Qué emoji mandaría más?",
      ja: "いちばんよく送る絵文字は？",
      pt: "Que emoji ele mais mandaria?",
    },
    options: {
      palette: "general",
    },
  },
  {
    id: "g-emoji-02",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Which emoji sums up their day?",
      es: "¿Qué emoji resume su día?",
      ja: "一日を絵文字で表すと？",
      pt: "Que emoji resume o dia dele?",
    },
    options: {
      palette: "general",
    },
  },
  {
    id: "g-emoji-03",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Which emoji would they never send?",
      es: "¿Qué emoji nunca mandaría?",
      ja: "絶対に送らない絵文字は？",
      pt: "Que emoji ele nunca mandaria?",
    },
    options: {
      palette: "general",
    },
  },
  {
    id: "g-emoji-04",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How would they react to bad news?",
      es: "¿Cómo reaccionaría a una mala noticia?",
      ja: "悪い知らせを聞いたらどんな顔？",
      pt: "Como ele reagiria a uma má notícia?",
    },
    options: {
      palette: "faces",
    },
  },
  {
    id: "g-emoji-05",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What animal would their pet be?",
      es: "¿Qué animal sería su mascota?",
      ja: "ペットにするならどの動物？",
      pt: "Que bicho seria o pet dele?",
    },
    options: {
      palette: "animals",
    },
  },
  {
    id: "g-emoji-06",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What weather suits them?",
      es: "¿Qué clima combina con su vibra?",
      ja: "似合う天気は？",
      pt: "Que clima combina com ele?",
    },
    options: {
      palette: "weather",
    },
  },
  {
    id: "g-emoji-07",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Where would they go on vacation?",
      es: "¿Dónde pasaría las vacaciones?",
      ja: "休暇はどこで過ごす？",
      pt: "Onde ele passaria as férias?",
    },
    options: {
      palette: "places",
    },
  },
  {
    id: "g-emoji-08",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What would they take to a desert island?",
      es: "¿Qué objeto llevaría a una isla desierta?",
      ja: "無人島に持っていく物は？",
      pt: "Que objeto ele levaria pra uma ilha deserta?",
    },
    options: {
      palette: "objects",
    },
  },
  {
    id: "g-emoji-09",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What sport would they watch?",
      es: "¿Qué deporte vería?",
      ja: "観るならどのスポーツ？",
      pt: "Que esporte ele assistiria?",
    },
    options: {
      palette: "sports",
    },
  },
  {
    id: "g-emoji-10",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What's their favorite food?",
      es: "¿Cuál es su comida favorita?",
      ja: "好きな食べ物は？",
      pt: "Qual a comida favorita dele?",
    },
    options: {
      palette: "foods",
    },
  },
  {
    id: "g-emoji-11",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What's their biggest fear?",
      es: "¿Cuál es su mayor miedo?",
      ja: "いちばん怖いものは？",
      pt: "Qual o maior medo dele?",
    },
    options: {
      palette: "general",
    },
  },
  {
    id: "g-emoji-12",
    kind: "emoji",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Which emoji would be their profile pic?",
      es: "¿Qué emoji sería su foto de perfil?",
      ja: "アイコンにしそうな絵文字は？",
      pt: "Que emoji seria a foto de perfil dele?",
    },
    options: {
      palette: "general",
    },
  },
  {
    id: "g-pick-01",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Beach or mountains?",
      es: "¿Playa o montaña?",
      ja: "海派？山派？",
      pt: "Praia ou montanha?",
    },
    options: {
      choices: [
        {
          emoji: "🏖️",
          text: {
            en: "Beach",
            es: "Playa",
            ja: "海",
            pt: "Praia",
          },
        },
        {
          emoji: "🏔️",
          text: {
            en: "Mountains",
            es: "Montaña",
            ja: "山",
            pt: "Montanha",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-02",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Dog or cat?",
      es: "¿Perro o gato?",
      ja: "犬派？猫派？",
      pt: "Cachorro ou gato?",
    },
    options: {
      choices: [
        {
          emoji: "🐶",
          text: {
            en: "Dog",
            es: "Perro",
            ja: "犬",
            pt: "Cachorro",
          },
        },
        {
          emoji: "🐱",
          text: {
            en: "Cat",
            es: "Gato",
            ja: "猫",
            pt: "Gato",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-03",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Day or night?",
      es: "¿Día o noche?",
      ja: "昼派？夜派？",
      pt: "Dia ou noite?",
    },
    options: {
      choices: [
        {
          emoji: "☀️",
          text: {
            en: "Day",
            es: "Día",
            ja: "昼",
            pt: "Dia",
          },
        },
        {
          emoji: "🌙",
          text: {
            en: "Night",
            es: "Noche",
            ja: "夜",
            pt: "Noite",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-04",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Sweet or salty?",
      es: "¿Dulce o salado?",
      ja: "甘い派？しょっぱい派？",
      pt: "Doce ou salgado?",
    },
    options: {
      choices: [
        {
          emoji: "🍰",
          text: {
            en: "Sweet",
            es: "Dulce",
            ja: "甘い",
            pt: "Doce",
          },
        },
        {
          emoji: "🍟",
          text: {
            en: "Salty",
            es: "Salado",
            ja: "しょっぱい",
            pt: "Salgado",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-05",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "City or countryside?",
      es: "¿Ciudad o campo?",
      ja: "都会派？田舎派？",
      pt: "Cidade ou campo?",
    },
    options: {
      choices: [
        {
          emoji: "🏙️",
          text: {
            en: "City",
            es: "Ciudad",
            ja: "都会",
            pt: "Cidade",
          },
        },
        {
          emoji: "🌾",
          text: {
            en: "Countryside",
            es: "Campo",
            ja: "田舎",
            pt: "Campo",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-06",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Party or couch?",
      es: "¿Fiesta o sofá?",
      ja: "パーティー派？おうち派？",
      pt: "Festa ou sofá?",
    },
    options: {
      choices: [
        {
          emoji: "🎉",
          text: {
            en: "Party",
            es: "Fiesta",
            ja: "パーティー",
            pt: "Festa",
          },
        },
        {
          emoji: "🛋️",
          text: {
            en: "Couch",
            es: "Sofá",
            ja: "おうち",
            pt: "Sofá",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-07",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Coffee or tea?",
      es: "¿Café o té?",
      ja: "コーヒー派？お茶派？",
      pt: "Café ou chá?",
    },
    options: {
      choices: [
        {
          emoji: "☕",
          text: {
            en: "Coffee",
            es: "Café",
            ja: "コーヒー",
            pt: "Café",
          },
        },
        {
          emoji: "🍵",
          text: {
            en: "Tea",
            es: "Té",
            ja: "お茶",
            pt: "Chá",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-08",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Hot or cold?",
      es: "¿Calor o frío?",
      ja: "暑いのと寒いの、どっち派？",
      pt: "Calor ou frio?",
    },
    options: {
      choices: [
        {
          emoji: "🔥",
          text: {
            en: "Hot",
            es: "Calor",
            ja: "暑い",
            pt: "Calor",
          },
        },
        {
          emoji: "❄️",
          text: {
            en: "Cold",
            es: "Frío",
            ja: "寒い",
            pt: "Frio",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-09",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Early bird or sleeps in?",
      es: "¿Madruga o duerme hasta tarde?",
      ja: "早起き派？寝坊派？",
      pt: "Acorda cedo ou dorme até tarde?",
    },
    options: {
      choices: [
        {
          emoji: "🐓",
          text: {
            en: "Early bird",
            es: "Temprano",
            ja: "早起き",
            pt: "Cedo",
          },
        },
        {
          emoji: "😴",
          text: {
            en: "Sleeps in",
            es: "Tarde",
            ja: "寝坊",
            pt: "Tarde",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-10",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Spender or saver?",
      es: "¿Gasta todo o ahorra?",
      ja: "お金は使い切る？貯める？",
      pt: "Gasta tudo ou guarda?",
    },
    options: {
      choices: [
        {
          emoji: "💸",
          text: {
            en: "Spender",
            es: "Gasta",
            ja: "使い切る",
            pt: "Gasta",
          },
        },
        {
          emoji: "🐷",
          text: {
            en: "Saver",
            es: "Ahorra",
            ja: "貯める",
            pt: "Guarda",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-11",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Leader or follower?",
      es: "¿Lidera o sigue?",
      ja: "引っぱる？ついていく？",
      pt: "Lidera ou segue?",
    },
    options: {
      choices: [
        {
          emoji: "👑",
          text: {
            en: "Leader",
            es: "Lidera",
            ja: "引っぱる",
            pt: "Lidera",
          },
        },
        {
          emoji: "🐾",
          text: {
            en: "Follower",
            es: "Sigue",
            ja: "ついていく",
            pt: "Segue",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-12",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Plans ahead or wings it?",
      es: "¿Planea o improvisa?",
      ja: "計画派？アドリブ派？",
      pt: "Planeja ou improvisa?",
    },
    options: {
      choices: [
        {
          emoji: "📋",
          text: {
            en: "Plans ahead",
            es: "Planea",
            ja: "計画",
            pt: "Planeja",
          },
        },
        {
          emoji: "🎲",
          text: {
            en: "Wings it",
            es: "Improvisa",
            ja: "アドリブ",
            pt: "Improvisa",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-13",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Solo or with a group?",
      es: "¿En solitario o en grupo?",
      ja: "ひとり派？みんな派？",
      pt: "Sozinho ou em grupo?",
    },
    options: {
      choices: [
        {
          emoji: "🧍",
          text: {
            en: "Solo",
            es: "En solitario",
            ja: "ひとり",
            pt: "Sozinho",
          },
        },
        {
          emoji: "👯",
          text: {
            en: "With a group",
            es: "En grupo",
            ja: "みんなで",
            pt: "Em grupo",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-14",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Fight or flight?",
      es: "¿Pelea o huye?",
      ja: "戦う？逃げる？",
      pt: "Luta ou foge?",
    },
    options: {
      choices: [
        {
          emoji: "⚔️",
          text: {
            en: "Fight",
            es: "Pelea",
            ja: "戦う",
            pt: "Luta",
          },
        },
        {
          emoji: "🏃",
          text: {
            en: "Flight",
            es: "Huye",
            ja: "逃げる",
            pt: "Foge",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-15",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Good liar or bad liar?",
      es: "¿Miente bien o miente mal?",
      ja: "ウソは上手？下手？",
      pt: "Mente bem ou mente mal?",
    },
    options: {
      choices: [
        {
          emoji: "😇",
          text: {
            en: "Bad liar",
            es: "Miente mal",
            ja: "下手",
            pt: "Mente mal",
          },
        },
        {
          emoji: "😏",
          text: {
            en: "Good liar",
            es: "Miente bien",
            ja: "上手",
            pt: "Mente bem",
          },
        },
      ],
    },
  },
  {
    id: "g-pick-16",
    kind: "pick",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Says sorry or never admits it?",
      es: "¿Pide perdón o nunca lo admite?",
      ja: "謝る？絶対に認めない？",
      pt: "Pede desculpa ou nunca admite?",
    },
    options: {
      choices: [
        {
          emoji: "🙏",
          text: {
            en: "Says sorry",
            es: "Pide perdón",
            ja: "謝る",
            pt: "Pede desculpa",
          },
        },
        {
          emoji: "😤",
          text: {
            en: "Never admits it",
            es: "Nunca lo admite",
            ja: "認めない",
            pt: "Nunca admite",
          },
        },
      ],
    },
  },
  {
    id: "g-word-01",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "A food that suits them",
      es: "Una comida que combine con su estilo",
      ja: "似合う食べ物をひとつ",
      pt: "Uma comida que combina com ele",
    },
    options: null,
  },
  {
    id: "g-word-02",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "A place they'd be right now",
      es: "Un lugar donde estaría ahora mismo",
      ja: "今どこにいそう？",
      pt: "Um lugar onde ele estaria agora",
    },
    options: null,
  },
  {
    id: "g-word-03",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What music would they listen to?",
      es: "¿Qué género musical escucharía?",
      ja: "どんな音楽を聴く？",
      pt: "Que estilo de música ele ouviria?",
    },
    options: null,
  },
  {
    id: "g-word-04",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What sport would they play?",
      es: "¿Qué deporte practicaría?",
      ja: "やるならどのスポーツ？",
      pt: "Que esporte ele praticaria?",
    },
    options: null,
  },
  {
    id: "g-word-05",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What would they do on a Sunday?",
      es: "¿Qué haría un domingo?",
      ja: "日曜日は何してる？",
      pt: "O que ele faria num domingo?",
    },
    options: null,
  },
  {
    id: "g-word-06",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What do they complain about at restaurants?",
      es: "¿De qué se quejaría en un restaurante?",
      ja: "レストランで何に文句を言う？",
      pt: "Do que ele reclamaria num restaurante?",
    },
    options: null,
  },
  {
    id: "g-word-07",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "A nickname you'd give them",
      es: "Un apodo que le pondrías",
      ja: "あだ名をつけるなら？",
      pt: "Um apelido que você daria a ele",
    },
    options: null,
  },
  {
    id: "g-word-08",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "A gift they'd love to get",
      es: "Un regalo que le encantaría recibir",
      ja: "もらって喜ぶプレゼントは？",
      pt: "Um presente que ele adoraria ganhar",
    },
    options: null,
  },
  {
    id: "g-word-09",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "One word that sums them up",
      es: "En una palabra, ¿cómo es?",
      ja: "ひと言で表すと？",
      pt: "Uma palavra que define ele",
    },
    options: null,
  },
  {
    id: "g-word-10",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What's their Wi-Fi password?",
      es: "¿Cuál sería la contraseña de su Wi-Fi?",
      ja: "Wi-Fiのパスワードは？",
      pt: "Qual seria a senha do Wi-Fi dele?",
    },
    options: null,
  },
  {
    id: "g-word-11",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "fiction",
    spice: 2,
    text: {
      en: "What job would they have in our world?",
      es: "¿Qué trabajo tendría en nuestro mundo?",
      ja: "私たちの世界ならどんな仕事？",
      pt: "Que emprego ele teria no nosso mundo?",
    },
    options: null,
  },
  {
    id: "g-word-12",
    kind: "word",
    scope: "general",
    set: null,
    themeId: null,
    audience: "all",
    spice: 3,
    text: {
      en: "Something they never put down",
      es: "Un objeto que nunca suelta",
      ja: "いつも手放さない物は？",
      pt: "Um objeto que ele nunca larga",
    },
    options: null,
  },
  {
    id: "s-anime-01",
    kind: "scale",
    scope: "set",
    set: "anime",
    themeId: null,
    audience: "fiction",
    spice: 2,
    text: {
      en: "How strong is their strongest attack?",
      es: "¿Qué tan fuerte es su mejor golpe?",
      ja: "必殺技の威力はどれくらい？",
      pt: "Quão forte é o golpe mais forte dele?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Wimpy",
          es: "Una caricia",
          ja: "へなちょこ",
          pt: "Fraquinho",
        },
      },
      high: {
        emoji: "💥",
        text: {
          en: "Levels mountains",
          es: "Destruye montañas",
          ja: "山をも砕く",
          pt: "Destrói montanhas",
        },
      },
    },
  },
  {
    id: "s-anime-02",
    kind: "pick",
    scope: "set",
    set: "anime",
    themeId: null,
    audience: "fiction",
    spice: 2,
    text: {
      en: "Do they shout their attack's name?",
      es: "¿Grita el nombre de su ataque?",
      ja: "技名を叫ぶ？",
      pt: "Grita o nome do golpe?",
    },
    options: {
      choices: [
        {
          emoji: "📣",
          text: {
            en: "Always",
            es: "Siempre",
            ja: "必ず叫ぶ",
            pt: "Sempre",
          },
        },
        {
          emoji: "🤫",
          text: {
            en: "Never",
            es: "Nunca",
            ja: "叫ばない",
            pt: "Nunca",
          },
        },
      ],
    },
  },
  {
    id: "s-anime-03",
    kind: "word",
    scope: "set",
    set: "anime",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What would they eat at a festival?",
      es: "¿Qué comería en un festival?",
      ja: "お祭りで何を食べる？",
      pt: "Que comida ele comeria num festival?",
    },
    options: null,
  },
  {
    id: "s-cartoons-01",
    kind: "scale",
    scope: "set",
    set: "cartoons",
    themeId: null,
    audience: "fiction",
    spice: 1,
    text: {
      en: "How often do they get hurt and bounce back?",
      es: "¿Cada cuánto se lastima y queda como si nada?",
      ja: "ボロボロから復活した回数は？",
      pt: "Quantas vezes ele já se machucou e voltou inteiro?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Never",
          es: "Nunca",
          ja: "一度もない",
          pt: "Nenhuma",
        },
      },
      high: {
        emoji: "🤕",
        text: {
          en: "Every week",
          es: "Cada semana",
          ja: "毎週",
          pt: "Toda semana",
        },
      },
    },
  },
  {
    id: "s-cartoons-02",
    kind: "word",
    scope: "set",
    set: "cartoons",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What sound do they make?",
      es: "¿Qué ruido hace?",
      ja: "どんな効果音が似合う？",
      pt: "Que barulho ele faz?",
    },
    options: null,
  },
  {
    id: "s-cartoons-03",
    kind: "pick",
    scope: "set",
    set: "cartoons",
    themeId: null,
    audience: "fiction",
    spice: 1,
    text: {
      en: "On TV in the morning or afternoon?",
      es: "¿Su programa sale de mañana o de tarde?",
      ja: "放送は朝？夕方？",
      pt: "Passa de manhã ou à tarde na TV?",
    },
    options: {
      choices: [
        {
          emoji: "🌅",
          text: {
            en: "Morning",
            es: "Mañana",
            ja: "朝",
            pt: "Manhã",
          },
        },
        {
          emoji: "🌇",
          text: {
            en: "Afternoon",
            es: "Tarde",
            ja: "夕方",
            pt: "Tarde",
          },
        },
      ],
    },
  },
  {
    id: "s-screen-01",
    kind: "scale",
    scope: "set",
    set: "screen",
    themeId: null,
    audience: "fiction",
    spice: 1,
    text: {
      en: "How many sequels do they deserve?",
      es: "¿Cuántas secuelas merece?",
      ja: "続編は何本作るべき？",
      pt: "Quantas continuações ele merece?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "None",
          es: "Ninguna",
          ja: "ゼロ",
          pt: "Nenhuma",
        },
      },
      high: {
        emoji: "🎬",
        text: {
          en: "Ten",
          es: "Diez",
          ja: "10本",
          pt: "Dez",
        },
      },
    },
  },
  {
    id: "s-screen-02",
    kind: "pick",
    scope: "set",
    set: "screen",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What's their entrance music?",
      es: "¿Qué música suena cuando aparece?",
      ja: "登場シーンのBGMは？",
      pt: "Que trilha toca quando ele entra?",
    },
    options: {
      choices: [
        {
          emoji: "🎻",
          text: {
            en: "Orchestra",
            es: "Orquesta",
            ja: "オーケストラ",
            pt: "Orquestra",
          },
        },
        {
          emoji: "🎸",
          text: {
            en: "Rock",
            es: "Rock",
            ja: "ロック",
            pt: "Rock",
          },
        },
      ],
    },
  },
  {
    id: "s-screen-03",
    kind: "pick",
    scope: "set",
    set: "screen",
    themeId: null,
    audience: "fiction",
    spice: 3,
    text: {
      en: "Do they survive the movie?",
      es: "¿Sobrevive hasta el final de la película?",
      ja: "映画の最後まで生き残る？",
      pt: "Chega vivo ao fim do filme?",
    },
    options: {
      choices: [
        {
          emoji: null,
          text: {
            en: "Makes it",
            es: "Sobrevive",
            ja: "生き残る",
            pt: "Chega",
          },
        },
        {
          emoji: null,
          text: {
            en: "Doesn't make it",
            es: "No sobrevive",
            ja: "やられる",
            pt: "Não chega",
          },
        },
      ],
    },
  },
  {
    id: "s-games-01",
    kind: "scale",
    scope: "set",
    set: "games",
    themeId: null,
    audience: "fiction",
    spice: 1,
    text: {
      en: "How many lives would they have?",
      es: "¿Cuántas vidas tendría?",
      ja: "残機はいくつ？",
      pt: "Quantas vidas ele teria?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "One",
          es: "Una",
          ja: "1機",
          pt: "Uma",
        },
      },
      high: {
        emoji: "♾️",
        text: {
          en: "Infinite",
          es: "Infinitas",
          ja: "無限",
          pt: "Infinitas",
        },
      },
    },
  },
  {
    id: "s-games-02",
    kind: "pick",
    scope: "set",
    set: "games",
    themeId: null,
    audience: "fiction",
    spice: 2,
    text: {
      en: "Hero or final boss?",
      es: "¿Héroe o jefe final?",
      ja: "ヒーロー？ボスキャラ？",
      pt: "Herói ou chefão?",
    },
    options: {
      choices: [
        {
          emoji: "🦸",
          text: {
            en: "Hero",
            es: "Héroe",
            ja: "ヒーロー",
            pt: "Herói",
          },
        },
        {
          emoji: "👹",
          text: {
            en: "Final boss",
            es: "Jefe final",
            ja: "ボスキャラ",
            pt: "Chefão",
          },
        },
      ],
    },
  },
  {
    id: "s-games-03",
    kind: "emoji",
    scope: "set",
    set: "games",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What item would they grab first?",
      es: "¿Qué ítem recogería primero?",
      ja: "最初に拾うアイテムは？",
      pt: "Que item ele pegaria primeiro?",
    },
    options: {
      palette: "objects",
    },
  },
  {
    id: "s-books-01",
    kind: "pick",
    scope: "set",
    set: "books",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Thin book or doorstopper?",
      es: "¿Libro cortito o mamotreto?",
      ja: "物語にしたら短編？大長編？",
      pt: "Livro fino ou calhamaço?",
    },
    options: {
      choices: [
        {
          emoji: "📄",
          text: {
            en: "Thin",
            es: "Cortito",
            ja: "短編",
            pt: "Fino",
          },
        },
        {
          emoji: "📚",
          text: {
            en: "Doorstopper",
            es: "Mamotreto",
            ja: "大長編",
            pt: "Calhamaço",
          },
        },
      ],
    },
  },
  {
    id: "s-books-02",
    kind: "scale",
    scope: "set",
    set: "books",
    themeId: null,
    audience: "fiction",
    spice: 2,
    text: {
      en: "How happy is their ending?",
      es: "¿Qué tan feliz es su final?",
      ja: "結末はどれくらいハッピー？",
      pt: "Quão feliz é o final dele?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Tragedy",
          es: "Tragedia",
          ja: "悲劇",
          pt: "Tragédia",
        },
      },
      high: {
        emoji: null,
        text: {
          en: "Happily ever after",
          es: "Felices para siempre",
          ja: "ハッピーエンド",
          pt: "Felizes para sempre",
        },
      },
    },
  },
  {
    id: "s-books-03",
    kind: "word",
    scope: "set",
    set: "books",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What book genre would they write?",
      es: "¿Qué género de libro escribiría?",
      ja: "本を書くならどのジャンル？",
      pt: "Que gênero de livro ele escreveria?",
    },
    options: null,
  },
  {
    id: "s-heroes-01",
    kind: "scale",
    scope: "set",
    set: "heroes",
    themeId: null,
    audience: "fiction",
    spice: 2,
    text: {
      en: "How many people do they save a day?",
      es: "¿A cuánta gente salva por día?",
      ja: "1日に何人救う？",
      pt: "Quanta gente ele salva por dia?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Nobody",
          es: "Nadie",
          ja: "ゼロ",
          pt: "Ninguém",
        },
      },
      high: {
        emoji: "🏙️",
        text: {
          en: "A whole city",
          es: "Una ciudad",
          ja: "街まるごと",
          pt: "Uma cidade",
        },
      },
    },
  },
  {
    id: "s-heroes-02",
    kind: "emoji",
    scope: "set",
    set: "heroes",
    themeId: null,
    audience: "fiction",
    spice: 2,
    text: {
      en: "What's their weak spot?",
      es: "¿Cuál es su punto débil?",
      ja: "弱点は？",
      pt: "Qual o ponto fraco dele?",
    },
    options: {
      palette: "general",
    },
  },
  {
    id: "s-heroes-03",
    kind: "pick",
    scope: "set",
    set: "heroes",
    themeId: null,
    audience: "fiction",
    spice: 3,
    text: {
      en: "Did they start out good or evil?",
      es: "¿Empieza del lado del bien o del mal?",
      ja: "はじめは正義側？悪側？",
      pt: "Começa do bem ou do mal?",
    },
    options: {
      choices: [
        {
          emoji: "😇",
          text: {
            en: "Good",
            es: "Del bien",
            ja: "正義",
            pt: "Do bem",
          },
        },
        {
          emoji: "😈",
          text: {
            en: "Evil",
            es: "Del mal",
            ja: "悪",
            pt: "Do mal",
          },
        },
      ],
    },
  },
  {
    id: "s-powers-01",
    kind: "scale",
    scope: "set",
    set: "powers",
    themeId: null,
    audience: "fiction",
    spice: 1,
    text: {
      en: "How useful is their power day to day?",
      es: "¿Qué tan útil es su poder en el día a día?",
      ja: "その能力、日常でどれくらい役立つ？",
      pt: "Quão útil é o poder dele no dia a dia?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Useless",
          es: "Inútil",
          ja: "役立たず",
          pt: "Inútil",
        },
      },
      high: {
        emoji: null,
        text: {
          en: "Essential",
          es: "Esencial",
          ja: "欠かせない",
          pt: "Essencial",
        },
      },
    },
  },
  {
    id: "s-powers-02",
    kind: "emoji",
    scope: "set",
    set: "powers",
    themeId: null,
    audience: "fiction",
    spice: 3,
    text: {
      en: "Which emoji is their power?",
      es: "¿Qué emoji representa su poder?",
      ja: "能力を絵文字にすると？",
      pt: "Que emoji é o poder dele?",
    },
    options: {
      palette: "general",
    },
  },
  {
    id: "s-powers-03",
    kind: "pick",
    scope: "set",
    set: "powers",
    themeId: null,
    audience: "fiction",
    spice: 2,
    text: {
      en: "Born with their power or got it later?",
      es: "¿Nació con el poder o lo adquirió?",
      ja: "能力は生まれつき？後から？",
      pt: "Nasceu com o poder ou ganhou?",
    },
    options: {
      choices: [
        {
          emoji: "🍼",
          text: {
            en: "Born with it",
            es: "Nació así",
            ja: "生まれつき",
            pt: "Nasceu",
          },
        },
        {
          emoji: "🎁",
          text: {
            en: "Got it later",
            es: "Lo adquirió",
            ja: "後から",
            pt: "Ganhou",
          },
        },
      ],
    },
  },
  {
    id: "s-myths-01",
    kind: "scale",
    scope: "set",
    set: "myths",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How old are they?",
      es: "¿Qué tan antiguo es?",
      ja: "どれくらい長く生きてる？",
      pt: "Quão velho ele é?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Newborn",
          es: "Recién nacido",
          ja: "生まれたて",
          pt: "Recém-nascido",
        },
      },
      high: {
        emoji: "⏳",
        text: {
          en: "Eternal",
          es: "Eterno",
          ja: "永遠",
          pt: "Eterno",
        },
      },
    },
  },
  {
    id: "s-myths-02",
    kind: "scale",
    scope: "set",
    set: "myths",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How many people believe in them?",
      es: "¿Cuánta gente cree en su existencia?",
      ja: "信じている人はどれくらい？",
      pt: "Quanta gente acredita nele?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Nobody",
          es: "Nadie",
          ja: "ゼロ",
          pt: "Ninguém",
        },
      },
      high: {
        emoji: null,
        text: {
          en: "Millions",
          es: "Millones",
          ja: "何百万人",
          pt: "Milhões",
        },
      },
    },
  },
  {
    id: "s-myths-03",
    kind: "emoji",
    scope: "set",
    set: "myths",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Where do they live?",
      es: "¿Dónde vive?",
      ja: "どこに住んでいる？",
      pt: "Onde ele mora?",
    },
    options: {
      palette: "places",
    },
  },
  {
    id: "s-scifi-01",
    kind: "scale",
    scope: "set",
    set: "scifi",
    themeId: null,
    audience: "fiction",
    spice: 1,
    text: {
      en: "How far from home are they?",
      es: "¿Qué tan lejos de casa está?",
      ja: "故郷からどれくらい遠くにいる？",
      pt: "Quão longe de casa ele está?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Around the corner",
          es: "A la vuelta",
          ja: "すぐそこ",
          pt: "Na esquina",
        },
      },
      high: {
        emoji: "🌌",
        text: {
          en: "Another galaxy",
          es: "Otra galaxia",
          ja: "別の銀河",
          pt: "Outra galáxia",
        },
      },
    },
  },
  {
    id: "s-scifi-02",
    kind: "pick",
    scope: "set",
    set: "scifi",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Do they trust robots?",
      es: "¿Confía en los robots?",
      ja: "ロボットを信用する？",
      pt: "Confia em robôs?",
    },
    options: {
      choices: [
        {
          emoji: "🤖",
          text: {
            en: "Trusts them",
            es: "Confía",
            ja: "信用する",
            pt: "Confia",
          },
        },
        {
          emoji: "🙅",
          text: {
            en: "No way",
            es: "Desconfía",
            ja: "疑う",
            pt: "Desconfia",
          },
        },
      ],
    },
  },
  {
    id: "s-scifi-03",
    kind: "word",
    scope: "set",
    set: "scifi",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What planet would they visit?",
      es: "¿Qué planeta visitaría?",
      ja: "行くならどの惑星？",
      pt: "Que planeta ele visitaria?",
    },
    options: null,
  },
  {
    id: "s-warriors-01",
    kind: "scale",
    scope: "set",
    set: "warriors",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How many weapons do they carry?",
      es: "¿Cuántas armas lleva encima?",
      ja: "武器をいくつ持ってる？",
      pt: "Quantas armas ele carrega?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "None",
          es: "Ninguna",
          ja: "丸腰",
          pt: "Nenhuma",
        },
      },
      high: {
        emoji: "🗡️",
        text: {
          en: "Whole arsenal",
          es: "Un arsenal",
          ja: "武器庫",
          pt: "Arsenal",
        },
      },
    },
  },
  {
    id: "s-warriors-02",
    kind: "pick",
    scope: "set",
    set: "warriors",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Do they fight by day or by night?",
      es: "¿Pelea de día o de noche?",
      ja: "戦うのは昼？夜？",
      pt: "Luta de dia ou de noite?",
    },
    options: {
      choices: [
        {
          emoji: "☀️",
          text: {
            en: "By day",
            es: "De día",
            ja: "昼",
            pt: "De dia",
          },
        },
        {
          emoji: "🌙",
          text: {
            en: "By night",
            es: "De noche",
            ja: "夜",
            pt: "De noite",
          },
        },
      ],
    },
  },
  {
    id: "s-warriors-03",
    kind: "pick",
    scope: "set",
    set: "warriors",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Honor or victory?",
      es: "¿Honor o victoria?",
      ja: "名誉？勝利？",
      pt: "Honra ou vitória?",
    },
    options: {
      choices: [
        {
          emoji: "🎖️",
          text: {
            en: "Honor",
            es: "Honor",
            ja: "名誉",
            pt: "Honra",
          },
        },
        {
          emoji: "🏆",
          text: {
            en: "Victory",
            es: "Victoria",
            ja: "勝利",
            pt: "Vitória",
          },
        },
      ],
    },
  },
  {
    id: "s-animals-01",
    kind: "scale",
    scope: "set",
    set: "animals",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How cute are they?",
      es: "¿Qué tan adorable es?",
      ja: "どれくらいかわいい？",
      pt: "Quão fofo ele é?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Scary",
          es: "Da miedo",
          ja: "怖い",
          pt: "Assustador",
        },
      },
      high: {
        emoji: "🥹",
        text: {
          en: "Super cute",
          es: "Pura ternura",
          ja: "超かわいい",
          pt: "Fofíssimo",
        },
      },
    },
  },
  {
    id: "s-animals-02",
    kind: "pick",
    scope: "set",
    set: "animals",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Wild or domestic?",
      es: "¿Salvaje o doméstico?",
      ja: "野生？ペット？",
      pt: "Selvagem ou de casa?",
    },
    options: {
      choices: [
        {
          emoji: "🌲",
          text: {
            en: "Wild",
            es: "Salvaje",
            ja: "野生",
            pt: "Selvagem",
          },
        },
        {
          emoji: "🏠",
          text: {
            en: "Domestic",
            es: "Doméstico",
            ja: "ペット",
            pt: "De casa",
          },
        },
      ],
    },
  },
  {
    id: "s-animals-03",
    kind: "word",
    scope: "set",
    set: "animals",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What sound do they make?",
      es: "¿Qué sonido hace?",
      ja: "鳴き声は？",
      pt: "Que barulho ele faz?",
    },
    options: null,
  },
  {
    id: "s-music-01",
    kind: "pick",
    scope: "set",
    set: "music",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Stadium show or small bar gig?",
      es: "¿Concierto en estadio o en un barcito?",
      ja: "ライブはスタジアム？ライブハウス？",
      pt: "Show em estádio ou num barzinho?",
    },
    options: {
      choices: [
        {
          emoji: "🏟️",
          text: {
            en: "Stadium",
            es: "Estadio",
            ja: "スタジアム",
            pt: "Estádio",
          },
        },
        {
          emoji: "🍻",
          text: {
            en: "Small bar",
            es: "Barcito",
            ja: "ライブハウス",
            pt: "Barzinho",
          },
        },
      ],
    },
  },
  {
    id: "s-music-02",
    kind: "word",
    scope: "set",
    set: "music",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What instrument would they play?",
      es: "¿Qué instrumento tocaría?",
      ja: "演奏するならどの楽器？",
      pt: "Que instrumento ele tocaria?",
    },
    options: null,
  },
  {
    id: "s-music-03",
    kind: "scale",
    scope: "set",
    set: "music",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How in tune are they?",
      es: "¿Qué tan bien afina?",
      ja: "音程はどれくらい正確？",
      pt: "Quão afinado ele é?",
    },
    options: {
      low: {
        emoji: "🙉",
        text: {
          en: "Off-key",
          es: "Desafinado",
          ja: "音痴",
          pt: "Desafinado",
        },
      },
      high: {
        emoji: null,
        text: {
          en: "Pitch-perfect",
          es: "Afinadísimo",
          ja: "完璧",
          pt: "Afinadíssimo",
        },
      },
    },
  },
  {
    id: "s-celebs-01",
    kind: "scale",
    scope: "set",
    set: "celebs",
    themeId: null,
    audience: "real",
    spice: 1,
    text: {
      en: "How controversial are they?",
      es: "¿Qué tan polémico es?",
      ja: "どれくらいお騒がせ？",
      pt: "Quão polêmico ele é?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Squeaky clean",
          es: "Un santo",
          ja: "聖人",
          pt: "Santo",
        },
      },
      high: {
        emoji: "🔥",
        text: {
          en: "Daily drama",
          es: "Drama diario",
          ja: "毎日炎上",
          pt: "Treta todo dia",
        },
      },
    },
  },
  {
    id: "s-celebs-02",
    kind: "pick",
    scope: "set",
    set: "celebs",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Red carpet or under the radar?",
      es: "¿Alfombra roja o anonimato?",
      ja: "レッドカーペット？ひっそり？",
      pt: "Tapete vermelho ou anonimato?",
    },
    options: {
      choices: [
        {
          emoji: "📸",
          text: {
            en: "Red carpet",
            es: "Alfombra roja",
            ja: "レッドカーペット",
            pt: "Tapete vermelho",
          },
        },
        {
          emoji: "🕶️",
          text: {
            en: "Under the radar",
            es: "Anonimato",
            ja: "ひっそり",
            pt: "Anonimato",
          },
        },
      ],
    },
  },
  {
    id: "s-celebs-03",
    kind: "scale",
    scope: "set",
    set: "celebs",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How many followers would they have?",
      es: "¿Cuántos seguidores tendría?",
      ja: "フォロワーは何人？",
      pt: "Quantos seguidores ele teria?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "A thousand",
          es: "Mil",
          ja: "千人",
          pt: "Mil",
        },
      },
      high: {
        emoji: null,
        text: {
          en: "A billion",
          es: "Mil millones",
          ja: "10億人",
          pt: "Um bilhão",
        },
      },
    },
  },
  {
    id: "s-sports-01",
    kind: "scale",
    scope: "set",
    set: "sports",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How competitive are they?",
      es: "¿Qué tan competitivo es?",
      ja: "どれくらい負けず嫌い？",
      pt: "Quão competitivo ele é?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Just for fun",
          es: "Le da lo mismo",
          ja: "気にしない",
          pt: "Tanto faz",
        },
      },
      high: {
        emoji: "😤",
        text: {
          en: "Hates losing",
          es: "Odia perder",
          ja: "負けは許さない",
          pt: "Odeia perder",
        },
      },
    },
  },
  {
    id: "s-sports-02",
    kind: "pick",
    scope: "set",
    set: "sports",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Morning or night training?",
      es: "¿Entrena de mañana o de noche?",
      ja: "練習は朝？夜？",
      pt: "Treina de manhã ou à noite?",
    },
    options: {
      choices: [
        {
          emoji: "🌅",
          text: {
            en: "Morning",
            es: "Mañana",
            ja: "朝",
            pt: "Manhã",
          },
        },
        {
          emoji: "🌙",
          text: {
            en: "Night",
            es: "Noche",
            ja: "夜",
            pt: "Noite",
          },
        },
      ],
    },
  },
  {
    id: "s-sports-03",
    kind: "word",
    scope: "set",
    set: "sports",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "What other sport would they play?",
      es: "¿Qué otro deporte practicaría?",
      ja: "ほかにやるならどのスポーツ？",
      pt: "Que outro esporte ele jogaria?",
    },
    options: null,
  },
  {
    id: "s-history-01",
    kind: "pick",
    scope: "set",
    set: "history",
    themeId: null,
    audience: "real",
    spice: 2,
    text: {
      en: "Did they change history by sword or pen?",
      es: "¿Hizo historia con espada o con pluma?",
      ja: "歴史を変えたのは剣？ペン？",
      pt: "Mudou a história com a espada ou com a caneta?",
    },
    options: {
      choices: [
        {
          emoji: "⚔️",
          text: {
            en: "Sword",
            es: "Espada",
            ja: "剣",
            pt: "Espada",
          },
        },
        {
          emoji: "✒️",
          text: {
            en: "Pen",
            es: "Pluma",
            ja: "ペン",
            pt: "Caneta",
          },
        },
      ],
    },
  },
  {
    id: "s-history-02",
    kind: "scale",
    scope: "set",
    set: "history",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How remembered will they be in 500 years?",
      es: "¿Qué tan recordado será en 500 años?",
      ja: "500年後も覚えられてる？",
      pt: "Quão lembrado ele será daqui a 500 anos?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Forgotten",
          es: "Olvidado",
          ja: "忘れられる",
          pt: "Esquecido",
        },
      },
      high: {
        emoji: "🏛️",
        text: {
          en: "Immortal",
          es: "Eterno",
          ja: "永遠に語られる",
          pt: "Eterno",
        },
      },
    },
  },
  {
    id: "s-history-03",
    kind: "word",
    scope: "set",
    set: "history",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What item would be in their museum?",
      es: "¿Qué objeto estaría en su museo?",
      ja: "記念館に飾られる物は？",
      pt: "Que objeto estaria no museu dele?",
    },
    options: null,
  },
  {
    id: "s-world-01",
    kind: "pick",
    scope: "set",
    set: "world",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Do they travel by plane or ship?",
      es: "¿Viaja en avión o en barco?",
      ja: "旅は飛行機？船？",
      pt: "Viaja de avião ou de navio?",
    },
    options: {
      choices: [
        {
          emoji: "✈️",
          text: {
            en: "Plane",
            es: "Avión",
            ja: "飛行機",
            pt: "Avião",
          },
        },
        {
          emoji: "🚢",
          text: {
            en: "Ship",
            es: "Barco",
            ja: "船",
            pt: "Navio",
          },
        },
      ],
    },
  },
  {
    id: "s-world-02",
    kind: "emoji",
    scope: "set",
    set: "world",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What food would they pack in their bag?",
      es: "¿Qué comida llevaría en la maleta?",
      ja: "スーツケースに入れる食べ物は？",
      pt: "Que comida ele levaria na mala?",
    },
    options: {
      palette: "foods",
    },
  },
  {
    id: "s-world-03",
    kind: "scale",
    scope: "set",
    set: "world",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "How far from here do they live?",
      es: "¿Qué tan lejos de aquí vive?",
      ja: "ここからどれくらい遠くに住んでる？",
      pt: "Quão longe daqui ele mora?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Close by",
          es: "Cerquita",
          ja: "すぐ近く",
          pt: "Pertinho",
        },
      },
      high: {
        emoji: "🌏",
        text: {
          en: "Across the globe",
          es: "Al otro lado del mundo",
          ja: "地球の裏側",
          pt: "Outro lado do mundo",
        },
      },
    },
  },
  {
    id: "s-jobs-01",
    kind: "scale",
    scope: "set",
    set: "jobs",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How well paid are they?",
      es: "¿Qué tan bien le pagan?",
      ja: "給料はどれくらい？",
      pt: "Quão bem pago ele é?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Underpaid",
          es: "Sueldo mínimo",
          ja: "薄給",
          pt: "Mal pago",
        },
      },
      high: {
        emoji: "💼",
        text: {
          en: "Rich",
          es: "Sueldazo",
          ja: "高給取り",
          pt: "Rico",
        },
      },
    },
  },
  {
    id: "s-jobs-02",
    kind: "pick",
    scope: "set",
    set: "jobs",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Do they wear a uniform to work?",
      es: "¿Trabaja con uniforme?",
      ja: "仕事は制服？",
      pt: "Trabalha de uniforme?",
    },
    options: {
      choices: [
        {
          emoji: "🦺",
          text: {
            en: "Uniform",
            es: "Uniforme",
            ja: "制服",
            pt: "Uniforme",
          },
        },
        {
          emoji: "👕",
          text: {
            en: "Regular clothes",
            es: "Ropa normal",
            ja: "私服",
            pt: "Roupa comum",
          },
        },
      ],
    },
  },
  {
    id: "s-jobs-03",
    kind: "emoji",
    scope: "set",
    set: "jobs",
    themeId: null,
    audience: "all",
    spice: 3,
    text: {
      en: "What tool do they use?",
      es: "¿Qué herramienta usa?",
      ja: "どんな道具を使う？",
      pt: "Que ferramenta ele usa?",
    },
    options: {
      palette: "objects",
    },
  },
  {
    id: "s-family-01",
    kind: "pick",
    scope: "set",
    set: "family",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Small or huge family?",
      es: "¿Familia pequeña o enorme?",
      ja: "家族は少人数？大家族？",
      pt: "Família pequena ou enorme?",
    },
    options: {
      choices: [
        {
          emoji: "👤",
          text: {
            en: "Small",
            es: "Pequeña",
            ja: "少人数",
            pt: "Pequena",
          },
        },
        {
          emoji: "👨‍👩‍👧‍👦",
          text: {
            en: "Huge",
            es: "Enorme",
            ja: "大家族",
            pt: "Enorme",
          },
        },
      ],
    },
  },
  {
    id: "s-family-02",
    kind: "scale",
    scope: "set",
    set: "family",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How protective are they?",
      es: "¿Qué tan protector es?",
      ja: "家族をどれくらい守る？",
      pt: "Quão protetor ele é?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Hands-off",
          es: "Le da igual",
          ja: "放任",
          pt: "Nem liga",
        },
      },
      high: {
        emoji: "🛡️",
        text: {
          en: "Overprotective",
          es: "Sobreprotector",
          ja: "過保護",
          pt: "Superprotetor",
        },
      },
    },
  },
  {
    id: "s-family-03",
    kind: "pick",
    scope: "set",
    set: "family",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "Who runs the house?",
      es: "¿Manda en casa o le toca obedecer?",
      ja: "家でいちばんえらいのは？",
      pt: "Quem manda na casa?",
    },
    options: {
      choices: [
        {
          emoji: "🫵",
          text: {
            en: "They do",
            es: "Manda",
            ja: "本人",
            pt: "Ele",
          },
        },
        {
          emoji: "👉",
          text: {
            en: "Someone else",
            es: "Obedece",
            ja: "ほかの人",
            pt: "Outra pessoa",
          },
        },
      ],
    },
  },
  {
    id: "s-quirks-01",
    kind: "scale",
    scope: "set",
    set: "quirks",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How stubborn are they?",
      es: "¿Qué tan terco es?",
      ja: "どれくらい頑固？",
      pt: "Quão teimoso ele é?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Flexible",
          es: "Flexible",
          ja: "柔軟",
          pt: "Flexível",
        },
      },
      high: {
        emoji: "🐐",
        text: {
          en: "Stubborn",
          es: "Cabeza dura",
          ja: "頑固",
          pt: "Teimoso",
        },
      },
    },
  },
  {
    id: "s-quirks-02",
    kind: "scale",
    scope: "set",
    set: "quirks",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How dramatic are they?",
      es: "¿Qué tan dramático es?",
      ja: "どれくらい大げさ？",
      pt: "Quão dramático ele é?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Calm",
          es: "Tranquilo",
          ja: "冷静",
          pt: "Calmo",
        },
      },
      high: {
        emoji: "🎭",
        text: {
          en: "Soap opera",
          es: "Telenovela",
          ja: "昼ドラ並み",
          pt: "Novela",
        },
      },
    },
  },
  {
    id: "s-quirks-03",
    kind: "word",
    scope: "set",
    set: "quirks",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "What quirk do they have?",
      es: "¿Qué manía tiene?",
      ja: "どんなクセがある？",
      pt: "Que mania ele tem?",
    },
    options: null,
  },
  {
    id: "s-looks-01",
    kind: "scale",
    scope: "set",
    set: "looks",
    themeId: null,
    audience: "all",
    spice: 1,
    text: {
      en: "How flashy is their look?",
      es: "¿Qué tan llamativo es su estilo?",
      ja: "見た目はどれくらい派手？",
      pt: "Quão chamativo é o visual dele?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Low-key",
          es: "Discreto",
          ja: "地味",
          pt: "Discreto",
        },
      },
      high: {
        emoji: "👀",
        text: {
          en: "Can't miss them",
          es: "Imposible no verlo",
          ja: "嫌でも目立つ",
          pt: "Impossível não ver",
        },
      },
    },
  },
  {
    id: "s-looks-02",
    kind: "pick",
    scope: "set",
    set: "looks",
    themeId: null,
    audience: "all",
    spice: 2,
    text: {
      en: "Neat or messy hair?",
      es: "¿Pelo peinado o despeinado?",
      ja: "髪はきちんと？ボサボサ？",
      pt: "Cabelo arrumado ou bagunçado?",
    },
    options: {
      choices: [
        {
          emoji: "💇",
          text: {
            en: "Neat",
            es: "Peinado",
            ja: "きちんと",
            pt: "Arrumado",
          },
        },
        {
          emoji: "🦁",
          text: {
            en: "Messy",
            es: "Despeinado",
            ja: "ボサボサ",
            pt: "Bagunçado",
          },
        },
      ],
    },
  },
  {
    id: "s-looks-03",
    kind: "word",
    scope: "set",
    set: "looks",
    themeId: null,
    audience: "all",
    spice: 3,
    text: {
      en: "What accessory do they never take off?",
      es: "¿Qué accesorio nunca se quita?",
      ja: "いつも身につけている小物は？",
      pt: "Que acessório ele não tira?",
    },
    options: null,
  },
  {
    id: "t-poke-mon-01",
    kind: "word",
    scope: "theme",
    set: null,
    themeId: "poke-mon",
    audience: "fiction",
    spice: 2,
    text: {
      en: "What type would they be?",
      es: "¿De qué tipo sería?",
      ja: "何タイプ？",
      pt: "De que tipo ele seria?",
    },
    options: null,
  },
  {
    id: "t-harry-potter-characters-01",
    kind: "pick",
    scope: "theme",
    set: null,
    themeId: "harry-potter-characters",
    audience: "fiction",
    spice: 2,
    text: {
      en: "Which house would they choose?",
      es: "¿Qué casa elegiría?",
      ja: "どの寮を選ぶ？",
      pt: "Que casa ele escolheria?",
    },
    options: {
      choices: [
        {
          emoji: "🦁",
          text: {
            en: "Gryffindor",
            es: "Gryffindor",
            ja: "グリフィンドール",
            pt: "Grifinória",
          },
        },
        {
          emoji: "🐍",
          text: {
            en: "Slytherin",
            es: "Slytherin",
            ja: "スリザリン",
            pt: "Sonserina",
          },
        },
        {
          emoji: "🦅",
          text: {
            en: "Ravenclaw",
            es: "Ravenclaw",
            ja: "レイブンクロー",
            pt: "Corvinal",
          },
        },
        {
          emoji: "🦡",
          text: {
            en: "Hufflepuff",
            es: "Hufflepuff",
            ja: "ハッフルパフ",
            pt: "Lufa-Lufa",
          },
        },
      ],
    },
  },
  {
    id: "t-star-wars-characters-01",
    kind: "pick",
    scope: "theme",
    set: null,
    themeId: "star-wars-characters",
    audience: "fiction",
    spice: 3,
    text: {
      en: "Light side or dark side?",
      es: "¿Lado luminoso u oscuro?",
      ja: "ライトサイド？ダークサイド？",
      pt: "Luz ou sombra?",
    },
    options: {
      choices: [
        {
          emoji: "☀️",
          text: {
            en: "Light side",
            es: "Lado luminoso",
            ja: "ライトサイド",
            pt: "Luz",
          },
        },
        {
          emoji: "🌑",
          text: {
            en: "Dark side",
            es: "Lado oscuro",
            ja: "ダークサイド",
            pt: "Sombra",
          },
        },
      ],
    },
  },
  {
    id: "t-dragon-ball-characters-01",
    kind: "scale",
    scope: "theme",
    set: null,
    themeId: "dragon-ball-characters",
    audience: "fiction",
    spice: 2,
    text: {
      en: "How high is their power level?",
      es: "¿Qué tan alto es su nivel de pelea?",
      ja: "戦闘力はどれくらい？",
      pt: "Quão alto é o poder de luta dele?",
    },
    options: {
      low: {
        emoji: null,
        text: {
          en: "Regular human",
          es: "Humano común",
          ja: "一般人",
          pt: "Humano comum",
        },
      },
      high: {
        emoji: null,
        text: {
          en: "Over 9000",
          es: "Más de 8000",
          ja: "8000以上",
          pt: "Acima de 9 000",
        },
      },
    },
  },
  {
    id: "t-soccer-players-01",
    kind: "pick",
    scope: "theme",
    set: null,
    themeId: "soccer-players",
    audience: "real",
    spice: 3,
    text: {
      en: "Attack or defend?",
      es: "¿Ataca o defiende?",
      ja: "攻める？守る？",
      pt: "Ataca ou defende?",
    },
    options: {
      choices: [
        {
          emoji: "⚽",
          text: {
            en: "Attack",
            es: "Ataca",
            ja: "攻める",
            pt: "Ataca",
          },
        },
        {
          emoji: "🧤",
          text: {
            en: "Defend",
            es: "Defiende",
            ja: "守る",
            pt: "Defende",
          },
        },
      ],
    },
  },
];
