// What for?'s missions and extras in local mode: the same first lots as
// supabase/seed/lineup_missions.sql and lineup_extras.sql, as the tables hand
// them to the server.
import type { BankExtra, BankMission, Tone } from "@/game/lineup/bank";

const mission = (
  id: string,
  tone: Tone,
  heavy: boolean,
  en: string,
  es: string,
  ja: string,
  pt: string,
): BankMission => ({ id, tone, heavy, text: { en, es, ja, pt } });

const extra = (
  id: string,
  emoji: string,
  tint: string,
  en: string,
  es: string,
  ja: string,
  pt: string,
): BankExtra => ({ id, emoji, tint, name: { en, es, ja, pt } });

export const LOCAL_MISSIONS: BankMission[] = [
  mission(
    "tire-rain",
    "chores",
    false,
    "Change a car tire, in the rain, at midnight.",
    "Cambiar la llanta del auto, bajo la lluvia, a medianoche.",
    "真夜中の雨の中で、車のタイヤを交換する。",
    "Trocar o pneu do carro, na chuva, à meia-noite.",
  ),
  mission(
    "fix-car",
    "chores",
    false,
    "Fix your car, which just won't start.",
    "Arreglar tu auto, que no arranca por nada del mundo.",
    "どうしてもエンジンがかからないあなたの車を直す。",
    "Consertar o seu carro, que não pega de jeito nenhum.",
  ),
  mission(
    "move-fifth-floor",
    "chores",
    false,
    "Move all your stuff to a fifth floor with no elevator.",
    "Hacer tu mudanza a un quinto piso sin ascensor.",
    "エレベーターのない5階へ引っ越しをする。",
    "Fazer sua mudança para um 5º andar sem elevador.",
  ),
  mission(
    "wardrobe",
    "chores",
    false,
    "Build a six-door wardrobe without the manual.",
    "Armar un ropero de seis puertas sin el manual.",
    "説明書なしで6枚扉のクローゼットを組み立てる。",
    "Montar um guarda-roupa de 6 portas sem o manual.",
  ),
  mission(
    "taxes",
    "chores",
    false,
    "File your taxes on the last day.",
    "Hacer tu declaración de impuestos el último día.",
    "締め切り当日に確定申告をすませる。",
    "Fazer sua declaração do imposto de renda no último dia.",
  ),
  mission(
    "three-kids",
    "chores",
    false,
    "Look after three 4-year-olds for a weekend.",
    "Cuidar a tres niños de 4 años durante un fin de semana.",
    "4歳児3人の面倒を週末ずっと見る。",
    "Cuidar de três crianças de 4 anos por um fim de semana.",
  ),
  mission(
    "grumpy-dog",
    "chores",
    false,
    "Walk your dog, who hates every other dog.",
    "Pasear a tu perro, que odia a todos los demás perros.",
    "ほかの犬が大嫌いなあなたの犬を散歩させる。",
    "Passear com seu cachorro, que odeia todos os outros cachorros.",
  ),
  mission(
    "clogged-sink",
    "chores",
    false,
    "Unclog the sink before the guests arrive.",
    "Destapar el fregadero antes de que lleguen las visitas.",
    "お客さんが来る前に流しのつまりを直す。",
    "Desentupir a pia antes da visita chegar.",
  ),
  mission(
    "sunday-lunch",
    "chores",
    false,
    "Cook Sunday lunch for 20 relatives.",
    "Preparar el almuerzo del domingo para 20 parientes.",
    "親戚20人分の日曜のお昼ごはんを作る。",
    "Fazer o almoço de domingo para 20 parentes.",
  ),
  mission(
    "last-bus",
    "chores",
    false,
    "Catch the last bus of the night and get home in one piece.",
    "Tomar el último autobús de la noche y llegar entero a casa.",
    "終バスに乗って、無事に家までたどり着く。",
    "Pegar o último ônibus da noite e chegar inteiro em casa.",
  ),
  mission(
    "keys-beach",
    "chores",
    false,
    "Find the car key someone lost in the sand at the beach.",
    "Encontrar la llave del auto que alguien perdió en la arena de la playa.",
    "誰かが砂浜で落とした車のカギを見つける。",
    "Achar a chave do carro que alguém perdeu na areia da praia.",
  ),
  mission(
    "phone-company",
    "chores",
    false,
    "Sort out a problem with your phone company over the phone.",
    "Resolver un problema con la compañía de celular por teléfono.",
    "携帯会社のトラブルを電話で解決する。",
    "Resolver um problema com a operadora de celular por telefone.",
  ),
  mission(
    "paint-flat",
    "chores",
    false,
    "Paint the whole apartment in one Saturday.",
    "Pintar todo el departamento en un sábado.",
    "土曜日1日でアパートを丸ごと塗り替える。",
    "Pintar o apartamento inteiro em um sábado.",
  ),
  mission(
    "group-project",
    "chores",
    false,
    "Be your teammates on a college group project.",
    "Ser tus compañeros en el trabajo en grupo de la universidad.",
    "大学のグループ課題でいっしょの班になる。",
    "Ser seus colegas de grupo no trabalho da faculdade.",
  ),
  mission(
    "roommates",
    "chores",
    false,
    "Share an apartment with you for a year.",
    "Compartir un departamento contigo durante un año.",
    "1年間あなたとルームシェアする。",
    "Dividir um apartamento com você por um ano.",
  ),
  mission(
    "surgery",
    "chores",
    true,
    "Look after you after surgery.",
    "Cuidarte después de una cirugía.",
    "手術のあとのあなたを看病する。",
    "Cuidar de você depois de uma cirurgia.",
  ),
  mission(
    "entrance-exam",
    "social",
    false,
    "Study with you to pass the college entrance exam.",
    "Estudiar contigo para aprobar el examen de admisión a la universidad.",
    "大学入試に受かるまで、あなたといっしょに勉強する。",
    "Estudar com você para passar no vestibular.",
  ),
  mission(
    "best-men",
    "social",
    false,
    "Be the best men and bridesmaids at your wedding.",
    "Ser tus padrinos de boda.",
    "あなたの結婚式で付添人をつとめる。",
    "Ser seus padrinhos de casamento.",
  ),
  mission(
    "kids-party",
    "social",
    false,
    "Liven up a 5-year-old's birthday party.",
    "Animar una fiesta de cumpleaños de un niño de 5 años.",
    "5歳の誕生日パーティーを盛り上げる。",
    "Animar uma festa infantil de 5 anos.",
  ),
  mission(
    "in-laws",
    "social",
    false,
    "Meet your in-laws in your place.",
    "Conocer a tus suegros en tu lugar.",
    "あなたの代わりに恋人の両親にあいさつする。",
    "Conhecer seus sogros no seu lugar.",
  ),
  mission(
    "office-karaoke",
    "social",
    false,
    "Win the office karaoke night.",
    "Ganar el karaoke de la oficina.",
    "会社のカラオケ大会で優勝する。",
    "Ganhar o karaokê da firma.",
  ),
  mission(
    "breakup",
    "social",
    false,
    "Help you end a six-year relationship.",
    "Ayudarte a terminar una relación de seis años.",
    "6年付き合った恋人との別れ話を手伝う。",
    "Te ajudar a terminar um namoro de 6 anos.",
  ),
  mission(
    "grandma-90",
    "social",
    false,
    "Give the speech at your grandma's 90th birthday.",
    "Dar el discurso en el cumpleaños 90 de tu abuela.",
    "おばあちゃんの90歳の誕生日でスピーチをする。",
    "Fazer o discurso no aniversário de 90 anos da sua avó.",
  ),
  mission(
    "cooking-judges",
    "social",
    false,
    "Be the judges on a cooking show.",
    "Ser el jurado de un reality de cocina.",
    "料理番組の審査員をつとめる。",
    "Ser os jurados de um reality de culinária.",
  ),
  mission(
    "wedding-band",
    "social",
    false,
    "Form a band to play at your wedding.",
    "Armar una banda para tocar en tu boda.",
    "あなたの結婚式で演奏するバンドを結成する。",
    "Formar uma banda de pagode para tocar no seu casamento.",
  ),
  mission(
    "condo-meeting",
    "social",
    false,
    "Stand in for you at the building's residents' meeting.",
    "Representarte en una junta de vecinos.",
    "マンションの管理組合の会議にあなたの代理で出る。",
    "Te representar numa reunião de condomínio.",
  ),
  mission(
    "new-year",
    "social",
    false,
    "Throw the best New Year's Eve party of your life.",
    "Hacer la mejor fiesta de Año Nuevo de tu vida.",
    "人生最高の年越しパーティーを開く。",
    "Fazer a melhor festa de réveillon da sua vida.",
  ),
  mission(
    "bakery-socials",
    "social",
    false,
    "Run your bakery's social media.",
    "Llevar las redes sociales de tu panadería.",
    "あなたのパン屋のSNSを運営する。",
    "Cuidar das redes sociais da sua padaria.",
  ),
  mission(
    "upstairs",
    "social",
    false,
    "Be your upstairs neighbors.",
    "Ser los vecinos del departamento de arriba.",
    "あなたの部屋の上の階の住人になる。",
    "Ser os vizinhos do apartamento de cima.",
  ),
  mission(
    "eulogy",
    "social",
    true,
    "Speak at your funeral.",
    "Dar un discurso en tu funeral.",
    "あなたのお葬式で弔辞を読む。",
    "Discursar no seu velório.",
  ),
  mission(
    "court",
    "social",
    true,
    "Defend you in court for a crime you did commit.",
    "Defenderte en un juicio por un crimen que sí cometiste.",
    "本当にあなたがやった罪の裁判で弁護する。",
    "Te defender no tribunal por um crime que você cometeu.",
  ),
  mission(
    "cheated",
    "social",
    true,
    "Tell your best friend they're being cheated on.",
    "Decirle a tu mejor amigo que le están siendo infiel.",
    "親友に「浮気されてるよ」と伝える。",
    "Contar ao seu melhor amigo que ele foi traído.",
  ),
  mission(
    "titanic",
    "adventure",
    true,
    "Save as many people as possible when the Titanic sinks.",
    "Salvar a la mayor cantidad de gente en el naufragio del Titanic.",
    "タイタニック号の沈没で、できるだけ多くの人を救う。",
    "Salvar o máximo de gente no naufrágio do Titanic.",
  ),
  mission(
    "desert-island",
    "adventure",
    false,
    "Survive a week on a desert island.",
    "Sobrevivir una semana en una isla desierta.",
    "無人島で1週間生きのびる。",
    "Sobreviver uma semana numa ilha deserta.",
  ),
  mission(
    "escape-room",
    "adventure",
    false,
    "Get out of an escape room in 60 minutes.",
    "Salir de un escape room en 60 minutos.",
    "60分以内に脱出ゲームの部屋から出る。",
    "Sair de uma sala de fuga em 60 minutos.",
  ),
  mission(
    "amazon",
    "adventure",
    false,
    "Cross the Amazon on foot.",
    "Cruzar el Amazonas a pie.",
    "アマゾンを歩いて横断する。",
    "Atravessar a Amazônia a pé.",
  ),
  mission(
    "mars",
    "adventure",
    false,
    "Be the crew of the first trip to Mars.",
    "Ser la tripulación del primer viaje a Marte.",
    "人類初の火星旅行の乗組員になる。",
    "Ser a tripulação da primeira viagem a Marte.",
  ),
  mission(
    "casino-heist",
    "adventure",
    false,
    "Rob a casino without anyone getting hurt.",
    "Asaltar un casino sin que nadie salga herido.",
    "誰もケガさせずにカジノ強盗を成功させる。",
    "Assaltar um cassino sem ninguém se machucar.",
  ),
  mission(
    "treasure-map",
    "adventure",
    false,
    "Find a pirate treasure with a torn map.",
    "Encontrar un tesoro pirata con un mapa roto.",
    "破れた地図で海賊の宝を見つける。",
    "Achar um tesouro pirata com um mapa rasgado.",
  ),
  mission(
    "everest",
    "adventure",
    false,
    "Climb Everest.",
    "Escalar el Everest.",
    "エベレストに登る。",
    "Escalar o Everest.",
  ),
  mission(
    "pub-quiz",
    "adventure",
    false,
    "Win a pub quiz with the bill on the line.",
    "Ganar una trivia de bar con la cuenta en juego.",
    "飲み代をかけたクイズ大会で勝つ。",
    "Vencer um quiz de bar valendo a conta.",
  ),
  mission(
    "state-secret",
    "adventure",
    false,
    "Keep a state secret for 30 years.",
    "Guardar un secreto de Estado durante 30 años.",
    "国家機密を30年間守りぬく。",
    "Guardar um segredo de Estado por 30 anos.",
  ),
  mission(
    "mall-night",
    "adventure",
    false,
    "Survive a night locked inside a mall.",
    "Sobrevivir una noche encerrados en un centro comercial.",
    "閉店後のショッピングモールに閉じこめられて一晩すごす。",
    "Sobreviver a uma noite trancados num shopping.",
  ),
  mission(
    "first-contact",
    "adventure",
    false,
    "Make first contact with aliens.",
    "Hacer el primer contacto con extraterrestres.",
    "宇宙人とのファーストコンタクトをつとめる。",
    "Fazer o primeiro contato com alienígenas.",
  ),
  mission(
    "zombies",
    "adventure",
    true,
    "Survive the first month of a zombie apocalypse.",
    "Sobrevivir al primer mes de un apocalipsis zombi.",
    "ゾンビ・アポカリプスの最初の1か月を生きのびる。",
    "Sobreviver ao primeiro mês de um apocalipse zumbi.",
  ),
  mission(
    "burning-building",
    "adventure",
    true,
    "Get everyone out of a burning building.",
    "Sacar a todos de un edificio en llamas.",
    "燃えているビルから全員を救い出す。",
    "Tirar todo mundo de um prédio em chamas.",
  ),
  mission(
    "hostage-talks",
    "adventure",
    true,
    "Negotiate with kidnappers.",
    "Negociar con secuestradores.",
    "誘拐犯と交渉する。",
    "Negociar com sequestradores.",
  ),
  mission(
    "andes-crash",
    "adventure",
    true,
    "Survive a plane crash in the Andes.",
    "Sobrevivir a un accidente de avión en los Andes.",
    "アンデス山中の飛行機事故から生還する。",
    "Sobreviver a um acidente de avião nos Andes.",
  ),
  mission(
    "cat-fridge",
    "absurd",
    false,
    "Talk a cat down from the top of the fridge.",
    "Convencer a un gato de bajarse del refrigerador.",
    "冷蔵庫の上の猫を説得して降ろす。",
    "Convencer um gato a descer da geladeira.",
  ),
  mission(
    "hide-and-seek",
    "absurd",
    false,
    "Win the world hide-and-seek championship.",
    "Ganar el campeonato mundial de las escondidas.",
    "かくれんぼの世界選手権で優勝する。",
    "Vencer o campeonato mundial de esconde-esconde.",
  ),
  mission(
    "ice-penguins",
    "absurd",
    false,
    "Sell ice to penguins.",
    "Venderles hielo a los pingüinos.",
    "ペンギンに氷を売る。",
    "Vender gelo para pinguins.",
  ),
  mission(
    "crying-baby",
    "absurd",
    false,
    "Make a baby stop crying on a 12-hour flight.",
    "Hacer que un bebé deje de llorar en un vuelo de 12 horas.",
    "12時間のフライトで泣きやまない赤ちゃんをあやす。",
    "Fazer um bebê parar de chorar num voo de 12 horas.",
  ),
  mission(
    "pillow-fight",
    "absurd",
    false,
    "Win a pillow fight at summer camp.",
    "Ganar una guerra de almohadas en un campamento.",
    "合宿の枕投げで勝つ。",
    "Ganhar uma guerra de travesseiros num acampamento.",
  ),
  mission(
    "parrot",
    "absurd",
    false,
    "Teach a parrot to speak three languages.",
    "Enseñarle a un loro a hablar tres idiomas.",
    "オウムに3か国語を教える。",
    "Ensinar um papagaio a falar três línguas.",
  ),
  mission(
    "family-photo",
    "absurd",
    false,
    "Take the official photo of a 40-person family.",
    "Sacar la foto oficial de una familia de 40 personas.",
    "40人の大家族の記念写真を撮る。",
    "Tirar a foto oficial de uma família de 40 pessoas.",
  ),
  mission(
    "houseplant",
    "absurd",
    false,
    "Keep a houseplant alive for a year.",
    "Mantener viva una planta durante un año.",
    "観葉植物を1年間枯らさずに育てる。",
    "Manter uma planta viva por um ano.",
  ),
  mission(
    "halloween",
    "absurd",
    false,
    "Win a Halloween costume contest.",
    "Ganar un concurso de disfraces de Halloween.",
    "ハロウィンの仮装コンテストで優勝する。",
    "Ganhar um concurso de fantasia de Halloween.",
  ),
  mission(
    "no-phone",
    "absurd",
    false,
    "Go 24 hours without a phone.",
    "Pasar 24 horas sin celular.",
    "24時間スマホなしですごす。",
    "Ficar 24 horas sem celular.",
  ),
  mission(
    "puzzle",
    "absurd",
    false,
    "Finish a 5,000-piece jigsaw puzzle in one weekend.",
    "Armar un rompecabezas de 5000 piezas en un fin de semana.",
    "5000ピースのジグソーパズルを週末で完成させる。",
    "Montar um quebra-cabeça de 5 000 peças num fim de semana.",
  ),
  mission(
    "knight-internet",
    "absurd",
    false,
    "Explain the internet to a medieval knight.",
    "Explicarle internet a un caballero medieval.",
    "中世の騎士にインターネットを説明する。",
    "Explicar a internet para um cavaleiro medieval.",
  ),
  mission(
    "cow-stairs",
    "absurd",
    false,
    "Get a cow to climb a flight of stairs.",
    "Hacer que una vaca suba una escalera.",
    "牛に階段をのぼらせる。",
    "Fazer uma vaca subir uma escada.",
  ),
  mission(
    "last-cake",
    "absurd",
    false,
    "Find out who ate the last slice of cake.",
    "Descubrir quién se comió el último pedazo de pastel.",
    "最後のケーキを食べた犯人を突き止める。",
    "Descobrir quem comeu o último pedaço de bolo.",
  ),
  mission(
    "end-of-world",
    "absurd",
    true,
    "Announce the end of the world on the evening news.",
    "Anunciar el fin del mundo en el noticiero de la noche.",
    "夜のニュースで世界の終わりを伝える。",
    "Anunciar o fim do mundo no jornal da noite.",
  ),
  mission(
    "cellmates",
    "absurd",
    true,
    "Be your cellmates for 10 years.",
    "Ser tus compañeros de celda durante 10 años.",
    "10年間あなたと同じ牢屋ですごす。",
    "Ser seus colegas de cela por 10 anos.",
  ),
  mission(
    "hide-body",
    "absurd",
    true,
    "Help you hide a body (it's a hypothetical question).",
    "Ayudarte a esconder un cuerpo (es una pregunta hipotética).",
    "あなたの死体隠しを手伝う（あくまで仮の話）。",
    "Te ajudar a esconder um corpo (é uma pergunta hipotética).",
  ),
  mission(
    "arena-4v4",
    "contest",
    false,
    "Win a 4-on-4 fight in an arena.",
    "Ganar una pelea de 4 contra 4 en una arena.",
    "闘技場の4対4のバトルで勝つ。",
    "Vencer uma luta de 4 contra 4 numa arena.",
  ),
  mission(
    "tug-of-war",
    "contest",
    false,
    "Win a tug-of-war.",
    "Ganar una competencia de jalar la cuerda.",
    "綱引きで勝つ。",
    "Ganhar um cabo de guerra.",
  ),
  mission(
    "dodgeball",
    "contest",
    false,
    "Win the final of a dodgeball tournament.",
    "Ganar la final de un torneo de quemados.",
    "ドッジボール大会の決勝で勝つ。",
    "Vencer a final de um campeonato de queimada.",
  ),
  mission(
    "relay",
    "contest",
    false,
    "Come first in a relay race.",
    "Llegar primero en una carrera de relevos.",
    "リレーで1位になる。",
    "Chegar primeiro numa corrida de revezamento.",
  ),
  mission(
    "castle",
    "contest",
    false,
    "Defend a castle against a whole army.",
    "Defender un castillo de un ejército entero.",
    "軍隊まるごとから城を守る。",
    "Defender um castelo de um exército inteiro.",
  ),
  mission(
    "pickup-soccer",
    "contest",
    false,
    "Win a pickup soccer game with the barbecue at stake.",
    "Ganar un partido de fútbol de barrio con la parrillada en juego.",
    "焼き肉をかけた草サッカーの試合で勝つ。",
    "Ganhar uma pelada de várzea valendo a churrascada.",
  ),
  mission(
    "snowball",
    "contest",
    false,
    "Win a snowball fight.",
    "Ganar una guerra de bolas de nieve.",
    "雪合戦で勝つ。",
    "Vencer uma guerra de bolas de neve.",
  ),
  mission(
    "alien-invasion",
    "contest",
    false,
    "Protect Earth from an alien invasion.",
    "Proteger la Tierra de una invasión extraterrestre.",
    "宇宙人の侵略から地球を守る。",
    "Proteger a Terra de uma invasão alienígena.",
  ),
  mission(
    "team-chess",
    "contest",
    false,
    "Win a team chess tournament.",
    "Ganar un torneo de ajedrez por equipos.",
    "チーム対抗のチェス大会で優勝する。",
    "Ganhar um torneio de xadrez por equipes.",
  ),
  mission(
    "arm-wrestling",
    "contest",
    false,
    "Win an arm-wrestling tournament.",
    "Ganar un torneo de vencidas.",
    "腕相撲大会で優勝する。",
    "Vencer um torneio de queda de braço.",
  ),
  mission(
    "battle-royale",
    "contest",
    false,
    "Survive a battle royale.",
    "Sobrevivir a un battle royale.",
    "バトルロイヤルを生き残る。",
    "Sobreviver a um battle royale.",
  ),
  mission(
    "dance-marathon",
    "contest",
    false,
    "Win a 24-hour dance marathon.",
    "Ganar un maratón de baile de 24 horas.",
    "24時間ダンスマラソンで優勝する。",
    "Ganhar uma maratona de dança de 24 horas.",
  ),
  mission(
    "soapbox",
    "contest",
    false,
    "Win a soapbox derby.",
    "Ganar una carrera de carritos de baleros.",
    "手作りカートのレースで優勝する。",
    "Vencer uma corrida de carrinhos de rolimã.",
  ),
  mission(
    "school-games",
    "contest",
    false,
    "Win the school field day.",
    "Ganar la competencia de la kermés escolar.",
    "学校の運動会で優勝する。",
    "Ganhar uma gincana de escola.",
  ),
  mission(
    "rap-battle",
    "contest",
    false,
    "Win a rap battle.",
    "Ganar una batalla de rap.",
    "ラップバトルで勝つ。",
    "Vencer um duelo de rap.",
  ),
  mission(
    "touchdown",
    "contest",
    false,
    "Grab the football and carry it across the field.",
    "Agarrar el balón de fútbol americano y cruzar el campo.",
    "アメフトのボールを持ってフィールドを駆け抜ける。",
    "Pegar a bola de futebol americano e cruzar o campo.",
  ),
];

export const LOCAL_EXTRAS: BankExtra[] = [
  extra("baby", "👶", "#fde2c8", "A baby", "Un bebé", "赤ちゃん", "Um bebê"),
  extra(
    "grandma",
    "👵",
    "#e7dafa",
    "An old lady",
    "Una señora mayor",
    "おばあさん",
    "Uma idosa",
  ),
  extra(
    "ghost",
    "👻",
    "#dfe6f3",
    "A ghost",
    "Un fantasma",
    "おばけ",
    "Um fantasma",
  ),
  extra(
    "pigeon",
    "🐦",
    "#dcefd9",
    "A pigeon",
    "Una paloma",
    "ハト",
    "Um pombo",
  ),
  extra(
    "clown",
    "🤡",
    "#fbd7ea",
    "A clown",
    "Un payaso",
    "ピエロ",
    "Um palhaço",
  ),
  extra(
    "intern",
    "🧑‍💼",
    "#dce8fa",
    "An intern",
    "Un becario",
    "インターン",
    "Um estagiário",
  ),
  extra(
    "uncle",
    "🧔",
    "#fce8d6",
    "Your uncle with the dad jokes",
    "Tu tío el de los chistes malos",
    "ダジャレ好きのおじさん",
    "Seu tio do pavê",
  ),
  extra("goat", "🐐", "#f3e2d3", "A goat", "Una cabra", "ヤギ", "Uma cabra"),
  extra("horse", "🐴", "#f3e2d3", "A horse", "Un caballo", "ウマ", "Um cavalo"),
  extra(
    "mutt",
    "🐕",
    "#fbf3d3",
    "A street mutt",
    "Un perrito callejero",
    "雑種の犬",
    "Um vira-lata caramelo",
  ),
  extra("duck", "🦆", "#d6f0f7", "A duck", "Un pato", "アヒル", "Um pato"),
  extra(
    "cat",
    "🐈",
    "#e8ecf3",
    "A cat that ignores you",
    "Un gato que te ignora",
    "知らんぷりする猫",
    "Um gato que te ignora",
  ),
  extra(
    "magician",
    "🎩",
    "#e4e0fb",
    "A kids' party magician",
    "Un mago de fiestas infantiles",
    "子ども会の手品師",
    "Um mágico de festa infantil",
  ),
  extra(
    "dancer",
    "🕺",
    "#fbd7ea",
    "A ballroom dancer",
    "Un bailarín de salsa",
    "社交ダンサー",
    "Um dançarino de forró",
  ),
  extra(
    "lunch-lady",
    "🧑‍🍳",
    "#fde2c8",
    "A lunch lady",
    "La señora del comedor",
    "給食のおばちゃん",
    "Uma merendeira",
  ),
  extra(
    "traffic-cop",
    "👮",
    "#dce8fa",
    "A traffic cop",
    "Un agente de tránsito",
    "交通整理のおまわりさん",
    "Um guarda de trânsito",
  ),
  extra(
    "astronaut",
    "🧑‍🚀",
    "#dfe6f3",
    "A retired astronaut",
    "Un astronauta jubilado",
    "引退した宇宙飛行士",
    "Um astronauta aposentado",
  ),
  extra(
    "cowboy",
    "🤠",
    "#f3e2d3",
    "A rodeo cowboy",
    "Un vaquero de rodeo",
    "ロデオのカウボーイ",
    "Um caubói de rodeio",
  ),
  extra(
    "vampire",
    "🧛",
    "#e7dafa",
    "A shy vampire",
    "Un vampiro tímido",
    "内気な吸血鬼",
    "Um vampiro tímido",
  ),
  extra(
    "zombie",
    "🧟",
    "#dcefd9",
    "A polite zombie",
    "Un zombi educado",
    "礼儀正しいゾンビ",
    "Um zumbi educado",
  ),
  extra(
    "robot-vacuum",
    "🤖",
    "#e8ecf3",
    "A robot vacuum",
    "Una aspiradora robot",
    "ロボット掃除機",
    "Um robô aspirador",
  ),
  extra(
    "teacher",
    "🧑‍🏫",
    "#fbf3d3",
    "Your 4th-grade teacher",
    "Tu maestra de cuarto grado",
    "小4のときの担任の先生",
    "Sua professora da 4ª série",
  ),
  extra(
    "dentist",
    "🦷",
    "#d6f0f7",
    "A dentist",
    "Un dentista",
    "歯医者さん",
    "Um dentista",
  ),
  extra(
    "plumber",
    "🔧",
    "#dce8fa",
    "A plumber",
    "Un plomero",
    "配管工",
    "Um encanador",
  ),
  extra(
    "trainer",
    "🏋️",
    "#fce8d6",
    "A personal trainer",
    "Un entrenador personal",
    "パーソナルトレーナー",
    "Um personal trainer",
  ),
  extra(
    "quantum-coach",
    "🔮",
    "#e4e0fb",
    "A quantum life coach",
    "Un coach cuántico",
    "あやしい自己啓発コーチ",
    "Um coach quântico",
  ),
  extra(
    "ninja",
    "🥷",
    "#e8ecf3",
    "A retired ninja",
    "Un ninja jubilado",
    "引退した忍者",
    "Um ninja aposentado",
  ),
  extra(
    "farmer",
    "🧑‍🌾",
    "#dcefd9",
    "A farmer",
    "Un granjero",
    "農家のおじさん",
    "Um fazendeiro",
  ),
  extra(
    "gorilla",
    "🦍",
    "#e8ecf3",
    "A gorilla",
    "Un gorila",
    "ゴリラ",
    "Um gorila",
  ),
  extra("bear", "🐻", "#f3e2d3", "A bear", "Un oso", "クマ", "Um urso"),
  extra(
    "snail",
    "🐌",
    "#dcefd9",
    "A snail",
    "Un caracol",
    "カタツムリ",
    "Uma lesma",
  ),
  extra("owl", "🦉", "#fbf3d3", "An owl", "Un búho", "フクロウ", "Uma coruja"),
  extra(
    "bar-singer",
    "🎸",
    "#fde2c8",
    "A bar singer",
    "Un cantante de bar",
    "バーの弾き語り歌手",
    "Um cantor de barzinho",
  ),
  extra(
    "kid-hacker",
    "💻",
    "#d6f0f7",
    "A 12-year-old hacker",
    "Un hacker de 12 años",
    "12歳のハッカー",
    "Um hacker de 12 anos",
  ),
  extra(
    "rider",
    "🛵",
    "#fce8d6",
    "A delivery rider",
    "Un repartidor en moto",
    "バイク便の配達員",
    "Um motoboy",
  ),
  extra(
    "grandpa",
    "🧓",
    "#e7dafa",
    "Your grandpa",
    "Tu abuelo",
    "おじいちゃん",
    "Seu avô",
  ),
];
