-- Library pictures added by hand, 2026-10: characters What for?'s deck deals
-- (a language's best known, or a gosto's) that had none. Each is the lead
-- image of the character's Wikipedia article (English, or the language it is
-- known in), as the library build takes them, looked at one by one; logos,
-- posters crowded with text and the wrong version of a character were left
-- out. Insert only, as the library's own (bonus 20): safe to run again, and
-- the covers follow.
with v(character_id, url) as (values
  ('hand-anxiety-inside-out', 'https://upload.wikimedia.org/wikipedia/en/e/ef/Anxiety_%28Inside_Out%29.png'),
  ('hand-arceus', 'https://upload.wikimedia.org/wikipedia/en/9/96/Arceus.png'),
  ('hand-astro-boy', 'https://upload.wikimedia.org/wikipedia/en/f/f2/Astro_Boy_anime_version.png'),
  ('hand-barney-the-dinosaur', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Barney_show_in_Qatar_%284340543390%29.jpg/500px-Barney_show_in_Qatar_%284340543390%29.jpg'),
  ('hand-batmobile', 'https://upload.wikimedia.org/wikipedia/en/2/27/Batmobile_%28circa_2018%29.png'),
  ('hand-big-bad-wolf', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Little_Red_Riding_Hood_-_J._W._Smith.jpg/500px-Little_Red_Riding_Hood_-_J._W._Smith.jpg'),
  ('hand-bigfoot', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Patterson_Gimlin_Bigfoot.jpg/500px-Patterson_Gimlin_Bigfoot.jpg'),
  ('hand-blossom-powerpuff-girls', 'https://upload.wikimedia.org/wikipedia/en/7/7b/Blossom_PPG_98_Art.png'),
  ('hand-boogeyman', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ac/Francisco_de_Goya%2C_Que_viene_el_coco_%28Here_Comes_the_Bogey-Man%29%2C_published_1799%2C_NGA_7459.jpg/500px-Francisco_de_Goya%2C_Que_viene_el_coco_%28Here_Comes_the_Bogey-Man%29%2C_published_1799%2C_NGA_7459.jpg'),
  ('hand-brothers-grimm', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/Grimm.jpg/500px-Grimm.jpg'),
  ('hand-butterfree', 'https://upload.wikimedia.org/wikipedia/en/9/96/Butterfree.png'),
  ('hand-cactuar', 'https://upload.wikimedia.org/wikipedia/en/9/9b/Cactuar_FFVII_Remake.png'),
  ('hand-cantinflas', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/Cantinflas_en_1967_%28cropped%29.webp/500px-Cantinflas_en_1967_%28cropped%29.webp'),
  ('hand-captain-olimar', 'https://upload.wikimedia.org/wikipedia/en/e/e4/CaptainOlimarKey.png'),
  ('hand-carmen-sandiego', 'https://upload.wikimedia.org/wikipedia/en/9/9a/Carmen_Sandiego_%28character%29.png'),
  ('hand-catbus', 'https://upload.wikimedia.org/wikipedia/en/5/59/Catbus_%28My_Neighbor_Totoro%29.jpg'),
  ('hand-celia-cruz', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Celia_Cruz_1957_color.jpg/500px-Celia_Cruz_1957_color.jpg'),
  ('hand-chiikawa', 'https://upload.wikimedia.org/wikipedia/en/f/f2/Chiikawa_volume_1_cover.jpg'),
  ('hand-clifford-the-big-red-dog', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/CliffordTheBigRedDog1stEdition1963.png/500px-CliffordTheBigRedDog1stEdition1963.png'),
  ('hand-cygnus-hyoga', 'https://upload.wikimedia.org/wikipedia/en/d/d5/HyogaKurumada.png'),
  ('hand-daddy-yankee', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Daddy_Yankee_-_The_Kingdom_%28Official_Q_%26_A%29.png'),
  ('hand-delorean-time-machine', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/DeLorean_Replica_Kovacs_Time_Machine.png/500px-DeLorean_Replica_Kovacs_Time_Machine.png'),
  ('hand-diglett', 'https://upload.wikimedia.org/wikipedia/en/8/87/Dugtrio_Pok%C3%A9mon_Theme_Park.png'),
  ('hand-don-quixote', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Ciudad_Real_-_Estatua_de_don_Quijote_de_la_Mancha_en_el_Museo_Cervantes_-_panoramio.jpg/500px-Ciudad_Real_-_Estatua_de_don_Quijote_de_la_Mancha_en_el_Museo_Cervantes_-_panoramio.jpg'),
  ('hand-dora-the-explorer', 'https://upload.wikimedia.org/wikipedia/en/9/99/Dora_the_Explorer_%28character%29.webp'),
  ('hand-dragon', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/St_Catherine%2C_St_George_and_the_Dragon_%28M%C3%A4staren_fr%C3%A5n_Kappenberg%29_-_Nationalmuseum_-_18337_%28brightened%29%2C_draken.png/500px-St_Catherine%2C_St_George_and_the_Dragon_%28M%C3%A4staren_fr%C3%A5n_Kappenberg%29_-_Nationalmuseum_-_18337_%28brightened%29%2C_draken.png'),
  ('hand-dumbo', 'https://upload.wikimedia.org/wikipedia/en/a/a7/Dumbo-1941-poster.jpg'),
  ('hand-e-t', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/E.T._figure_at_Madame_Tussauds_London.jpg/500px-E.T._figure_at_Madame_Tussauds_London.jpg'),
  ('hand-elizabeth-i', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Darnley_stage_3.jpg/500px-Darnley_stage_3.jpg'),
  ('hand-evangelion-unit-01', 'https://upload.wikimedia.org/wikipedia/en/0/04/Evangelion_units.jpg'),
  ('hand-fujin', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/F%C5%ABjin_at_Sanj%C5%ABsangen-d%C5%8D.jpg/500px-F%C5%ABjin_at_Sanj%C5%ABsangen-d%C5%8D.jpg'),
  ('hand-goldilocks', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ef/The_Three_Bears_-_Project_Gutenberg_eText_17034.jpg/500px-The_Three_Bears_-_Project_Gutenberg_eText_17034.jpg'),
  ('hand-golem', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Golem_%E2%80%93_Mikol%C3%A1%C5%A1_Ale%C5%A1_%28Star%C3%A9_pov%C4%9Bsti_%C4%8Desk%C3%A9%29.jpg/500px-Golem_%E2%80%93_Mikol%C3%A1%C5%A1_Ale%C5%A1_%28Star%C3%A9_pov%C4%9Bsti_%C4%8Desk%C3%A9%29.jpg'),
  ('hand-golgo-13', 'https://upload.wikimedia.org/wikipedia/en/1/1c/Golgo_13_vol_1_%28Japanese_edition%29.jpg'),
  ('hand-grumpy-cat', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/Grumpy_Cat_%2814556024763%29_%28cropped%29.jpg/500px-Grumpy_Cat_%2814556024763%29_%28cropped%29.jpg'),
  ('hand-gumball-watterson', 'https://upload.wikimedia.org/wikipedia/en/2/26/Amazing_World_of_Gumball_Wattersons.png'),
  ('hand-hachiko', 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Hachiko.JPG'),
  ('hand-hamtaro', 'https://upload.wikimedia.org/wikipedia/en/0/03/Hamtaro_cover.jpg'),
  ('hand-hansel-and-gretel', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Hansel-and-gretel-rackham.jpg/500px-Hansel-and-gretel-rackham.jpg'),
  ('hand-hattori-hanzo', 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Hattori_Hanzo.jpg'),
  ('hand-headless-mule', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/Mulasemcabeca.JPG/500px-Mulasemcabeca.JPG'),
  ('hand-j-balvin', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/J_Balvin%2C_Noisey_Meets%3B_Oct_2018.jpg/500px-J_Balvin%2C_Noisey_Meets%3B_Oct_2018.jpg'),
  ('hand-jibanyan', 'https://upload.wikimedia.org/wikipedia/en/2/28/Jibanyan_artwork_for_Yo-kai_Watch_3.png'),
  ('hand-joy-inside-out', 'https://upload.wikimedia.org/wikipedia/en/3/30/Joy_-_Inside_Out.webp'),
  ('hand-juan-gabriel', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Juan_Gabriel_in_1985_%28cropped%29.jpg/500px-Juan_Gabriel_in_1985_%28cropped%29.jpg'),
  ('hand-leprechaun', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Leprechaun_ill_artlibre_jnl.png/500px-Leprechaun_ill_artlibre_jnl.png'),
  ('hand-little-red-riding-hood', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Little_Red_Riding_Hood_-_J._W._Smith.jpg/500px-Little_Red_Riding_Hood_-_J._W._Smith.jpg'),
  ('hand-maneki-neko', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/Manekineko1003.jpg/500px-Manekineko1003.jpg'),
  ('hand-marie-antoinette', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Louise_Elisabeth_Vig%C3%A9e-Lebrun_-_Marie-Antoinette_dit_%C2%AB_%C3%A0_la_Rose_%C2%BB_-_Google_Art_Project.jpg/500px-Louise_Elisabeth_Vig%C3%A9e-Lebrun_-_Marie-Antoinette_dit_%C2%AB_%C3%A0_la_Rose_%C2%BB_-_Google_Art_Project.jpg'),
  ('hand-maui', 'https://upload.wikimedia.org/wikipedia/en/5/57/Maui_Disney.webp'),
  ('hand-mermaid', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/John_William_Waterhouse_A_Mermaid.jpg/500px-John_William_Waterhouse_A_Mermaid.jpg'),
  ('hand-mike-wazowski', 'https://upload.wikimedia.org/wikipedia/en/6/6a/Mike_Wazowski.png'),
  ('hand-millennium-falcon', 'https://upload.wikimedia.org/wikipedia/en/8/8d/A_screenshot_from_Star_Wars_Episode_IV_A_New_Hope_depicting_the_Millennium_Falcon.jpg'),
  ('hand-moby-dick', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Moby_Dick_p510_illustration.jpg/500px-Moby_Dick_p510_illustration.jpg'),
  ('hand-mushu', 'https://upload.wikimedia.org/wikipedia/en/1/10/Mushu.png'),
  ('hand-mussum', 'https://upload.wikimedia.org/wikipedia/en/2/2c/Mussum_O_Globo.jpeg'),
  ('hand-nairobi-money-heist', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/78/Wandgem%C3%A4lde_Alba_Flores_-_Nairobi_-_Venloer_Stra%C3%9Fe_274%2C_K%C3%B6ln-Ehrenfeld-7360.jpg/500px-Wandgem%C3%A4lde_Alba_Flores_-_Nairobi_-_Venloer_Stra%C3%9Fe_274%2C_K%C3%B6ln-Ehrenfeld-7360.jpg'),
  ('hand-namahage', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/Namahage.jpg/500px-Namahage.jpg'),
  ('hand-nopperabo', 'https://upload.wikimedia.org/wikipedia/commons/7/76/Masasumi_Noppera-bo.jpg'),
  ('hand-oiwa', 'https://upload.wikimedia.org/wikipedia/commons/4/43/Kuniyoshi_oiwa.jpg'),
  ('hand-okiku', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Yoshitoshi_Ogiku.jpg/500px-Yoshitoshi_Ogiku.jpg'),
  ('hand-oni', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/Kobo_Daishi_Practicing_the_Tantra%2C_with_Demon_and_Wolf%2C_by_Hokusai.jpg/500px-Kobo_Daishi_Practicing_the_Tantra%2C_with_Demon_and_Wolf%2C_by_Hokusai.jpg'),
  ('hand-os-trapalhoes', 'https://upload.wikimedia.org/wikipedia/en/9/9e/Trapalhoes.jpg'),
  ('hand-patati-patata', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bc/A_dupla_de_palha%C3%A7os_Patati_e_Patat%C3%A1_faz_apresenta%C3%A7%C3%A3o_da_exposi%C3%A7%C3%A3o_Mundo_MCTIC._Foto._Herivelto_Batista_%2830537934624%29.jpg/500px-A_dupla_de_palha%C3%A7os_Patati_e_Patat%C3%A1_faz_apresenta%C3%A7%C3%A3o_da_exposi%C3%A7%C3%A3o_Mundo_MCTIC._Foto._Herivelto_Batista_%2830537934624%29.jpg'),
  ('hand-paul-the-octopus', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Oktopus-Orakel_Paul_mit_Schuh.JPG/500px-Oktopus-Orakel_Paul_mit_Schuh.JPG'),
  ('hand-paulo-gustavo', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Paulo_Gustavo_em_novembro_de_2019_no_Humor_Multishow_%28cropped%29.png/500px-Paulo_Gustavo_em_novembro_de_2019_no_Humor_Multishow_%28cropped%29.png'),
  ('hand-perman', 'https://upload.wikimedia.org/wikipedia/en/f/fc/Perman_%28game_box_art%29.jpg'),
  ('hand-prince-charming', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Prince_of_Sleeping_Beauty.jpg/500px-Prince_of_Sleeping_Beauty.jpg'),
  ('hand-princess-zelda', 'https://upload.wikimedia.org/wikipedia/en/6/6e/Link_to_the_Past_Zelda.png'),
  ('hand-pumbaa', 'https://upload.wikimedia.org/wikipedia/en/9/91/Pumbaa.png'),
  ('hand-raijin', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Raijin_in_Sanj%C5%ABsangen-d%C5%8D._Mid-13th_century.jpg/500px-Raijin_in_Sanj%C5%ABsangen-d%C5%8D._Mid-13th_century.jpg'),
  ('hand-ringo-starr', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/ARTIST_INTERVIEW_-_Ringo_Starr_%28Former_the_Beatles%29_exclusive_interview_0-14_screenshot_%28portrait_crop%29.jpg/500px-ARTIST_INTERVIEW_-_Ringo_Starr_%28Former_the_Beatles%29_exclusive_interview_0-14_screenshot_%28portrait_crop%29.jpg'),
  ('hand-saint-peter', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Saint_Peter-Sinai_%286th_Century%29.jpg/500px-Saint_Peter-Sinai_%286th_Century%29.jpg'),
  ('hand-sakana-kun', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Masayuki_Miyazawa_cropped_1_Masayuki_Miyazawa_20141024.jpg/500px-Masayuki_Miyazawa_cropped_1_Masayuki_Miyazawa_20141024.jpg'),
  ('hand-slime-dragon-quest', 'https://upload.wikimedia.org/wikipedia/en/9/9d/Slime_%28Dragon_Quest%29.png'),
  ('hand-team-rocket', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/71/Team_Rocket_Logo.svg/500px-Team_Rocket_Logo.svg.png'),
  ('hand-the-cat-in-the-hat', 'https://upload.wikimedia.org/wikipedia/en/1/10/The_Cat_in_the_Hat.png'),
  ('hand-three-little-pigs', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/Three_little_pigs_and_mother_sow_-_Project_Gutenberg_eText_15661.jpg/500px-Three_little_pigs_and_mother_sow_-_Project_Gutenberg_eText_15661.jpg'),
  ('hand-tiradentes', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Jos%C3%A9_da_Silva_Xavier%2C_o_Tiradentes.jpg/500px-Jos%C3%A9_da_Silva_Xavier%2C_o_Tiradentes.jpg'),
  ('hand-tom-nook', 'https://upload.wikimedia.org/wikipedia/en/7/72/Tom_Nook.png'),
  ('hand-town-musicians-of-bremen', 'https://upload.wikimedia.org/wikipedia/commons/1/14/Bremen.band.500pix.jpg'),
  ('hand-troll', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/John_Bauer_1915.jpg/500px-John_Bauer_1915.jpg'),
  ('hand-ultraman-tiga', 'https://upload.wikimedia.org/wikipedia/en/5/51/UltramanTigaSeries.jpg'),
  ('hand-ultraman-tsuburaya', 'https://upload.wikimedia.org/wikipedia/en/4/4e/Ultraman_Profile_Photo.jpg'),
  ('hand-unicorn', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/Oftheunicorn.jpg/500px-Oftheunicorn.jpg'),
  ('hand-urashima-taro', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Matsuki_Heikichi%281899%29-Urashima-p04.jpg/500px-Matsuki_Heikichi%281899%29-Urashima-p04.jpg'),
  ('hand-vicente-fernandez', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/Vicente_Fern%C3%A1ndez_-_Pepsi_Center_-_06.11.11.jpg/500px-Vicente_Fern%C3%A1ndez_-_Pepsi_Center_-_06.11.11.jpg'),
  ('hand-virgen-de-guadalupe', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/Virgen_de_guadalupe1.jpg/500px-Virgen_de_guadalupe1.jpg'),
  ('hand-wall-e', 'https://upload.wikimedia.org/wikipedia/en/6/68/WALL-E_%28character%29.png'),
  ('hand-werewolf', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/WeirdTalesv36n2pg038_The_Werewolf_Howls.png/500px-WeirdTalesv36n2pg038_The_Werewolf_Howls.png'),
  ('hand-whindersson-nunes', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/Whindersson_2021.png/500px-Whindersson_2021.png'),
  ('hand-wright-brothers', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Orville_Wright_1905-crop.jpg/500px-Orville_Wright_1905-crop.jpg'),
  ('hand-ziraldo', 'https://upload.wikimedia.org/wikipedia/commons/7/76/Ziraldo_e_Felipe_Vellozo_2015_%28cropped%29.jpg'),
  ('hand-zumbi-dos-palmares', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Ant%C3%B4nio_Parreiras_-_Zumbi_2.jpg/500px-Ant%C3%B4nio_Parreiras_-_Zumbi_2.jpg'),
  ('wd-Q1318594', 'https://upload.wikimedia.org/wikipedia/en/1/15/Miho_Nakayama_2024.jpg'),
  ('wd-Q20038709', 'https://upload.wikimedia.org/wikipedia/en/7/7a/Cropped_Photo_of_Mizuki_Itagaki.jpeg'),
  ('hand-balthazar-magi', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e9/Girolamo_da_Santacroce_-_The_Adoration_of_the_Three_Kings_-_Walters_37261_-_Detail_A.jpg/500px-Girolamo_da_Santacroce_-_The_Adoration_of_the_Three_Kings_-_Walters_37261_-_Detail_A.jpg'),
  ('hand-chico-bento', 'https://upload.wikimedia.org/wikipedia/pt/b/b8/Chico_Bento_%28personagem%29.jpg'),
  ('hand-el-chapulin-colorado', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/El_Chapul%C3%ADn_Colorado_logo.svg/500px-El_Chapul%C3%ADn_Colorado_logo.svg.png'),
  ('hand-jaimito-el-cartero', 'https://upload.wikimedia.org/wikipedia/commons/1/10/Ra%C3%BAl_Chato_Padilla%2C_Jaimito_el_Cartero%2C_statue_in_Mexico_%282%29.png'),
  ('hand-louro-jose', 'https://upload.wikimedia.org/wikipedia/pt/2/25/Louro_Jos%C3%A9_e_Tom_Veiga.png'),
  ('hand-mafalda', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Mafalda_nos_saluda.JPG/500px-Mafalda_nos_saluda.JPG'),
  ('hand-medama-oyaji', 'https://upload.wikimedia.org/wikipedia/ja/3/38/Sakaiminato_Mizuki_Shigeru_Road_Medama-oyaji_Statue_1.JPG'),
  ('hand-melchior-magi', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Adoration_of_the_Magi_ABM_s80_-_Melchior.jpg/500px-Adoration_of_the_Magi_ABM_s80_-_Melchior.jpg'),
  ('hand-menino-maluquinho', 'https://upload.wikimedia.org/wikipedia/pt/d/da/O_Menino_Maluquinho.png'),
  ('hand-phoenix-mythology', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Nuremberg_chronicles_-_Phoenix_%28CIIIIv%29.jpg/500px-Nuremberg_chronicles_-_Phoenix_%28CIIIIv%29.jpg'),
  ('hand-saint-george', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Stgeorge-dragon.jpg/500px-Stgeorge-dragon.jpg'),
  ('hand-tia-nastacia', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/Benedita_Rodrigues_%28Tupi%29.jpg/500px-Benedita_Rodrigues_%28Tupi%29.jpg')
), added as (
  insert into public.character_images (character_id, url, status, bonus)
  select v.character_id, v.url, 'active', 20
  from v
  where exists (select 1 from public.characters c where c.id = v.character_id)
    and not exists (
      select 1 from public.character_images i
      where i.character_id = v.character_id and i.url = v.url
    )
  returning character_id
)
select count(*) from added;

select public.refresh_character_cover(id)
from unnest(array[
  'hand-anxiety-inside-out',
  'hand-arceus',
  'hand-astro-boy',
  'hand-barney-the-dinosaur',
  'hand-batmobile',
  'hand-big-bad-wolf',
  'hand-bigfoot',
  'hand-blossom-powerpuff-girls',
  'hand-boogeyman',
  'hand-brothers-grimm',
  'hand-butterfree',
  'hand-cactuar',
  'hand-cantinflas',
  'hand-captain-olimar',
  'hand-carmen-sandiego',
  'hand-catbus',
  'hand-celia-cruz',
  'hand-chiikawa',
  'hand-clifford-the-big-red-dog',
  'hand-cygnus-hyoga',
  'hand-daddy-yankee',
  'hand-delorean-time-machine',
  'hand-diglett',
  'hand-don-quixote',
  'hand-dora-the-explorer',
  'hand-dragon',
  'hand-dumbo',
  'hand-e-t',
  'hand-elizabeth-i',
  'hand-evangelion-unit-01',
  'hand-fujin',
  'hand-goldilocks',
  'hand-golem',
  'hand-golgo-13',
  'hand-grumpy-cat',
  'hand-gumball-watterson',
  'hand-hachiko',
  'hand-hamtaro',
  'hand-hansel-and-gretel',
  'hand-hattori-hanzo',
  'hand-headless-mule',
  'hand-j-balvin',
  'hand-jibanyan',
  'hand-joy-inside-out',
  'hand-juan-gabriel',
  'hand-leprechaun',
  'hand-little-red-riding-hood',
  'hand-maneki-neko',
  'hand-marie-antoinette',
  'hand-maui',
  'hand-mermaid',
  'hand-mike-wazowski',
  'hand-millennium-falcon',
  'hand-moby-dick',
  'hand-mushu',
  'hand-mussum',
  'hand-nairobi-money-heist',
  'hand-namahage',
  'hand-nopperabo',
  'hand-oiwa',
  'hand-okiku',
  'hand-oni',
  'hand-os-trapalhoes',
  'hand-patati-patata',
  'hand-paul-the-octopus',
  'hand-paulo-gustavo',
  'hand-perman',
  'hand-prince-charming',
  'hand-princess-zelda',
  'hand-pumbaa',
  'hand-raijin',
  'hand-ringo-starr',
  'hand-saint-peter',
  'hand-sakana-kun',
  'hand-slime-dragon-quest',
  'hand-team-rocket',
  'hand-the-cat-in-the-hat',
  'hand-three-little-pigs',
  'hand-tiradentes',
  'hand-tom-nook',
  'hand-town-musicians-of-bremen',
  'hand-troll',
  'hand-ultraman-tiga',
  'hand-ultraman-tsuburaya',
  'hand-unicorn',
  'hand-urashima-taro',
  'hand-vicente-fernandez',
  'hand-virgen-de-guadalupe',
  'hand-wall-e',
  'hand-werewolf',
  'hand-whindersson-nunes',
  'hand-wright-brothers',
  'hand-ziraldo',
  'hand-zumbi-dos-palmares',
  'wd-Q1318594',
  'wd-Q20038709',
  'hand-balthazar-magi',
  'hand-chico-bento',
  'hand-el-chapulin-colorado',
  'hand-jaimito-el-cartero',
  'hand-louro-jose',
  'hand-mafalda',
  'hand-medama-oyaji',
  'hand-melchior-magi',
  'hand-menino-maluquinho',
  'hand-phoenix-mythology',
  'hand-saint-george',
  'hand-tia-nastacia'
]) as id;
