-- What for?'s extras, first lot (36): plain folk and animals drawn by hand,
-- an emoji on a tint. Hand-fed: run again to update, never to remove one
-- (hide it: status 'hidden').
insert into public.lineup_extras (id, emoji, tint, en, es, ja, pt)
values
  ('baby', '👶', '#fde2c8', 'A baby', 'Un bebé', '赤ちゃん', 'Um bebê'),
  ('grandma', '👵', '#e7dafa', 'An old lady', 'Una señora mayor', 'おばあさん', 'Uma idosa'),
  ('ghost', '👻', '#dfe6f3', 'A ghost', 'Un fantasma', 'おばけ', 'Um fantasma'),
  ('pigeon', '🐦', '#dcefd9', 'A pigeon', 'Una paloma', 'ハト', 'Um pombo'),
  ('clown', '🤡', '#fbd7ea', 'A clown', 'Un payaso', 'ピエロ', 'Um palhaço'),
  ('intern', '🧑‍💼', '#dce8fa', 'An intern', 'Un becario', 'インターン', 'Um estagiário'),
  ('uncle', '🧔', '#fce8d6', 'Your uncle with the dad jokes', 'Tu tío el de los chistes malos', 'ダジャレ好きのおじさん', 'Seu tio do pavê'),
  ('goat', '🐐', '#f3e2d3', 'A goat', 'Una cabra', 'ヤギ', 'Uma cabra'),
  ('horse', '🐴', '#f3e2d3', 'A horse', 'Un caballo', 'ウマ', 'Um cavalo'),
  ('mutt', '🐕', '#fbf3d3', 'A street mutt', 'Un perrito callejero', '雑種の犬', 'Um vira-lata caramelo'),
  ('duck', '🦆', '#d6f0f7', 'A duck', 'Un pato', 'アヒル', 'Um pato'),
  ('cat', '🐈', '#e8ecf3', 'A cat that ignores you', 'Un gato que te ignora', '知らんぷりする猫', 'Um gato que te ignora'),
  ('magician', '🎩', '#e4e0fb', 'A kids'' party magician', 'Un mago de fiestas infantiles', '子ども会の手品師', 'Um mágico de festa infantil'),
  ('dancer', '🕺', '#fbd7ea', 'A ballroom dancer', 'Un bailarín de salsa', '社交ダンサー', 'Um dançarino de forró'),
  ('lunch-lady', '🧑‍🍳', '#fde2c8', 'A lunch lady', 'La señora del comedor', '給食のおばちゃん', 'Uma merendeira'),
  ('traffic-cop', '👮', '#dce8fa', 'A traffic cop', 'Un agente de tránsito', '交通整理のおまわりさん', 'Um guarda de trânsito'),
  ('astronaut', '🧑‍🚀', '#dfe6f3', 'A retired astronaut', 'Un astronauta jubilado', '引退した宇宙飛行士', 'Um astronauta aposentado'),
  ('cowboy', '🤠', '#f3e2d3', 'A rodeo cowboy', 'Un vaquero de rodeo', 'ロデオのカウボーイ', 'Um caubói de rodeio'),
  ('vampire', '🧛', '#e7dafa', 'A shy vampire', 'Un vampiro tímido', '内気な吸血鬼', 'Um vampiro tímido'),
  ('zombie', '🧟', '#dcefd9', 'A polite zombie', 'Un zombi educado', '礼儀正しいゾンビ', 'Um zumbi educado'),
  ('robot-vacuum', '🤖', '#e8ecf3', 'A robot vacuum', 'Una aspiradora robot', 'ロボット掃除機', 'Um robô aspirador'),
  ('teacher', '🧑‍🏫', '#fbf3d3', 'Your 4th-grade teacher', 'Tu maestra de cuarto grado', '小4のときの担任の先生', 'Sua professora da 4ª série'),
  ('dentist', '🦷', '#d6f0f7', 'A dentist', 'Un dentista', '歯医者さん', 'Um dentista'),
  ('plumber', '🔧', '#dce8fa', 'A plumber', 'Un plomero', '配管工', 'Um encanador'),
  ('trainer', '🏋️', '#fce8d6', 'A personal trainer', 'Un entrenador personal', 'パーソナルトレーナー', 'Um personal trainer'),
  ('quantum-coach', '🔮', '#e4e0fb', 'A quantum life coach', 'Un coach cuántico', 'あやしい自己啓発コーチ', 'Um coach quântico'),
  ('ninja', '🥷', '#e8ecf3', 'A retired ninja', 'Un ninja jubilado', '引退した忍者', 'Um ninja aposentado'),
  ('farmer', '🧑‍🌾', '#dcefd9', 'A farmer', 'Un granjero', '農家のおじさん', 'Um fazendeiro'),
  ('gorilla', '🦍', '#e8ecf3', 'A gorilla', 'Un gorila', 'ゴリラ', 'Um gorila'),
  ('bear', '🐻', '#f3e2d3', 'A bear', 'Un oso', 'クマ', 'Um urso'),
  ('snail', '🐌', '#dcefd9', 'A snail', 'Un caracol', 'カタツムリ', 'Uma lesma'),
  ('owl', '🦉', '#fbf3d3', 'An owl', 'Un búho', 'フクロウ', 'Uma coruja'),
  ('bar-singer', '🎸', '#fde2c8', 'A bar singer', 'Un cantante de bar', 'バーの弾き語り歌手', 'Um cantor de barzinho'),
  ('kid-hacker', '💻', '#d6f0f7', 'A 12-year-old hacker', 'Un hacker de 12 años', '12歳のハッカー', 'Um hacker de 12 anos'),
  ('rider', '🛵', '#fce8d6', 'A delivery rider', 'Un repartidor en moto', 'バイク便の配達員', 'Um motoboy'),
  ('grandpa', '🧓', '#e7dafa', 'Your grandpa', 'Tu abuelo', 'おじいちゃん', 'Seu avô')
on conflict (id) do update set
  emoji = excluded.emoji,
  tint = excluded.tint,
  en = excluded.en,
  es = excluded.es,
  ja = excluded.ja,
  pt = excluded.pt;
