-- Spanish names of the themes (0026), for the Spanish game. Latin American
-- Spanish first ("Personajes de Los Simpson", "Lentes de sol"). Only fills a
-- missing name: safe to run again.
update public.whoami_themes t
set es = v.es
from (values
  ('a-character-and-their-pet', 'Personaje y su mascota'),
  ('bears', 'Osos'),
  ('big-cats', 'Grandes felinos'),
  ('birds', 'Aves'),
  ('cats', 'Gatos'),
  ('characters-turned-into-animals', 'Personajes convertidos en animales'),
  ('characters-with-an-animal-in-their-name', 'Personajes con nombre de animal'),
  ('characters-with-an-animal-sidekick', 'Personajes con un compañero animal'),
  ('dinosaurs', 'Dinosaurios'),
  ('dogs', 'Perros'),
  ('elephants', 'Elefantes'),
  ('famous-real-life-animals', 'Animales famosos de la vida real'),
  ('farm-animals', 'Animales de granja'),
  ('foxes', 'Zorros'),
  ('horses-and-ponies', 'Caballos y ponis'),
  ('insects-and-spiders', 'Insectos y arañas'),
  ('mascots', 'Mascotas oficiales'),
  ('mice-and-rats', 'Ratones y ratas'),
  ('monkeys-and-apes', 'Monos y simios'),
  ('penguins', 'Pingüinos'),
  ('pigs', 'Cerdos'),
  ('rabbits', 'Conejos'),
  ('reptiles', 'Reptiles'),
  ('talking-animals', 'Animales que hablan'),
  ('wolves', 'Lobos'),
  ('anime-characters', 'Personajes de anime'),
  ('dragon-ball-characters', 'Personajes de Dragon Ball'),
  ('magical-girls', 'Chicas mágicas'),
  ('manga-artists', 'Mangakas'),
  ('manga-characters', 'Personajes de manga'),
  ('naruto-characters', 'Personajes de Naruto'),
  ('one-piece-characters', 'Personajes de One Piece'),
  ('shonen-protagonists', 'Protagonistas de shonen'),
  ('studio-ghibli-characters', 'Personajes de Studio Ghibli'),
  ('tokusatsu-heroes', 'Héroes de tokusatsu'),
  ('cartoonists', 'Dibujantes de cómics'),
  ('characters-from-children-s-books', 'Personajes de libros infantiles'),
  ('classic-literature-characters', 'Personajes de clásicos de la literatura'),
  ('fairy-tale-characters', 'Personajes de cuentos de hadas'),
  ('poets', 'Poetas'),
  ('princes', 'Príncipes'),
  ('princesses', 'Princesas'),
  ('writers', 'Escritores'),
  ('cartoon-network-characters', 'Personajes de Cartoon Network'),
  ('characters-from-old-cartoons', 'Personajes de dibujos animados clásicos'),
  ('characters-that-are-food', 'Personajes que son comida'),
  ('characters-that-are-vehicles', 'Personajes que son vehículos'),
  ('children-s-cartoon-characters', 'Personajes de dibujos animados infantiles'),
  ('christmas-characters', 'Personajes navideños'),
  ('cute-characters', 'Personajes adorables'),
  ('looney-tunes-characters', 'Personajes de los Looney Tunes'),
  ('nickelodeon-characters', 'Personajes de Nickelodeon'),
  ('plant-characters', 'Personajes que son plantas'),
  ('puppet-characters', 'Títeres y marionetas'),
  ('round-shaped-characters', 'Personajes redonditos'),
  ('talking-objects', 'Objetos que hablan'),
  ('the-simpsons-characters', 'Personajes de Los Simpson'),
  ('toy-characters', 'Personajes que son juguetes'),
  ('actors', 'Actores'),
  ('actresses', 'Actrices'),
  ('celebrities-known-by-one-name', 'Famosos conocidos por un solo nombre'),
  ('characters-who-became-memes', 'Personajes que se volvieron meme'),
  ('child-actors', 'Actores infantiles'),
  ('classic-hollywood-stars', 'Estrellas del Hollywood clásico'),
  ('comedians', 'Comediantes'),
  ('comedy-groups', 'Grupos de comedia'),
  ('famous-people-from-the-2000s', 'Famosos de los años 2000'),
  ('famous-people-from-the-60s', 'Famosos de los años 60'),
  ('famous-people-from-the-70s', 'Famosos de los años 70'),
  ('famous-people-from-the-80s', 'Famosos de los años 80'),
  ('famous-people-from-the-90s', 'Famosos de los años 90'),
  ('fashion-designers', 'Diseñadores de moda'),
  ('magicians-and-illusionists', 'Magos e ilusionistas'),
  ('models', 'Modelos'),
  ('movie-directors', 'Directores de cine'),
  ('real-people-with-a-biopic', 'Personas con película biográfica'),
  ('tv-hosts', 'Presentadores de TV'),
  ('youtubers-and-streamers', 'YouTubers y streamers'),
  ('baby-characters', 'Personajes bebés'),
  ('characters-in-a-love-triangle', 'Personajes de triángulos amorosos'),
  ('characters-over-100-years-old', 'Personajes de más de 100 años'),
  ('characters-with-a-famous-sibling', 'Personajes con un hermano famoso'),
  ('child-characters', 'Personajes que son niños'),
  ('children-of-famous-parents', 'Hijos de padres famosos'),
  ('elderly-characters', 'Personajes ancianos'),
  ('famous-couples', 'Parejas famosas'),
  ('famous-dads', 'Papás famosos'),
  ('famous-duos', 'Dúos famosos'),
  ('famous-families', 'Familias famosas'),
  ('famous-moms', 'Mamás famosas'),
  ('famous-trios', 'Tríos famosos'),
  ('groups-of-friends', 'Grupos de amigos'),
  ('half-of-a-famous-couple', 'Mitad de una pareja famosa'),
  ('half-of-a-famous-duo', 'Mitad de un dúo famoso'),
  ('high-school-students', 'Estudiantes de secundaria'),
  ('members-of-a-famous-family', 'Miembros de familias famosas'),
  ('members-of-a-famous-team', 'Miembros de equipos famosos'),
  ('orphans', 'Personajes huérfanos'),
  ('siblings-who-come-as-a-set', 'Hermanos que andan juntos'),
  ('twins', 'Gemelos'),
  ('fighting-game-characters', 'Personajes de juegos de pelea'),
  ('nintendo-characters', 'Personajes de Nintendo'),
  ('poke-mon', 'Pokémon'),
  ('retro-game-characters', 'Personajes de videojuegos retro'),
  ('video-game-characters', 'Personajes de videojuegos'),
  ('video-game-species', 'Especies de videojuegos'),
  ('antiheroes', 'Antihéroes'),
  ('bullies', 'Bravucones'),
  ('characters-who-betrayed-someone', 'Personajes que traicionaron a alguien'),
  ('characters-who-want-to-rule-the-world', 'Personajes que quieren dominar el mundo'),
  ('characters-with-a-famous-rival', 'Personajes con un rival famoso'),
  ('characters-with-a-secret-identity', 'Personajes con identidad secreta'),
  ('chosen-ones', 'Elegidos por el destino'),
  ('comic-book-characters', 'Personajes de cómics'),
  ('comic-relief-characters', 'Personajes cómicos'),
  ('female-superheroes', 'Superheroínas'),
  ('female-villains', 'Villanas'),
  ('hero-and-sidekick', 'Héroe y ayudante'),
  ('hero-teams', 'Equipos de héroes'),
  ('heroes-without-superpowers', 'Héroes sin superpoderes'),
  ('mad-scientists', 'Científicos locos'),
  ('main-characters', 'Protagonistas'),
  ('mentors', 'Mentores'),
  ('sidekicks', 'Fieles escuderos'),
  ('superheroes', 'Superhéroes'),
  ('villain-gangs', 'Pandillas de villanos'),
  ('villains', 'Villanos'),
  ('villains-henchmen', 'Secuaces de villanos'),
  ('villains-who-became-good', 'Villanos que se volvieron buenos'),
  ('ancient-history-figures', 'Personajes de la Antigüedad'),
  ('business-people', 'Empresarios'),
  ('explorers-and-adventurers', 'Exploradores y aventureros'),
  ('historical-figures', 'Personajes históricos'),
  ('inventors', 'Inventores'),
  ('kings', 'Reyes'),
  ('military-leaders', 'Líderes militares'),
  ('painters', 'Pintores'),
  ('philosophers', 'Filósofos'),
  ('politicians', 'Políticos'),
  ('presidents', 'Presidentes'),
  ('queens', 'Reinas'),
  ('revolutionaries', 'Revolucionarios'),
  ('scientists', 'Científicos'),
  ('women-who-made-history', 'Mujeres que hicieron historia'),
  ('airplane-pilots', 'Pilotos de avión'),
  ('butlers', 'Mayordomos'),
  ('characters-who-are-bosses', 'Personajes que son jefes'),
  ('chefs-and-cooks', 'Chefs y cocineros'),
  ('clowns', 'Payasos'),
  ('detectives', 'Detectives'),
  ('doctors', 'Médicos'),
  ('journalists', 'Periodistas'),
  ('lawyers', 'Abogados'),
  ('maids', 'Sirvientas'),
  ('office-workers', 'Oficinistas'),
  ('police-officers', 'Policías'),
  ('ship-captains', 'Capitanes de barco'),
  ('soldiers', 'Soldados'),
  ('spies', 'Espías'),
  ('teachers', 'Profesores'),
  ('bald-characters', 'Personajes calvos'),
  ('blond-characters', 'Personajes rubios'),
  ('blue-characters', 'Personajes azules'),
  ('characters-who-dress-in-black', 'Personajes que se visten de negro'),
  ('characters-who-wear-a-cape', 'Personajes que usan capa'),
  ('characters-who-wear-a-hat', 'Personajes que usan sombrero'),
  ('characters-who-wear-a-helmet', 'Personajes que usan casco'),
  ('characters-who-wear-a-hood', 'Personajes que usan capucha'),
  ('characters-who-wear-a-mask', 'Personajes que usan máscara'),
  ('characters-who-wear-a-suit', 'Personajes que usan traje'),
  ('characters-who-wear-armor', 'Personajes que usan armadura'),
  ('characters-who-wear-glasses', 'Personajes que usan lentes'),
  ('characters-who-wear-sunglasses', 'Personajes que usan lentes de sol'),
  ('characters-with-a-beard', 'Personajes con barba'),
  ('characters-with-a-big-nose', 'Personajes narigudos'),
  ('characters-with-a-color-in-their-name', 'Personajes con un color en el nombre'),
  ('characters-with-a-facial-scar', 'Personajes con una cicatriz en la cara'),
  ('characters-with-a-mustache', 'Personajes con bigote'),
  ('characters-with-an-iconic-hairstyle', 'Personajes con un peinado icónico'),
  ('characters-with-big-ears', 'Personajes orejones'),
  ('characters-with-freckles', 'Personajes pecosos'),
  ('characters-with-tattoos', 'Personajes tatuados'),
  ('green-characters', 'Personajes verdes'),
  ('one-eyed-characters', 'Personajes de un solo ojo'),
  ('orange-characters', 'Personajes anaranjados'),
  ('pink-characters', 'Personajes rosados'),
  ('purple-characters', 'Personajes morados'),
  ('red-characters', 'Personajes rojos'),
  ('redheads', 'Personajes pelirrojos'),
  ('yellow-characters', 'Personajes amarillos'),
  ('band-members', 'Integrantes de bandas'),
  ('bands-and-music-groups', 'Bandas y grupos musicales'),
  ('bands-from-cartoons-and-anime', 'Bandas de dibujos animados y anime'),
  ('characters-who-dance', 'Personajes que bailan'),
  ('characters-who-sing', 'Personajes que cantan'),
  ('characters-with-a-famous-theme-song', 'Personajes con un tema musical famoso'),
  ('classical-composers', 'Compositores clásicos'),
  ('djs', 'DJs'),
  ('female-singers', 'Cantantes femeninas'),
  ('guitarists', 'Guitarristas'),
  ('j-pop-idols', 'Idols de J-pop'),
  ('k-pop-idols', 'Idols de K-pop'),
  ('male-singers', 'Cantantes masculinos'),
  ('music-duos', 'Dúos musicales'),
  ('rappers', 'Raperos'),
  ('rock-stars', 'Estrellas de rock'),
  ('angels', 'Ángeles'),
  ('biblical-characters', 'Personajes bíblicos'),
  ('creatures-that-come-in-crowds', 'Criaturitas que andan en grupo'),
  ('demons', 'Demonios'),
  ('dragons', 'Dragones'),
  ('elves', 'Elfos'),
  ('fairies', 'Hadas'),
  ('fantasy-characters', 'Personajes de fantasía'),
  ('fantasy-races', 'Razas de fantasía'),
  ('ghosts', 'Fantasmas'),
  ('giant-characters', 'Personajes gigantes'),
  ('goddesses', 'Diosas'),
  ('gods', 'Dioses'),
  ('greek-mythology-characters', 'Personajes de la mitología griega'),
  ('half-human-characters', 'Personajes mitad humanos'),
  ('legendary-creatures', 'Criaturas legendarias'),
  ('monsters', 'Monstruos'),
  ('non-humans', 'Personajes no humanos'),
  ('tiny-characters', 'Personajes diminutos'),
  ('urban-legends', 'Leyendas urbanas'),
  ('vampires', 'Vampiros'),
  ('witches', 'Brujas'),
  ('zombies-and-undead', 'Zombis y muertos vivientes'),
  ('characters-sent-to-another-world', 'Personajes llevados a otro mundo'),
  ('characters-who-came-back-from-the-dead', 'Personajes que volvieron de la muerte'),
  ('characters-who-can-fly', 'Personajes que vuelan'),
  ('characters-who-can-see-the-future', 'Personajes que ven el futuro'),
  ('characters-who-can-talk-to-animals', 'Personajes que hablan con animales'),
  ('characters-who-can-turn-invisible', 'Personajes que se vuelven invisibles'),
  ('characters-who-got-kidnapped', 'Personajes que fueron secuestrados'),
  ('characters-who-lost-their-memory', 'Personajes que perdieron la memoria'),
  ('characters-who-transform', 'Personajes que se transforman'),
  ('characters-who-use-gadgets', 'Personajes que usan artefactos'),
  ('characters-who-use-magic', 'Personajes que usan magia'),
  ('characters-with-a-famous-special-move', 'Personajes con un ataque especial famoso'),
  ('characters-with-a-magic-item', 'Personajes con un objeto mágico'),
  ('characters-with-electric-powers', 'Personajes con poderes eléctricos'),
  ('characters-with-fire-powers', 'Personajes con poderes de fuego'),
  ('characters-with-mind-powers', 'Personajes con poderes mentales'),
  ('cursed-characters', 'Personajes malditos'),
  ('immortal-characters', 'Personajes inmortales'),
  ('mutants', 'Mutantes'),
  ('super-fast-characters', 'Personajes con supervelocidad'),
  ('super-strong-characters', 'Personajes con superfuerza'),
  ('always-cheerful-characters', 'Personajes siempre alegres'),
  ('arrogant-characters', 'Personajes arrogantes'),
  ('characters-who-are-poor', 'Personajes pobres'),
  ('characters-who-love-to-eat', 'Personajes glotones'),
  ('characters-who-never-talk', 'Personajes que no hablan'),
  ('characters-who-ride-motorcycles', 'Personajes que andan en moto'),
  ('characters-whose-name-ends-in-man', 'Personajes con nombre terminado en “man”'),
  ('characters-whose-name-is-the-title', 'Personajes que dan nombre a la obra'),
  ('characters-with-a-catchphrase', 'Personajes con una frase característica'),
  ('characters-with-a-famous-favorite-food', 'Personajes con una comida favorita famosa'),
  ('characters-with-a-famous-vehicle', 'Personajes con un vehículo famoso'),
  ('characters-with-a-number-in-their-name', 'Personajes con un número en el nombre'),
  ('characters-with-matching-initials', 'Personajes con iniciales iguales'),
  ('clumsy-characters', 'Personajes torpes'),
  ('geniuses', 'Genios'),
  ('gloomy-characters', 'Personajes pesimistas'),
  ('greedy-characters', 'Personajes codiciosos'),
  ('grumpy-or-hot-tempered-characters', 'Personajes gruñones o de mal genio'),
  ('lazy-characters', 'Personajes perezosos'),
  ('liars-and-tricksters', 'Mentirosos y tramposos'),
  ('nerds', 'Nerds'),
  ('rebels', 'Rebeldes'),
  ('rich-characters', 'Personajes ricos'),
  ('scaredy-cats', 'Personajes miedosos'),
  ('spoiled-characters', 'Personajes mimados'),
  ('ai-characters', 'Inteligencias artificiales'),
  ('aliens', 'Extraterrestres'),
  ('characters-who-went-to-space', 'Personajes que fueron al espacio'),
  ('cyborgs', 'Cíborgs'),
  ('robots', 'Robots'),
  ('sci-fi-characters', 'Personajes de ciencia ficción'),
  ('spaceship-pilots', 'Pilotos de naves espaciales'),
  ('star-wars-characters', 'Personajes de Star Wars'),
  ('starship-captains', 'Capitanes de naves espaciales'),
  ('time-travelers', 'Viajeros en el tiempo'),
  ('action-movie-heroes', 'Héroes de películas de acción'),
  ('animated-movie-characters', 'Personajes de películas animadas'),
  ('characters-with-multiple-versions', 'Personajes con varias versiones'),
  ('comedy-movie-characters', 'Personajes de películas de comedia'),
  ('dc-characters', 'Personajes de DC'),
  ('disney-characters', 'Personajes de Disney'),
  ('dreamworks-characters', 'Personajes de DreamWorks'),
  ('harry-potter-characters', 'Personajes de Harry Potter'),
  ('horror-movie-characters', 'Personajes de películas de terror'),
  ('marvel-characters', 'Personajes de Marvel'),
  ('pixar-characters', 'Personajes de Pixar'),
  ('the-lord-of-the-rings-characters', 'Personajes de El Señor de los Anillos'),
  ('tv-series-characters', 'Personajes de series de TV'),
  ('basketball-players', 'Jugadores de básquetbol'),
  ('boxers', 'Boxeadores'),
  ('coaches-and-trainers', 'Entrenadores'),
  ('fictional-athletes', 'Atletas ficticios'),
  ('martial-artists', 'Artistas marciales'),
  ('olympic-athletes', 'Atletas olímpicos'),
  ('pro-wrestlers', 'Luchadores profesionales'),
  ('race-car-drivers', 'Pilotos de carreras'),
  ('soccer-players', 'Futbolistas'),
  ('tennis-players', 'Tenistas'),
  ('archers', 'Arqueros'),
  ('assassins', 'Asesinos a sueldo'),
  ('characters-who-use-weapons', 'Personajes que usan armas'),
  ('criminals', 'Criminales'),
  ('hunters', 'Cazadores'),
  ('knights', 'Caballeros'),
  ('ninjas', 'Ninjas'),
  ('pirates', 'Piratas'),
  ('samurai', 'Samuráis'),
  ('swordfighters', 'Espadachines'),
  ('thieves', 'Ladrones'),
  ('vikings', 'Vikingos'),
  ('warrior-women', 'Mujeres guerreras'),
  ('wild-west-characters', 'Personajes del Viejo Oeste'),
  ('characters-who-live-in-new-york', 'Personajes que viven en Nueva York'),
  ('characters-who-live-in-the-desert', 'Personajes que viven en el desierto'),
  ('characters-who-live-in-the-jungle', 'Personajes que viven en la selva'),
  ('characters-who-live-in-the-sea', 'Personajes que viven en el mar'),
  ('characters-who-live-on-an-island', 'Personajes que viven en una isla'),
  ('famous-americans', 'Estadounidenses famosos'),
  ('famous-brazilians', 'Brasileños famosos'),
  ('famous-british-people-and-characters', 'Personajes y famosos británicos'),
  ('famous-chinese-people-and-characters', 'Personajes y famosos chinos'),
  ('famous-french-people-and-characters', 'Personajes y famosos franceses'),
  ('famous-italian-people-and-characters', 'Personajes y famosos italianos'),
  ('famous-japanese-people', 'Japoneses famosos'),
  ('famous-mexican-people-and-characters', 'Personajes y famosos mexicanos'),
  ('famous-spanish-people-and-characters', 'Personajes y famosos españoles'),
  ('ice-and-snow-characters', 'Personajes del hielo y la nieve'),
  ('airplane-and-spaceship-pilots', 'Pilotos de avión o nave espacial'),
  ('angels-and-demons', 'Ángeles y demonios'),
  ('butlers-and-maids', 'Mayordomos y sirvientas'),
  ('cartoonists-and-manga-artists', 'Dibujantes de cómics y mangakas'),
  ('characters-who-wear-a-mask-or-helmet', 'Personajes que usan máscara o casco'),
  ('characters-with-a-beard-or-mustache', 'Personajes con barba o bigote'),
  ('comic-book-and-manga-characters', 'Personajes de cómics y manga'),
  ('fairies-and-elves', 'Hadas y elfos'),
  ('famous-people-from-the-60s-or-70s', 'Famosos de los años 60 o 70'),
  ('foxes-and-wolves', 'Zorros y lobos'),
  ('gods-and-goddesses', 'Dioses y diosas'),
  ('k-pop-and-j-pop-idols', 'Idols de K-pop y J-pop'),
  ('kings-and-queens', 'Reyes y reinas'),
  ('ninjas-and-samurai', 'Ninjas y samuráis')
) as v(id, es)
where t.id = v.id and t.es is null;
